options(unbrief.minimal=TRUE,unbrief.root=getwd())
for(f in list.files('R',pattern='^[0-9].*\\.R$',full.names=TRUE))source(f)
hc<-readRDS('output/2026-09-23/hierarchical_reference/audit/analytics/artifacts/M07.rds')
pam<-readRDS('validation/pam_reference_final/audit/analytics/artifacts/M09.rds')
m02a<-readRDS('output/2026-09-23/hierarchical_reference/audit/analytics/artifacts/M02.rds')
m02b<-readRDS('validation/pam_reference_final/audit/analytics/artifacts/M02.rds')
stopifnot(identical(sha_object(m02a),sha_object(m02b)),identical(hc$feature_sha256,pam$feature_sha256),identical(hc$numerical$distance,pam$numerical$distance))
hg<-hc$numerical$selected_groups;pg<-pam$numerical$selected_groups;stopifnot(identical(sort(names(hg)),sort(names(pg))))
ari<-hc_ari(hg[names(pg)],pg)
hsizes<-sort(as.integer(table(hg)),decreasing=TRUE);psizes<-sort(as.integer(table(pg)),decreasing=TRUE)
report<-list(schema='D1-I4-checkpoint-audit-v1',R=R.version.string,Matrix=as.character(packageVersion('Matrix')),cluster=as.character(packageVersion('cluster')),feature_sha256=hc$feature_sha256,distance_matrices_identical=TRUE,countries=length(hg),hierarchical=list(selected_k=hc$numerical$selected_k,cluster_sizes=hsizes,mean_silhouette=hc$numerical$candidates$mean_silhouette[hc$numerical$candidates$selected_primary],mean_ari=hc$numerical$candidates$mean_ari[hc$numerical$candidates$selected_primary],quality_passed=hc$quality$passed),pam=list(selected_k=pam$numerical$selected_k,cluster_sizes=psizes,medoids=pam$numerical$selected_medoids,mean_silhouette=pam$numerical$candidates$mean_silhouette[pam$numerical$candidates$selected_primary],mean_ari=pam$numerical$candidates$mean_ari[pam$numerical$candidates$selected_primary],medoid_retention=pam$numerical$medoid_stability$retention_fraction[pam$numerical$medoid_stability$candidate_id==pam$numerical$selected_id],quality_passed=pam$quality$passed),partition_ari_between_m07_and_m09=ari,interpretation='Both methods use the same frozen lexical geometry. Their low separation/stability and divergent partitions support audit-only treatment; no geopolitical meaning is inferred.')
json_write('validation/CHECKPOINT_CLUSTERING_AUDIT.json',report)
cat(json_text(report), '\n')
