#!/usr/bin/env Rscript
options(unbrief.minimal=TRUE)
source('R/00_core.R')
for(f in list.files('R',pattern='^[0-9].*\\.R$',full.names=TRUE)) source(f)
read_tests<-function(path){x<-json_read(path);list(tests=as.integer(x$tests),failed=as.integer(x$failed))}
tests<-list(base=read_tests('validation/r_tests.json'),d1=read_tests('validation/d1_tests.json'),i2=read_tests('validation/i2_tests.json'),hierarchical=read_tests('validation/hierarchical_tests.json'),pam=read_tests('validation/pam_tests.json'))
stopifnot(sum(vapply(tests,`[[`,integer(1),'failed'))==0L,sum(vapply(tests,`[[`,integer(1),'tests'))==371L)
stopifnot(identical(sha_file('config/pam_policy.json'),sha_file('design/D1-PAM/pam_policy.json')))
registry<-read_d1_registry(getwd());stopifnot(nrow(registry)==42L,identical(names(d1_adapters()),c('M01','M02','M05','M06','M07','M09')))
stopifnot(!any(c('M07','M09') %in% D1_READY_PRODUCERS))
hc<-readRDS('output/2026-09-23/hierarchical_reference/audit/analytics/artifacts/M07.rds')
pam<-readRDS('validation/pam_reference_final/audit/analytics/artifacts/M09.rds')
stopifnot(identical(hc$feature_sha256,pam$feature_sha256),identical(hc$numerical$distance,pam$numerical$distance),!hc$quality$passed,!pam$quality$passed)
stopifnot(!dir.exists('history'),!dir.exists('models'),!dir.exists('cache'),!dir.exists('output/.run-lock'))
secret_files<-list.files('.',recursive=TRUE,all.files=TRUE,pattern='(^|/)\\.secrets$|runtime\\.local\\.json$|library_path\\.txt$',full.names=TRUE)
stopifnot(length(secret_files)==0L)
parse_files<-c(list.files('R',pattern='\\.R$',full.names=TRUE),list.files('.',pattern='\\.R$',full.names=TRUE))
for(f in parse_files) parse(f)
ca<-json_read('validation/CHECKPOINT_CLUSTERING_AUDIT.json')
stopifnot(isTRUE(ca$distance_matrices_identical),ca$countries==39L,abs(ca$partition_ari_between_m07_and_m09+0.01166620916826793)<1e-12)
report<-list(schema='D1-I4-project-audit-v1',release='2.5.0-d1-i4-checkpoint',generated_at=utc_now(),R=R.version.string,Matrix=as.character(packageVersion('Matrix')),cluster=as.character(packageVersion('cluster')),r_scripts_parsed=length(parse_files),test_suites=tests,total_tests=371L,total_failures=0L,registry_methods=42L,implemented_adapters=names(d1_adapters()),unimplemented_adapter_count=36L,prerequisite_count=133L,pam_policy_frozen=TRUE,no_clustering_ready_producer=TRUE,active_mutable_state_absent=TRUE,local_secret_or_runtime_files=unname(secret_files),source_feature_sha256=pam$feature_sha256,hierarchical_quality_passed=hc$quality$passed,pam_quality_passed=pam$quality$passed,pam_selected_k=pam$numerical$selected_k,pam_medoids=unname(pam$numerical$selected_medoids),cross_method_selected_partition_ari=ca$partition_ari_between_m07_and_m09,full_39_speech_combined_replay='attempt exceeded interactive execution window after preparation; not counted as acceptance',email_sent=FALSE,scheduled_task_created=FALSE)
json_write('validation/PROJECT_AUDIT.json',report)
cat('PROJECT AUDIT PASSED: 371 tests, 0 failures; 34 R scripts parsed; PAM remains audit-only.\n')
