args <- commandArgs(trailingOnly = TRUE)
root <- normalizePath(if (length(args)) args[[1L]] else ".", winslash = "/")
source(file.path(root, "R", "load.R"))
load_readout(root, globalenv())
Sys.setlocale("LC_CTYPE", "C.UTF-8")
records <- list()
check <- function(name, expression) {
  error <- NULL
  result <- tryCatch(isTRUE(force(expression)), error = function(e) { error <<- conditionMessage(e); FALSE })
  records[[length(records) + 1L]] <<- data.frame(test = name, passed = result, detail = error %||% "", stringsAsFactors = FALSE)
  cat(if (result) "PASS" else "FAIL", "|", name, if (!is.null(error)) paste("|", error) else "", "\n")
}
fails <- function(expr, pattern = "") {
  tryCatch({force(expr); FALSE}, error = function(e) !nzchar(pattern) || grepl(pattern, conditionMessage(e), fixed = TRUE))
}
work <- tempfile("readout-tests-")
dir.create(work)
config <- new_config("2026-09-23", "2026-09-25", DEFAULT_TOPICS)
check("Four default topics preserve order", identical(vapply(config$fixed_topics, `[[`, character(1), "label"), DEFAULT_TOPICS))
check("Arbitrary topic labels", make_topics("Climate finance")[[1L]]$label == "Climate finance")
check("Case-insensitive duplicate topics collapse", length(make_topics(c("Iran", "iran", "Cuba"))) == 2L)
check("Whitespace is normalized", make_topics("  Food   security ")[[1L]]$label == "Food security")
check("Empty topic list is valid", length(make_topics(character())) == 0L)
check("Twenty-topic limit enforced", fails(make_topics(paste("Topic", 1:21))))
check("Overlong topic refused", fails(make_topics(paste(rep("a", 101), collapse = ""))))
check("Empty topic refused", fails(make_topics("   ")))
check("Overlapping inclusion/exclusion refused", fails(make_topics("AI", list(AI = list(exclude = "AI")))))
check("AI alias explicitly included for default", "AI" %in% unlist(make_topics("Artificial Intelligence")[[1L]]$include))
check("Acronym AI does not match Haiti", !phrase_hit("Haiti discussed aid.", "AI"))
check("Acronym AI matches uppercase", phrase_hit("AI oversight matters.", "AI"))
check("Acronym AI is case-sensitive", !phrase_hit("The letters ai are lowercase.", "AI"))
check("Ordinary phrase matching ignores case", phrase_hit("ARTIFICIAL INTELLIGENCE", "Artificial intelligence"))
check("Regex punctuation is literal", phrase_hit("C++ research", "C++") && !phrase_hit("CCCC", "C++"))
check("Regex wildcard is not interpreted", !phrase_hit("anything at all", ".*"))
check("Valid leap date accepted", valid_date("2024-02-29"))
check("Invalid leap date rejected", !valid_date("2026-02-29"))
check("Date normalization cannot admit invalid day", !valid_date("2026-09-31"))
check("Reversed dates rejected", fails(new_config("2026-09-25", "2026-09-23", DEFAULT_TOPICS)))
check("Long reporting window rejected", fails(new_config("2026-01-01", "2026-03-01", DEFAULT_TOPICS)))
check("Full corpus discovery cannot be disabled in normal request", isTRUE(config$discover_themes))
check("External processing defaults off", identical(config$external_processing, FALSE))
check("No-send request contract", identical(config$email_delivery, "draft_only"))
check("SHA-256 matches known fixture", sha256_text("abc") == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
check("JSON escaping control and quote characters", identical(json_quote('a\n"b'), '"a\\u000a\\"b"'))
check("Base64 single byte", base64_encode("f") == "Zg==")
check("Base64 two bytes", base64_encode("fo") == "Zm8=")
check("Base64 three bytes", base64_encode("foo") == "Zm9v")
check("Base64 MIME lines bounded", all(nchar(strsplit(wrap_base64(base64_encode(paste(rep("hello", 100), collapse = ""))), "\r\n", fixed = TRUE)[[1L]]) <= 76L))
check("HTML text is escaped", html_escape('<img src="x">&') == "&lt;img src=&quot;x&quot;&gt;&amp;")

s <- parse_transcript(file.path(root, "tests", "fixtures", "topic_header.txt"))
check("TXT metadata separated from body", !grepl("Artificial Intelligence", s$text, fixed = TRUE))
check("TXT country and date parsed", s$country == "Example One" && s$speech_date == "2026-09-24")
check("ZIP traversal is refused before extraction", fails(safe_zip_members(file.path(root, "tests/fixtures/unsafe.zip"))))
check("Safe nested ZIP member accepted", nrow(safe_zip_members(file.path(root, "tests/fixtures/safe.zip"))) == 1L)
loaded <- load_inputs(file.path(root, "tests/fixtures/safe.zip"), "safe.zip", file.path(work, "zip"))
check("Safe ZIP streamed to generated filenames", nrow(loaded) == 1L && loaded$country == "Example One")
scope <- scope_statements(s, config)
check("English source eligible for discovery", isTRUE(scope$discovery_eligible))
check("Topic in metadata does not create body hit", nrow(match_topics(scope, config$fixed_topics)$evidence) == 0L)
blank <- s; blank$text <- ""; blank$body_sha256 <- sha256_text(""); blank$statement_id <- "BLANK"
blank <- scope_statements(blank, config)
check("Blank record is missing text", blank$status == "missing_text" && !blank$discovery_eligible)
unknown <- s; unknown$speech_date <- ""; unknown <- scope_statements(unknown, config)
check("Undated source is not silently assigned", unknown$status == "invalid_or_missing_date")
nonenglish <- s; nonenglish$language <- "fr"; nonenglish <- scope_statements(nonenglish, config)
check("Non-English text retained but excluded from English discovery", nonenglish$status == "available" && !nonenglish$discovery_eligible)
duplicate <- rbind(s,s); duplicate$statement_id[[2L]] <- "DUPLICATE"
duplicate <- scope_statements(duplicate, config)
check("Duplicate source accounting", identical(duplicate$status, c("available", "duplicate_source")))
outside <- s; outside$speech_date <- "2026-09-22"; outside <- scope_statements(outside, config)
check("Date range excludes outside records", outside$status == "outside_reporting_period")
check("Missing text yields no topic evidence", nrow(match_topics(blank, config$fixed_topics)$evidence) == 0L)

multi <- s; multi$text <- "AI military uses are an example. AI education uses are another example. Food security also appears."; multi$body_sha256 <- sha256_text(multi$text); multi <- scope_statements(multi, config)
tracks <- make_topics(c("Artificial Intelligence", "Food security"), list("Artificial Intelligence" = list(include = "AI", exclude = "military")))
matched <- match_topics(multi, tracks)
check("Exclusion applies to passage, not entire transcript", sum(matched$evidence$topic == "Artificial Intelligence") == 1L)
check("Multi-label text receives both topic candidates", all(matched$summary$texts_with_matches == 1L))
check("All quotation character spans verified", validate_evidence(matched$evidence, multi))
bad <- matched$evidence; bad$quote[[1L]] <- "Fabricated quote"
check("Tampered quotation blocks output", fails(validate_evidence(bad, multi)))
check("No-match is unresolved, not absent", match_topics(multi, make_topics("Never mentioned"))$summary$unresolved_texts == 1L)

packets <- make_packets(config)
check("Exactly five ordered analytical slots", validate_packets(packets))
check("Sixth slot rejected", fails(validate_packets(c(packets, list(packets[[1L]])))))
bad_packets <- packets; bad_packets[[2L]]$released <- TRUE
check("Config flag cannot release research output", fails(validate_packets(bad_packets)))
bad_packets <- packets; bad_packets[[1L]]$payload <- 7
check("Unvalidated numerical payload rejected", fails(validate_packets(bad_packets)))
email <- render_email(config, multi, matched, packets, "unit_test")
check("Email draft has X-Unsent header", grepl("X-Unsent: 1\r\n", email$eml, fixed = TRUE))
check("Email has no recipient or sender", !grepl("(^|\r\n)(To|From|Cc|Bcc):", email$eml, perl = TRUE))
check("MIME has plaintext and HTML", grepl("text/plain", email$eml, fixed = TRUE) && grepl("text/html", email$eml, fixed = TRUE))
check("Full-width HTML outer layout", grepl('width="100%"', email$html, fixed = TRUE))
check("Learned candidate table not inserted into email", !grepl("suggested_terms", email$html, fixed = TRUE))
check("Missing D1 folder fails closed", !inspect_d1(file.path(work, "absent"))$ready)
legacy <- file.path(work, "legacy"); dir.create(file.path(legacy,"R"), recursive = TRUE)
for (f in c("run_daily.R", "R/16_analytics_pipeline.R", "R/15_publish_packets.R")) writeLines("# inert legacy fixture", file.path(legacy, f))
check("Legacy D1 cannot accept unsupported custom topics", inspect_d1(legacy)$status == "integration_patch_required")
check("Capability handshake fails closed", fails(validate_d1_capabilities(list(request_schema = "un.readout.request.v1"))))
caps <- list(request_schema = "un.readout.request.v1", dynamic_topics = TRUE, full_corpus_discovery = TRUE,
  immutable_requests = TRUE, publication_gates = TRUE, exactly_five_outputs = TRUE, no_send = TRUE,
  honors_no_external_processing = TRUE)
check("Complete bridge capability contract accepted", validate_d1_capabilities(caps))
check("Path escape is rejected", fails(assert_inside(file.path(root, "app.R"), work)))

# Export protection does not change the internal evidence objects.
csv_input <- data.frame(text = c("=1+1", "  @SUM(A1)", "-command", "ordinary", "\t=2"),
  value = c(-2, 0, 1, 2, 3), stringsAsFactors = FALSE)
csv_output <- csv_safe(csv_input)
check("CSV formulas are exported as text", all(startsWith(csv_output$text[c(1, 2, 3, 5)], "'")))
check("CSV ordinary text stays unchanged", csv_output$text[[4L]] == "ordinary")
check("CSV numeric values stay numeric", identical(csv_output$value, csv_input$value))
check("CSV protection does not mutate source evidence", csv_input$text[[1L]] == "=1+1")

# Full base-R pipeline run. These are synthetic tests, never a replay of real speeches.
demo_dir <- file.path(root, "validation", "demo_run")
if (dir.exists(demo_dir)) unlink(demo_dir, recursive = TRUE)
result <- tryCatch(run_readout(config, demo_dir, root, make_pdf = TRUE), error = function(e) { cat("END-TO-END FAILURE:", conditionMessage(e), "\n"); NULL })
check("Complete synthetic pipeline returns result", !is.null(result))
if (!is.null(result)) {
  check("18 synthetic statements available", sum(result$statements$status == "available") == 18L)
  check("Six synthetic AI text matches", result$tracked$summary$texts_with_matches[result$tracked$summary$topic == "Artificial Intelligence"] == 6L)
  check("Source evidence revalidated after full run", validate_evidence(result$tracked$evidence, result$statements))
  check("Hierarchy and PAM both executed", setequal(unique(result$discovery$diagnostics$method), c("hierarchical", "PAM")))
  check("Research candidates stay audit-only", identical(result$discovery$released, FALSE) && all(!result$discovery$diagnostics$publication_eligible))
  check("Unsupervised geometry saved", !is.null(result$discovery$pca) && !is.null(result$discovery$pcoa))
  check("PDF actually created", result$pdf$status == "created" && file.exists(result$files$pdf))
  check("Request JSON saved", file.exists(result$files$request))
  check("Completed run cannot be overwritten", fails(run_readout(config, demo_dir, root, make_pdf = FALSE)))
  alternate <- new_config("2026-09-23", "2026-09-25", c("Climate finance", "Food security", "Nuclear weapons"))
  alternate_dir <- file.path(work, "alternate")
  result2 <- run_readout(alternate, alternate_dir, root, make_pdf = FALSE)
  check("Changing topics does not change discovery feature hash", identical(result$feature_hash, result2$feature_hash))
  check("Changing topics does not change learned groups", identical(result$discovery$assignments, result2$discovery$assignments))
  check("Custom categories replace default watchlist in request", identical(result2$tracked$summary$topic, c("Climate finance", "Food security", "Nuclear weapons")))
  check("Unknown category remains unresolved", result2$tracked$summary$unresolved_texts[result2$tracked$summary$topic == "Nuclear weapons"] == 18L)
  check("PCA and PCoA are not published", all(!vapply(result$packets, `[[`, logical(1), "released")))
  empty_config <- new_config("2026-09-01", "2026-09-01", character())
  empty <- run_readout(empty_config, file.path(work, "no_data"), root, make_pdf = FALSE)
  check("Empty corpus produces explicit coverage-only draft", sum(empty$statements$status == "available") == 0L && length(empty$packets) == 5L)
  check("No-topic run leaves discovery enabled", empty$config$discover_themes && nrow(empty$tracked$summary) == 0L)
}

# Parse every R file, including front end, without pretending dependencies ran.
rfiles <- list.files(root, "\\.R$", recursive = TRUE, full.names = TRUE)
for (f in rfiles) check(paste("R syntax:", substring(f, nchar(root) + 2L)), {parse(f); TRUE})
report <- do.call(rbind, records)
utils::write.csv(report, file.path(root, "validation", "test_results.csv"), row.names = FALSE)
writeLines(capture.output(sessionInfo()), file.path(root, "validation", "R_sessionInfo.txt"))
cat("\nRESULT:", sum(report$passed), "/", nrow(report), "checks passed;", sum(!report$passed), "failed.\n")
if (any(!report$passed)) quit(status = 1L)
