#!/usr/bin/env Rscript
# Explicit local engineering runner; the daily pipeline never imports these outputs.
a<-commandArgs(TRUE);if(length(a)!=3)stop('Usage: Rscript research/run.R Mxx input.rds output.rds')
self<-sub('^--file=','',commandArgs(FALSE)[grepl('^--file=',commandArgs(FALSE))][1]);root<-normalizePath(dirname(self),winslash='/',mustWork=TRUE)
if(dir.exists(file.path(root,'library'))).libPaths(c(file.path(root,'library'),.libPaths()))
source(file.path(root,'engines.R'));i6_need('digest')
i6_assert(!file.exists(a[3])&&!file.exists(paste0(a[3],'.sha256')),'Output already exists; use a new immutable output name')
d<-readRDS(a[2]);value<-i6_compute(a[1],d)
value$input_sha256<-digest::digest(file=a[2],algo='sha256');value$engine_sha256<-digest::digest(file=file.path(root,'engines.R'),algo='sha256')
value$additional_engine_sha256<-digest::digest(file=file.path(root,'engines_more.R'),algo='sha256')
value$created_at<-format(Sys.time(),tz='UTC',format='%Y-%m-%dT%H:%M:%SZ')
value$packages<-vapply(c('glmnet','uwot','dbscan','ranger','isotree','changepoint','clue','gbm','topicmodels','stm','depmixS4','blockmodels','posterior','RhpcBLASctl'),function(p)if(requireNamespace(p,quietly=TRUE))as.character(packageVersion(p)) else 'not_installed',character(1))
dir.create(dirname(a[3]),recursive=TRUE,showWarnings=FALSE);saveRDS(value,a[3],version=2)
writeLines(digest::digest(file=a[3],algo='sha256'),paste0(a[3],'.sha256'))
cat('Saved synthetic engineering output. Not a daily adapter or a released analytical result.\n')
