args<-commandArgs(TRUE);if(length(args)).libPaths(c(args[1],.libPaths()))
source('research/engines.R')
records<-list();test<-function(name,expr){e<-tryCatch({force(expr);NULL},error=function(e)conditionMessage(e));records[[length(records)+1]]<<-data.frame(test=name,passed=is.null(e),error=if(is.null(e))'' else e);cat(if(is.null(e))'PASS' else 'FAIL',name,if(!is.null(e))e,'\n')}
reject<-function(expr)stopifnot(tryCatch({force(expr);FALSE},error=function(e)TRUE))
kind<-function(d){d$dataset_kind<-'synthetic_engineering';d}
set.seed(901);mat<-function(n,p=2,prefix='r'){x<-matrix(rnorm(n*p),n,p);rownames(x)<-paste0(prefix,seq_len(n));colnames(x)<-paste0('x',seq_len(p));x}
part<-function(prefix,n=300,offset=0){x<-mat(n,prefix=prefix);list(x=x,y=rbinom(n,1,plogis(.3+1.2*x[,1]-.6*x[,2])),time=seq_len(n)+offset,country=paste0(prefix,'country',seq_len(n)),text_hash=paste0(prefix,'hash',seq_len(n)))}
d<-kind(list(train=part('train'),calibration=part('cal',offset=1000),test=part('test',offset=2000),representation_id='synthetic-v1'))
test('All 27 research kernels have explicit IDs',stopifnot(length(i6_ids)==27,!anyDuplicated(i6_ids)))
test('Real or unreviewed data cannot enter experimental path',{z<-d;z$dataset_kind<-'real';reject(i6_compute('M11',z))})
for(id in c('M11','M12','M13','M15','M37'))test(paste(id,'held-out predictions and bounds'),{v<-i6_compute(id,d);stopifnot(!v$publication_eligible,!v$daily_adapter_integrated,length(v$value$scores)==300,all(v$value$scores>0&v$value$scores<1),v$value$test_logloss<v$value$baseline_logloss)})
test('Training and test country overlap rejected',{z<-d;z$test$country[1]<-z$train$country[1];reject(i6_compute('M11',z))})
test('Text duplicate leakage rejected',{z<-d;z$test$text_hash[1]<-z$train$text_hash[1];reject(i6_compute('M12',z))})
test('Future training observations rejected',{z<-d;z$train$time[1]<-9999;reject(i6_compute('M11',z))})
test('Missing labels do not become negatives',{z<-d;z$train$y[1]<-NA;reject(i6_compute('M11',z))})
test('Changed feature order rejected',{z<-d;colnames(z$test$x)<-rev(colnames(z$test$x));reject(i6_compute('M12',z))})
test('Perfect separation rejected',{z<-d;z$train$y<-as.numeric(z$train$x[,1]>0);reject(i6_compute('M11',z))})
test('Random state restored',{old<-.Random.seed;invisible(i6_compute('M13',d));stopifnot(identical(old,.Random.seed))})
stance_part<-function(prefix,offset){z<-part(prefix,400,offset);z$y<-rep(c('support','oppose','conditional','descriptive'),100);j<-match(z$y,c('support','oppose','conditional','descriptive'));z$x[,1]<-z$x[,1]+c(-2,2,-2,2)[j];z$x[,2]<-z$x[,2]+c(-2,-2,2,2)[j];z}
st<-kind(list(train=stance_part('st',0),calibration=stance_part('sc',1000),test=stance_part('se',2000),proposition_id='fictional-p1',target='fictional-target',representation_id='synthetic-v1'))
test('M17 proposition-specific scores and abstention vocabulary',{v<-i6_compute('M17',st)$value;stopifnot(all(abs(rowSums(v$scores)-1)<1e-8),!any(v$predicted=='neutral'),identical(v$proposition_id,'fictional-p1'),v$test_logloss<log(4))})
test('M17 no proposition rejected',{z<-st;z$proposition_id<-'';reject(i6_compute('M17',z))})
emb<-kind(list(passages=mat(8),statement_id=rep(paste0('s',1:4),each=2),country=rep(c('AAA','BBB'),each=4),model_sha256=paste(rep('a',64),collapse=''),tokenizer_id='synthetic-tokenizer'))
test('M03 cached vector pooling normalizes statements and countries',{v<-i6_compute('M03',emb)$value;stopifnot(nrow(v$statement)==4,nrow(v$country)==2,all(abs(rowSums(v$country^2)-1)<1e-8))})
ref<-kind(list(x=mat(8),references=mat(3,prefix='topic'),representation_id='v1',reference_representation_id='v1'))
test('M04 cosine matches direct dot products',{v<-i6_compute('M04',ref)$value;stopifnot(max(abs(v$cosine-i6_unit(ref$x)%*%t(i6_unit(ref$references))))<1e-12)})
test('M04 different reference basis rejected',{z<-ref;z$reference_representation_id<-'v2';reject(i6_compute('M04',z))})
x<-mat(60);x[31:60,]<-x[31:60,]+10
test('M10 UMAP finite repeatable sensitivity coordinates',{v<-i6_compute('M10',kind(list(x=x,representation_id='synthetic')))$value$coordinates;w<-i6_compute('M10',kind(list(x=x,representation_id='synthetic')))$value$coordinates;stopifnot(identical(dim(v),c(60L,2L)),all(is.finite(v)),isTRUE(all.equal(v,w)))})
test('M10 archived model survives save/reload and transforms',{v<-i6_compute('M10',kind(list(x=x,representation_id='synthetic')))$value;v<-unserialize(serialize(v,NULL,version=2));z<-i6_umap_transform(v,x[1:4,,drop=FALSE]);stopifnot(identical(dim(z),c(4L,2L)),all(is.finite(z)))})
test('M21 density clusters preserve the full roster',{v<-i6_compute('M21',kind(list(x=x)))$value;stopifnot(length(v$cluster)==60,length(unique(v$cluster[v$cluster>0]))==2)})
test('Resource limit enforced',{z<-matrix(0,5001,2);rownames(z)<-seq_len(5001);reject(i6_compute('M21',kind(list(x=z))))})
a<-i6_unit(mat(10));meta<-list(country=rownames(a),genre=rep('general_debate',10),issue=rep('fictional-issue',10),language=rep('en',10));hist<-kind(list(before=a,after=a,before_representation='v1',after_representation='v1',before_meta=meta,after_meta=meta,before_time=rep(1,10),after_time=rep(2,10)))
test('M22 identical comparable observations have zero distance',stopifnot(max(i6_compute('M22',hist)$value$chord_distance)<1e-12))
test('M22 genre mismatch rejected',{z<-hist;z$after_meta$genre[1]<-'security_council';reject(i6_compute('M22',z))})
test('M22 absent new observation rejected',{z<-hist;z$after_time<-z$before_time;reject(i6_compute('M22',z))})
an<-kind(list(train_x=mat(200),score_x=mat(30,prefix='new'),train_time=1:200,score_time=1001:1030));an$score_x[30,]<-30
test('M23 historical-only isolation scores flag synthetic extreme',{v<-i6_compute('M23',an)$value$score;stopifnot(all(is.finite(v)),v[30]>median(v))})
test('M23 future history rejected',{z<-an;z$train_time[1]<-5000;reject(i6_compute('M23',z))})
cp<-kind(list(y=c(rnorm(50,0,.3),rnorm(50,5,.3)),time=seq(1,1000,length.out=100),index='observation',dependence='independent_gaussian'))
test('M24 recovers known synthetic mean break',stopifnot(any(abs(i6_compute('M24',cp)$value$change_after_observation-50)<=1)))
test('M24 invented daily indexing rejected',{z<-cp;z$index<-'imputed_daily';reject(i6_compute('M24',z))})
a<-mat(20);rotation<-matrix(c(0,1,-1,0),2);b<-a%*%rotation+3;dimnames(b)<-dimnames(a);pr<-kind(list(before=a,after=b,anchors=rownames(a)[1:15],representation='map-v1',after_representation='map-v1'))
test('M25 removes known rotation and translation',stopifnot(i6_compute('M25',pr)$value$anchor_rmse<1e-10))
test('M25 missing anchors rejected',{z<-pr;z$anchors<-c('missing','r1','r2');reject(i6_compute('M25',z))})
co<-kind(list(before=setNames(c(1,1,2,2,3),letters[1:5]),after=setNames(c(8,9,7,7,7),letters[2:6])))
test('M27 retains arrivals departures splits and merges',{v<-i6_compute('M27',co)$value;stopifnot(identical(v$arrived,'f'),identical(v$departed,'a'),length(v$shared)==4,length(v$splits)>0)})
test('M27 zero-overlap correspondence is unmatched',{z<-kind(list(before=setNames(1:3,letters[1:3]),after=setNames(rep(9,3),letters[1:3])));v<-i6_compute('M27',z)$value;stopifnot(sum(is.na(v$matched$after))==2)})
hz<-kind(list(x=mat(300),country=paste0('unit',1:300),start=rep(10,300),stop=rep(11,300),exposure_available=rep(1,300),censor_reason=rep('observed interval, no event',300)));hz$y<-rbinom(300,1,1-exp(-exp(-1+.5*hz$x[,1])))
test('M39 finite associational hazard estimates',stopifnot(all(is.finite(i6_compute('M39',hz)$value$coefficients))))
test('M39 future exposure rejected',{z<-hz;z$exposure_available[1]<-10;reject(i6_compute('M39',z))})
test('M39 risk after first event rejected',{z<-hz;z$country[1:2]<-'same';z$y[1:2]<-c(1,0);z$start[2]<-11;z$stop[2]<-12;reject(i6_compute('M39',z))})
n<-70;w<-matrix(0,n,n);for(i in 1:n)w[i,c(if(i==1)n else i-1,if(i==n)1 else i+1)]<-.5;dimnames(w)<-list(paste0('g',1:n),paste0('g',1:n));xx<-mat(n,1,'g');yy<-solve(diag(n)-.35*w,.2+.8*xx[,1]+rnorm(n,0,.3));sar<-kind(list(w=w,x=xx,y=yy,network_available=1,outcome_time=2))
test('M40 network-lag fit recovers synthetic association',stopifnot(abs(i6_compute('M40',sar)$value$rho-.35)<.3))
test('M40 contemporaneous graph rejected',{z<-sar;z$network_available<-2;reject(i6_compute('M40',z))})
rx<-mat(400,1);event<-rep(1:100,each=4);chosen<-numeric(400);for(e in 1:100){ix<-which(event==e);chosen[sample(ix,1,prob=exp(.8*rx[ix,1]))]<-1}
re<-kind(list(x=rx,chosen=chosen,event=event,sender=rep('AAA',400),receiver=rep(c('BBB','CCC','DDD','EEE'),100),covariate_available=rep(0,400),event_time=rep(1:100,each=4)))
test('M41 conditional event model recovers known choice association',stopifnot(abs(i6_compute('M41',re)$value$coefficients[1]-.8)<.4))
test('M41 duplicate dyads rejected',{z<-re;z$receiver[2]<-z$receiver[1];reject(i6_compute('M41',z))})
test('M41 two realized events in one risk set rejected',{z<-re;z$chosen[1:4]<-c(1,1,0,0);reject(i6_compute('M41',z))})
test('M41 inconsistent times in one risk set rejected',{z<-re;z$event_time[1]<-2;reject(i6_compute('M41',z))})
result<-do.call(rbind,records);out<-Sys.getenv('I6_TEST_REPORT',tempfile(fileext='.csv'));write.csv(result,out,row.names=FALSE);cat(nrow(result),'checks;',sum(!result$passed),'failures\n');if(any(!result$passed))quit(status=1)
