'use strict';
/** Self-contained, offline and source-bound adjudication interface. The user makes actual human choices. */
const fs=require('node:fs');const crypto=require('node:crypto');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(packet,assistantReview){
 if(packet?.schema!=='un.quick-reader-adjudication-benchmark.v1'||assistantReview?.case_binding_sha256!==packet.case_binding_sha256)throw Error('Unbound private benchmark view');
 const data=JSON.stringify({packet,assistantReview}).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/\u2028/g,'\\u2028');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none';"><title>Development quick-reader adjudication benchmark</title><style>
:root{color-scheme:light;--ink:#18293c;--blue:#16486d;--muted:#5c6d7e;--line:#d4dce3;--gold:#9b7950;--paper:#fff;--soft:#f4f7f9}*{box-sizing:border-box}
body{margin:0;background:var(--soft);color:var(--ink);font:15px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif}main{max-width:1100px;margin:auto;padding:28px 20px 70px}
h1{font-family:Georgia,serif;font-size:clamp(24px,3vw,34px);font-weight:600;margin:0 0 10px}h2{font-size:19px;line-height:1.35;margin:12px 0;overflow-wrap:anywhere}p{margin:8px 0 15px}small,.sub{color:var(--muted)}
header{border-bottom:3px solid var(--gold);padding-bottom:12px;margin-bottom:20px}.panel{background:var(--paper);border:1px solid var(--line);border-radius:8px;padding:18px 20px;margin:15px 0;box-shadow:0 2px 14px rgba(14,37,61,.035)}
.toolbar{display:flex;flex-wrap:wrap;align-items:end;gap:12px}.toolbar>label{flex:1;min-width:170px}.toolbar input,.toolbar select,.answer select,.answer textarea{display:block;width:100%;padding:9px 11px;border:1px solid #bac9d4;border-radius:5px;background:white;color:var(--ink);font:inherit}
button{border-radius:5px;padding:9px 14px;border:1px solid var(--blue);color:var(--blue);background:white;cursor:pointer;font:inherit;font-weight:600}button.primary{background:var(--blue);color:white}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #b58347;outline-offset:2px}
.badge{font-size:12px;background:#edf2f5;color:var(--blue);border-radius:3px;padding:4px 7px;margin-right:6px;display:inline-block;font-weight:650}
pre{white-space:pre-wrap;word-break:break-word;background:var(--soft);border-left:3px solid var(--gold);padding:12px;border-radius:0 4px 4px 0;font:14px/1.6 system-ui,sans-serif}
.twocol{display:grid;grid-template-columns:1fr 1fr;gap:15px}.answer label{display:block;margin-top:12px;font-size:13px;font-weight:600;color:var(--blue)}.answer textarea{min-height:80px}
a{color:var(--blue)}.warn{border-left:4px solid #be8a43;padding-left:13px}.nav{display:flex;justify-content:space-between;gap:15px;align-items:center;margin:14px 0}.nav>*{flex:1}.nav span{text-align:center}
@media(max-width:720px){main{padding:18px 12px 55px}.twocol{display:block}.panel{padding:15px}.toolbar{display:block}.toolbar>*,.toolbar button{margin:6px 0;width:100%}.nav{flex-wrap:wrap}.nav span{order:-1;flex-basis:100%}}
</style></head><body><main><header><div class="sub">UN TRANSCRIPT AGENT • PRIVATE DEVELOPMENT QA</div><h1>Quick-reader adjudication benchmark</h1><p>13 additional development meetings • 83 review items • Original excerpts linked to saved source hashes</p></header>
<div class="panel warn"><strong>Not human confirmed.</strong> The assistant's provisional findings are shown separately for reference. No answer field starts confirmed. Review original source context before assigning your own label. No external AI, network calls, automatic publication, or holdout transcript access.</div>
<div class="panel toolbar"><label>Reviewer name<input id="reviewer" placeholder="Name for future adjudication"></label><label>Review type<select id="kind"><option value="all">All cases</option><option value="position">Attribution + stance</option><option value="abstention">Abstentions</option><option value="context">Context coverage</option></select></label><button id="download" class="primary">Export my decisions (.json)</button><label>Resume my JSON<input type="file" id="import" accept=".json,application/json"></label></div>
<div class="panel"><div id="progress" aria-live="polite"></div><div class="nav"><button id="previous">← Previous</button><span id="counter"></span><button id="next">Next →</button></div><div id="case"></div></div>
<div class="panel"><h2>Interpretation</h2><p>Attribution precision, stance precision, specific-context coverage, and abstention correctness use separate populations and denominators. Unknown and unreviewed labels are excluded, not counted as successes. This is a purposive development benchmark, not representative accuracy and not permission to open reserved material.</p></div>
<script>const DATA=${data};
const packet=DATA.packet, suggestions=new Map(DATA.assistantReview.choices.map(x=>[x.id,x]));let list=packet.cases.slice(),index=0;const answers=new Map();
const $=id=>document.getElementById(id);const create=(tag,text,parent,cls)=>{const e=document.createElement(tag);if(text!==undefined&&text!==null)e.textContent=String(text);if(cls)e.className=cls;if(parent)parent.appendChild(e);return e};
const selectors={position:{attribution:['individual_country','collective_or_non_country','uncertain'],stance:['supported_expression','unsupported_or_wrong_object','uncertain']},abstention:{abstention:['appropriate_withhold','possible_missed_expression','uncertain']},context:{context:['covered','missed','uncertain']}};
function currentChoices(){const a=[...answers.values()];return {schema:'un.quick-reader-adjudication-choices.v1',case_binding_sha256:packet.case_binding_sha256,reviewer_type:'owner_human',owner_confirmation:true,reviewer_name:$('reviewer').value.trim(),reviewed_at:new Date().toISOString(),choices:a};}
function update(){const n=[...answers.keys()].length;$('progress').textContent=n+' of '+packet.cases.length+' cases labeled. These are draft decisions; only the downloaded JSON is durable.';}
function view(){list=packet.cases.filter(x=>$('kind').value==='all'||x.kind===$('kind').value);index=Math.max(0,Math.min(index,list.length-1));$('case').replaceChildren();
 const item=list[index];$('counter').textContent=list.length?(index+1)+' / '+list.length:'0 cases';$('previous').disabled=index===0;$('next').disabled=index>=list.length-1;
 if(!item)return;const root=$('case');create('h2',item.kind.toUpperCase()+' · '+item.id,root);
 const met=create('div',null,root);for(const label of [item.meeting_id,item.recorded_country||item.anchor_label||'',item.issue_id||'',item.current_classification?'Currently shown':'Currently withheld'])if(label)create('span',label,met,'badge');
 const source=create('p',null,root);source.appendChild(document.createTextNode('Source segment: '+item.source_id+' · SHA256 '+item.source_sha256.slice(0,16)+'… · '));
 if(typeof item.source_url==='string'&&item.source_url.startsWith('https://transcripts.un.org/en/')){const a=create('a','Open original UN meeting',source);a.href=item.source_url;a.target='_blank';a.rel='noopener noreferrer';}
 const grid=create('div',null,root,'twocol');const left=create('section',null,grid);create('h2','Source evidence',left);create('pre',item.source_excerpt||'No excerpt',left);
 const sugg=suggestions.get(item.id);const right=create('section',null,grid);create('h2','Assistant’s provisional finding (not approved)',right);create('p',sugg?Object.entries(sugg.labels).map(([k,v])=>k+': '+v).join(' · '):'No provisional assessment',right);create('p',sugg?.note||'No note',right);
 const answer=create('div',null,root,'answer');create('h2','Your adjudication',answer);const saved=answers.get(item.id);
 const values={};for(const [task,choices] of Object.entries(selectors[item.kind])){let field=create('label',task.replace(/_/g,' '),answer);const select=create('select',null,field);const empty=create('option','— Not reviewed —',select);empty.value='';for(const choice of choices){const option=create('option',choice.replace(/_/g,' '),select);option.value=choice}select.value=saved?.labels?.[task]||'';select.addEventListener('change',save);values[task]=select;}
 const noteLabel=create('label','Reasoning / context checked',answer),note=create('textarea',null,noteLabel);note.placeholder='Record the specific proposition, country/group capacity, and missing context';note.value=saved?.note||'';note.addEventListener('input',save);
 function save(){let labels={};let all=true;for(const [key,control] of Object.entries(values)){if(!control.value)all=false;labels[key]=control.value;}if(all&&note.value.trim().length>=8){answers.set(item.id,{id:item.id,source_id:item.source_id,source_sha256:item.source_sha256,labels,note:note.value.trim()});}else answers.delete(item.id);update()}
 update();}
$('kind').addEventListener('change',()=>{index=0;view()});$('previous').addEventListener('click',()=>{index--;view()});$('next').addEventListener('click',()=>{index++;view()});
$('download').addEventListener('click',()=>{if($('reviewer').value.trim().length<2){alert('Enter the reviewer name before exporting.');return;}const data=JSON.stringify(currentChoices(),null,2);const blob=new Blob([data],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='quick-reader-adjudication-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(url)});
$('import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const x=JSON.parse(await file.text());if(x.schema!=='un.quick-reader-adjudication-choices.v1'||x.case_binding_sha256!==packet.case_binding_sha256||!Array.isArray(x.choices))throw Error('Review file belongs to another source packet');const ids=new Set(packet.cases.map(c=>c.id));const seen=new Set();const next=new Map();for(const c of x.choices){const expected=packet.cases.find(item=>item.id===c.id);if(!ids.has(c.id)||seen.has(c.id)||c.source_sha256!==expected.source_sha256||c.source_id!==expected.source_id)throw Error('Unknown/duplicate/mismatched source decision');seen.add(c.id);next.set(c.id,c);}answers.clear();for(const [key,value] of next)answers.set(key,value);$('reviewer').value=x.reviewer_name||'';view();}catch(e){alert('Could not import: '+e.message)}finally{event.target.value=''}});
view();</script></main></body></html>`;
}
if(require.main===module){const [bench,review,out]=process.argv.slice(2);if(!bench||!review||!out||fs.existsSync(out))throw Error('Usage: render_adjudication_view.cjs BENCHMARK REVIEW NEW_HTML');const html=render(JSON.parse(fs.readFileSync(bench)),JSON.parse(fs.readFileSync(review)));fs.writeFileSync(out,html);console.log(JSON.stringify({schema:'un.adjudication-offline-view.v1',bytes:Buffer.byteLength(html),external_requests:0}));}
module.exports={render};
