#!/usr/bin/env Rscript
# Synthetic engineering tests. None of the fixture prose or dates is production evidence.
self<-sub("^--file=","",commandArgs()[grepl("^--file=",commandArgs())][1])
root<-normalizePath(file.path(dirname(self),".."),winslash="/",mustWork=TRUE);setwd(root)
if(file.exists("config/library_path.txt")){lib<-readLines("config/library_path.txt",warn=FALSE)[1];if(dir.exists(lib)).libPaths(c(lib,.libPaths()))}
options(unbrief.minimal="--minimal=true"%in%commandArgs(trailingOnly=TRUE))
for(f in list.files("R",pattern="^[0-9].*\\.R$",full.names=TRUE)){parse(f,encoding="UTF-8");source(f)}
cat("Parsed successfully: D1-I2 native-R modules.\n")
results<-list()
test<-function(name,expr){e<-tryCatch({force(expr);NULL},error=function(e)conditionMessage(e));results[[length(results)+1L]]<<-list(test=name,passed=is.null(e),error=e);cat(if(is.null(e))"PASS" else "FAIL",name,if(!is.null(e))paste0(": ",e) else "","\n")}
throws<-function(expr){stopifnot(isTRUE(tryCatch({force(expr);FALSE},error=function(e)TRUE)))}
tmp_rel<-paste0("validation/d1_fixture_",Sys.getpid());tmp<-file.path(root,tmp_rel);dir.create(tmp,recursive=TRUE)
cfg<-load_config("config/config.example.json");cfg$analysis_mode<-"extractive";cfg$analytics$history_dir<-paste0(tmp_rel,"/history");cfg$analytics$method_cache_dir<-paste0(tmp_rel,"/method_cache");cfg$analytics$feature_reference_dir<-paste0(tmp_rel,"/features");cfg$analytics$projection_reference_dir<-paste0(tmp_rel,"/projections")
book<-json_read("config/issue_codebook.json");countries<-load_registry("config/countries.csv");reg<-read_d1_registry(root)
fixture_text<-"Engineering fixture only. We request transparent governance of artificial intelligence and cooperation on AI safety. We discuss Iran in a diplomatic context and access to health services. We call for financing of adaptation and development programs."
make_obs<-function(key="statement-1",text=fixture_text,date="2026-09-20",acquired="2026-09-21T01:00:00Z",country="AND") {
  c<-resolve_country(countries,country)
  s<-normalized_speech(list(iso3=country,country=c$country,speaker="Synthetic fixture speaker",title="Test delegate",date=date,
      text=text,source_type="engineering_fixture",source_file="",observation_key=key,genre="synthetic_test_genre"),countries)
  observation_enrich(s,"local",acquired)
}
make_cp<-function(obs,source="local") {
  grouped<-group_countries(obs)$speeches;grouped<-order_country_readouts(grouped,cfg)
  aa<-setNames(lapply(grouped,function(s)extractive_analysis(s,book)),vapply(grouped,function(s)s$iso3,character(1)))
  list(brief=list(date=if(length(obs))obs[[1]]$date else "2026-09-20",source=source,analysis_mode="extractive",
                 collection=list(errors=list(),excluded=list(),coverage_note="Synthetic engineering fixture; not an observed UN speech.")),
       observations=obs,speeches=grouped,analyses=aa,config=cfg,codebook=book)
}
new_run<-function(name){p<-file.path(tmp,name);dir.create(p,recursive=TRUE);p}
obs1<-make_obs();cp1<-make_cp(list(obs1));r1<-new_run("ingest_1")
snap1<-history_ingest(root,r1,cfg,cp1$observations,cp1,clock=function()"2026-09-21T02:00:00Z")
store<-file.path(root,cfg$analytics$history_dir)
query<-function(t="2026-09-30T00:00:00Z",date="2026-09-30",latest=TRUE)history_index(store,t,date,latest)
test("Exact 42-method registry and 133 required gates",stopifnot(nrow(reg)==42L,sum(lengths(strsplit(reg$required_gates,"|",fixed=TRUE)))==133L))
test("Ready-packet config toggle rejected",{bad<-cfg;bad$analytics$allow_ready_packets<-TRUE;throws(validate_analytics_config(bad))})
test("Automatic model promotion toggle rejected",{bad<-cfg;bad$analytics$allow_automatic_promotion<-TRUE;throws(validate_analytics_config(bad))})
test("Unsafe historical directory rejected",{bad<-cfg;bad$analytics$history_dir<-"../outside";throws(validate_analytics_config(bad))})
test("Unknown storage backend rejected",{bad<-cfg;bad$analytics$history_backend<-"invented";throws(validate_analytics_config(bad))})
test("Old config cannot silently enable D1",{bad<-cfg;bad$analytics<-NULL;throws(validate_analytics_config(bad))})
test("Strict UTC timestamp rejects invalid calendar date",throws(parse_utc("2026-02-30T00:00:00Z")))
test("UTC timestamp without timezone rejected",throws(parse_utc("2026-09-20T01:00:00")))
test("Fractional UTC timestamps remain ordered",stopifnot(parse_utc("2026-09-20T01:00:00.123456Z")>parse_utc("2026-09-20T01:00:00.123455Z")))
test("One source statement is stored with its event date",{x<-query();stopifnot(nrow(x)==1,x$event_date=="2026-09-20",x$first_seen_at=="2026-09-21T01:00:00Z")})
test("No backdating availability to event time",stopifnot(nrow(query("2026-09-20T23:59:59Z"))==0))
test("Known source before store commit excluded from historical query",stopifnot(nrow(query("2026-09-21T01:30:00Z"))==0))
test("Event-date cutoff excludes future event despite acquisition",stopifnot(nrow(query(date="2026-09-19"))==0))
test("Date-only source does not invent event seconds",{o<-observation_object(obs1);stopifnot(o$metadata$event_time_precision=="date",o$metadata$event_time==obs1$date)})
test("Exact passage character offsets reconstruct source text",{o<-observation_object(obs1);for(p in o$passages)stopifnot(p$offsets_exact,substring(o$text,p$start_char,p$end_char)==p$text)})
test("Near-duplicate discovery not falsely claimed",{o<-observation_object(obs1);stopifnot(all(vapply(o$passages,function(p)p$near_duplicate_status=="not_assessed",logical(1))))})
test("Synthetic observations are explicitly excluded from historical modeling",stopifnot(query()$eligibility_class=="engineering_fixture"))
test("Automatic labels are never gold",{ll<-history_labels(store,"2026-09-30T00:00:00Z","2026-09-30");stopifnot(length(ll)==13L,all(vapply(ll,function(x)identical(x$is_gold,FALSE)&&identical(x$training_eligible,FALSE),logical(1))))})
test("No future labels in as-of view",stopifnot(length(history_labels(store,"2026-09-21T01:59:59Z","2026-09-30"))==0))
test("Human gold selection cannot pick rule labels",stopifnot(length(history_labels(store,"2026-09-30T00:00:00Z","2026-09-30",origin="human_adjudicated"))==0))
obs2<-make_obs(text=paste(fixture_text,"This correction adds an explicit discussion of Cuba."),acquired="2026-09-22T01:00:00Z")
cp2<-make_cp(list(obs2));r2<-new_run("ingest_2");snap2<-history_ingest(root,r2,cfg,cp2$observations,cp2,clock=function()"2026-09-22T02:00:00Z")
test("Revised transcript retains stable observation identity",stopifnot(obs1$observation_id==obs2$observation_id,observation_object(obs1)$observation_version_id!=observation_object(obs2)$observation_version_id))
test("Historical view before correction sees original text version",stopifnot(query("2026-09-21T23:00:00Z")$text_sha256==obs1$text_sha256))
test("Historical view after correction sees corrected text version",stopifnot(query("2026-09-22T03:00:00Z")$text_sha256==obs2$text_sha256))
test("Old and revised objects are both retained",stopifnot(nrow(query(latest=FALSE))==2L))
repeat_obs<-obs2;repeat_obs$acquired_at<-"2026-09-23T01:00:00Z";repeat_cp<-make_cp(list(repeat_obs));r3<-new_run("ingest_3")
history_ingest(root,r3,cfg,repeat_cp$observations,repeat_cp,clock=function()"2026-09-23T02:00:00Z")
test("Repeated acquisition does not duplicate versions",stopifnot(nrow(query(latest=FALSE))==2L,nrow(query())==1L))
test("Repeated acquisition preserves original version availability",stopifnot(query()$first_seen_at=="2026-09-22T01:00:00Z"))
revert<-obs1;revert$acquired_at<-"2026-09-24T01:00:00Z";revert_cp<-make_cp(list(revert));r4<-new_run("ingest_4")
history_ingest(root,r4,cfg,revert_cp$observations,revert_cp,clock=function()"2026-09-24T02:00:00Z")
test("Explicit later reversion to original bytes is represented",stopifnot(query()$text_sha256==obs1$text_sha256,query()$first_seen_at==obs1$acquired_at,nrow(query(latest=FALSE))==2L))
late<-make_obs(key="late",date="2026-09-01",acquired="2026-09-25T01:00:00Z");late_cp<-make_cp(list(late));rl<-new_run("late_backfill")
history_ingest(root,rl,cfg,late_cp$observations,late_cp,clock=function()"2026-09-25T02:00:00Z")
test("Late backfill cannot leak into earlier knowledge cutoff",stopifnot(!late$observation_id%in%query("2026-09-24T23:00:00Z")$observation_id,late$observation_id%in%query()$observation_id))
test("Commit chain verifies immutable objects",stopifnot(history_verify(store)$passed,history_verify(store)$commits==5L))
test("Clock regression rejected",throws(history_ingest(root,new_run("bad_clock"),cfg,cp1$observations,cp1,clock=function()"2026-09-21T02:00:00Z")))
test("Future source acquisition rejected",{future<-obs1;future$acquired_at<-"2027-01-01T00:00:00Z";throws(history_ingest(root,new_run("future_source"),cfg,list(future),cp1,clock=function()"2026-09-25T03:00:00Z"))})
test("Text hash mismatch rejected at history boundary",{bad<-obs1;bad$text<-paste(bad$text,"unhashed");throws(observation_object(bad))})
test("Conflicting same-collection versions are not arbitrarily ordered",throws(history_ingest(root,new_run("ambiguous"),cfg,list(obs1,obs2),cp2,clock=function()"2026-09-25T03:00:00Z")))
test("Interrupted precommit write leaves no visible commit",{before<-length(history_commits(store));throws(history_ingest(root,new_run("interrupted"),cfg,list(obs1),cp1,clock=function()"2026-09-25T03:00:00Z",fault="before_commit"));stopifnot(length(history_commits(store))==before)})
test("Staging directory never appears as committed history",{p<-file.path(store,"commits/.pending_fixture");dir.create(p);write_text(file.path(p,"partial.txt"),"not a commit");stopifnot(length(history_commits(store))==5L);unlink(p,recursive=TRUE)})
test("Concurrent history writer is blocked",{lock<-history_lock(store);throws(history_lock(store));history_unlock(lock)})
test("Different lock owner cannot release another writer",{lock<-history_lock(store);fake<-lock;fake$token<-"wrong";throws(history_unlock(fake));stopifnot(dir.exists(lock$path));history_unlock(lock)})
test("Tampered observation bytes fail verification",{ref<-query()[1,];p<-file.path(store,ref$object_path);bytes<-read_bytes(p);writeBin(c(bytes,as.raw(1)),p);throws(query());writeBin(bytes,p);stopifnot(history_verify(store)$passed)})
test("Tampered commit bytes fail chain verification",{p<-file.path(store,history_commits(store)[[1]]$commit_path,"commit.rds");bytes<-read_bytes(p);writeBin(c(bytes,as.raw(1)),p);throws(history_commits(store));writeBin(bytes,p)})
test("Missing interior commit is detected",{p<-file.path(store,history_commits(store)[[2]]$commit_path);hidden<-file.path(store,"commits/.hidden_test");stopifnot(file.rename(p,hidden));throws(history_commits(store));stopifnot(file.rename(hidden,p))})
second<-make_obs(key="statement-2",text=paste(fixture_text,"A separately identified second intervention."))
pair_cp<-make_cp(list(obs1,second));pair_run<-new_run("pair")
cfgpair<-cfg;cfgpair$analytics$history_dir<-paste0(tmp_rel,"/pair_history")
pair_snap<-history_ingest(root,pair_run,cfgpair,pair_cp$observations,pair_cp,clock=function()"2026-09-25T03:00:00Z")
test("Ungrouped statements survive one-country aggregation",stopifnot(length(pair_cp$speeches)==1L,length(pair_cp$observations)==2L,nrow(pair_snap$observations)==2L))
test("Statement-level source versions are distinct",stopifnot(length(unique(pair_snap$observations$observation_id))==2L))
test("Every country label binds both contributing statements",{labs<-history_labels(file.path(root,cfgpair$analytics$history_dir),"2026-09-30T00:00:00Z","2026-09-30");stopifnot(all(vapply(labs,function(x)length(x$observation_versions)==2L,logical(1))))})
# Actual diagnostic execution; other 30 methods remain explicitly unimplemented.
account<-run_method_accounting(root,pair_run,cfg,pair_cp,pair_snap)
test("Complete daily method ledger",stopifnot(nrow(account$ledger)==42L,sum(account$ledger$terminal_status=="executed")==1L,sum(account$ledger$terminal_status=="not_implemented")==30L))
test("Every method has all prerequisite decisions",stopifnot(nrow(account$gates)==133L))
test("Rule diagnostic is not a trained classifier",{x<-readRDS(file.path(pair_run,account$ledger$artifact_ref[1]));stopifnot(identical(x$is_fitted_model,FALSE),identical(x$publication_eligible,FALSE))})
test("Rule candidates keep exact source quotes",validate_m01(readRDS(file.path(pair_run,account$ledger$artifact_ref[1])),pair_cp,root))
test("Rule nonhits never become absent",{x<-readRDS(file.path(pair_run,account$ledger$artifact_ref[1]));stopifnot(any(vapply(x$decisions,function(d)d$state=="no_hit_unresolved",logical(1))),all(vapply(x$decisions,function(d)!d$is_absence_decision,logical(1))))})
test("Repeated identical input observations do not multiply issue decisions",{dup<-pair_cp;dup$observations<-c(dup$observations,dup$observations[1]);x<-m01_rule_candidates(dup,root);validate_m01(x,dup,root);stopifnot(length(x$decisions)==26L)})
test("M01 accounts at statement level, not only country level",{x<-readRDS(file.path(pair_run,account$ledger$artifact_ref[1]));stopifnot(length(x$decisions)==26L)})
rreuse<-new_run("reuse");acc2<-run_method_accounting(root,rreuse,cfg,pair_cp,pair_snap)
test("Unchanged diagnostic reuses exact validated cache",stopifnot(acc2$ledger$terminal_status[1]=="reused",acc2$ledger$artifact_sha256[1]==account$ledger$artifact_sha256[1],acc2$ledger$artifact_created_at[1]==account$ledger$artifact_created_at[1]))
test("Model-training absence is not disguised as a fit",stopifnot(account$ledger$fit_status[1]=="not_a_fit",all(account$ledger$fit_status[!account$ledger$method_id%in%names(d1_adapters())]=="not_implemented")))
test("Driftmap operating regime is explicitly unestablished",{g<-account$gates[account$gates$method_id=="M26"&account$gates$gate=="driftmap_supported_regime",];stopifnot(nrow(g)==1L,g$state=="unestablished",g$blocker_class=="regime")})
test("Synthetic history cannot satisfy model history gates",stopifnot(account$context$prior_nonreplay_statement_versions==0L))
# Failure and mutation cases must not erase unrelated method accounting.
failcfg<-cfg;failcfg$analytics$method_cache_dir<-paste0(tmp_rel,"/fail_cache")
bad_adapter<-d1_adapters();bad_adapter$M01$execute<-function(...)stop("Injected engineering adapter failure")
rfail<-new_run("adapter_failure");af<-run_method_accounting(root,rfail,failcfg,pair_cp,pair_snap,bad_adapter)
test("Failed adapter still leaves all 42 rows",stopifnot(nrow(af$ledger)==42L,af$ledger$terminal_status[1]=="failed",all(af$ledger$terminal_status[!af$ledger$method_id%in%names(d1_adapters())]=="not_implemented")))
test("Failed adapter never claims an output artifact",stopifnot(af$ledger$artifact_ref[1]=="",file.exists(file.path(rfail,af$ledger$error_log[1]))))
missing<-d1_adapters();missing$M01$required_packages<-"D1nonexistentPackageEngineeringFixture"
am<-run_method_accounting(root,new_run("dependency_failure"),failcfg,pair_cp,pair_snap,missing)
test("Missing actual dependency is explicit",stopifnot(am$ledger$terminal_status[1]=="blocked_dependency"))
cachefile<-list.files(file.path(root,cfg$analytics$method_cache_dir,"M01"),pattern="\\.rds$",full.names=TRUE)[1];bytes<-read_bytes(cachefile);writeBin(c(bytes,as.raw(1)),cachefile)
ac<-run_method_accounting(root,new_run("cache_corruption"),cfg,pair_cp,pair_snap);writeBin(bytes,cachefile)
test("Corrupt cache fails instead of silently recomputing",stopifnot(ac$ledger$terminal_status[1]=="failed",nrow(ac$ledger)==42L))
futurecache<-readRDS(cachefile);futurecache$created_at<-"2099-01-01T00:00:00Z";oldhash<-read_bytes(paste0(cachefile,".sha256"));writeBin(serialize(futurecache,NULL,version=3),cachefile);write_text(paste0(cachefile,".sha256"),sha_file(cachefile))
afuture<-run_method_accounting(root,new_run("future_cache"),cfg,pair_cp,pair_snap);writeBin(bytes,cachefile);writeBin(oldhash,paste0(cachefile,".sha256"))
test("Future-dated cache artifact rejected",stopifnot(afuture$ledger$terminal_status[1]=="failed"))
test("Missing method row rejected",throws(validate_method_ledger(account$ledger[-1,],account$gates,reg,pair_run,account$as_of_cutoff)))
test("Duplicate method row rejected",{bad<-account$ledger;bad$method_id[2]<-bad$method_id[1];throws(validate_method_ledger(bad,account$gates,reg,pair_run,account$as_of_cutoff))})
test("Unknown terminal status rejected",{bad<-account$ledger;bad$terminal_status[2]<-"looks_good";throws(validate_method_ledger(bad,account$gates,reg,pair_run,account$as_of_cutoff))})
test("Empty non-delivery reason rejected",{bad<-account$ledger;bad$reason[2]<-"";throws(validate_method_ledger(bad,account$gates,reg,pair_run,account$as_of_cutoff))})
test("Missing required gate rejected",throws(validate_method_ledger(account$ledger,account$gates[-1,],reg,pair_run,account$as_of_cutoff)))
test("Pass flag conflicting with gate evidence rejected",{bad<-account$gates;at<-which(bad$gate=="gold_issue_labels")[1];bad$state[at]<-"pass";throws(validate_method_ledger(account$ledger,bad,reg,pair_run,account$as_of_cutoff))})
test("Unimplemented method cannot claim execution",{bad<-account$ledger;bad$terminal_status[3]<-"executed";throws(validate_method_ledger(bad,account$gates,reg,pair_run,account$as_of_cutoff))})
test("Unexecuted row cannot carry stale artifact",{bad<-account$ledger;bad$artifact_ref[3]<-bad$artifact_ref[1];throws(validate_method_ledger(bad,account$gates,reg,pair_run,account$as_of_cutoff))})
packets<-d1_build_packets(pair_cp,account,pair_snap,pair_run)
pair_cp$analytics<-list(design="D1",implementation="I2",as_of_cutoff=account$as_of_cutoff,report_packets=packets,inline_images=list())
test("Internal sentence range removed from reader-facing notes",stopifnot(reader_source_note("The introduction repeats at S106–S107.")=="The introduction repeats in the source text."))
test("Original source-note substance preserved",stopifnot(reader_source_note("S059 gives inconsistent poverty figures.")=="The source text gives inconsistent poverty figures."))
test("Exactly five unavailable packets in fixed order",stopifnot(identical(unname(vapply(packets,function(x)x$slot_id,character(1))),D1_SLOT_IDS),all(vapply(packets,function(x)x$state%in%c("not_ready","withheld"),logical(1)))))
test("Sixth packet rejected",throws(d1_validate_packets(c(packets,packets[1]),pair_run,pair_cp,account$as_of_cutoff)))
test("Missing packet rejected",throws(d1_validate_packets(packets[-1],pair_run,pair_cp,account$as_of_cutoff)))
test("Reordered packets rejected",throws(d1_validate_packets(rev(packets),pair_run,pair_cp,account$as_of_cutoff)))
test("Stale numerical payload on unavailable output rejected",{bad<-packets;bad[[1]]$payload<-list(n_present=99);throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
test("Boolean flags cannot promote a fabricated ready packet",{bad<-packets;bad[[1]]$state<-"ready";bad[[1]]$model_id<-"imaginary_released_model";bad[[1]]$release_status<-"released";bad[[1]]$quality_checks<-as.list(setNames(rep(TRUE,8),D1_REQUIRED_CHECKS));throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
test("Forecasts cannot enter an observed-output slot",{bad<-packets;bad[[2]]$is_forecast<-TRUE;throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
test("Misleading slot title rejected",{bad<-packets;bad[[3]]$title<-"Political alignment score";throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
test("Source snapshot substitution rejected",{bad<-packets;bad[[4]]$source_snapshot_id<-paste(rep("0",64),collapse="");throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
test("Future packet cutoff rejected",{bad<-packets;bad[[4]]$as_of_cutoff<-"2099-01-01T00:00:00Z";throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
test("Unsafe artifact reference rejected",{bad<-packets;bad[[1]]$evidence_refs[[1]]$path<-"../escape";throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
test("Publication check hash must match actual evidence",{bad<-packets;bad[[1]]$quality_checks$source$evidence_sha256<-paste(rep("0",64),collapse="");throws(d1_validate_packets(bad,pair_run,pair_cp,account$as_of_cutoff))})
render<-d1_render_packets(pair_cp,pair_run,cfg);h<-paste(render$html,collapse="\n");plain<-paste(render$plain,collapse="\n")
test("Five analytical HTML sections, no extra charts",stopifnot(count_pattern('class="analytics-slot"',h)==5L,length(render$images)==0L,!grepl("<img",h,fixed=TRUE)))
test("Permanent topics ordered Iran Cuba Ukraine AI",{pos<-vapply(FIXED_ISSUE_LABELS,function(x)regexpr(paste0(">",x,"</td>"),h,fixed=TRUE)[1],numeric(1));stopifnot(all(pos>0),all(diff(pos)>0))})
test("Unavailable topic table does not fabricate zero prevalence",stopifnot(!grepl("0 / 1|>0%<|n_present",h),grepl("Unassessed is not absent",h,fixed=TRUE)))
test("Every unavailable-state reason is identical in HTML and plaintext",for(p in packets)stopifnot(grepl(html_escape(p$reason),h,fixed=TRUE),grepl(p$reason,plain,fixed=TRUE)))
test("Unreleased images cannot be inserted through manifest",{bad<-pair_cp;bad$analytics$inline_images<-list("injected.png");throws(d1_render_packets(bad,pair_run,cfg))})
# Integration tests use actual pipeline functions but no network or model calls.
input<-file.path(tmp,"local_fixture.json");json_write(input,list(obs1,second))
endcfg<-cfg;endcfg$analytics$history_dir<-paste0(tmp_rel,"/e2e_history");endcfg$analytics$method_cache_dir<-paste0(tmp_rel,"/e2e_cache")
e2e<-new_run("e2e_failed_audit_charts");dir.create(file.path(e2e,"logs"));dir.create(file.path(e2e,"figures"))
prepare_run(root,e2e,endcfg,"local","2026-09-20",input)
prepare_analytics(root,e2e,endcfg);run_audit_figures(root,e2e,runner=function(...)1L)
build_email(root,e2e,endcfg);qa<-validate_output(root,e2e,endcfg)
test("Failed audit-only charts do not block five-output email",stopifnot(qa$passed,qa$inline_images==1L,qa$methods_accounted==42L,grepl("not available",qa$frequency_reconciliation,fixed=TRUE)))
test("Country summaries survive withheld analytical outputs",stopifnot(qa$country_sections==1L,qa$ungrouped_statements_preserved==2L))
test("Email explicitly excludes all three legacy figure filenames",{x<-flatten_mime(parse_mime(read_bytes(file.path(e2e,"daily_briefing.eml"))));body<-rawToChar(Filter(function(p)p$type=="text/html",x)[[1]]$bytes);for(f in FIGURE_FILES)stopifnot(!grepl(f,body,fixed=TRUE))})
test("Frozen checkpoint renders byte-identical email",{before<-sha_file(file.path(e2e,"daily_briefing.eml"));build_email(root,e2e,endcfg);stopifnot(identical(before,sha_file(file.path(e2e,"daily_briefing.eml"))))})
empty_input<-file.path(tmp,"empty.json");json_write(empty_input,list());empty<-new_run("e2e_empty");dir.create(file.path(empty,"logs"));dir.create(file.path(empty,"figures"))
prepare_run(root,empty,endcfg,"local","2026-09-20",empty_input);prepare_analytics(root,empty,endcfg);run_audit_figures(root,empty,runner=function(...)1L);build_email(root,empty,endcfg);qe<-validate_output(root,empty,endcfg)
test("Empty source day retains exactly five unavailable outputs",stopifnot(qe$passed,qe$country_sections==0L,qe$inline_images==1L,qe$methods_accounted==42L))
test("No-source M01 correctly records blocked_data",{l<-read.csv(file.path(empty,"audit/analytics/method_ledger.csv"));stopifnot(l$terminal_status[1]=="blocked_data")})
test("Empty watchlist says no qualifying text, not zero prevalence",{hh<-read_text(file.path(empty,"daily_briefing.html"));stopifnot(count_pattern("No qualifying country text</td>",hh)==4L,!grepl("0 / 0",hh,fixed=TRUE))})
prep_fail<-new_run("failed_preparation");account_preparation_failure(root,prep_fail,cfg,"Injected missing source fixture")
test("Preparation failure still accounts for all 42 methods",{l<-read.csv(file.path(prep_fail,"audit/analytics/method_ledger.csv"));stopifnot(nrow(l)==42L,all(l$terminal_status=="blocked_data"),!file.exists(file.path(prep_fail,"daily_briefing.eml")))})
summary<-list(passed=all(vapply(results,function(r)r$passed,logical(1))),tests=length(results),failed=sum(!vapply(results,function(r)r$passed,logical(1))),R_version=R.version.string,minimal=isTRUE(getOption("unbrief.minimal")),fixture_scope="Synthetic engineering data; no live requests, model training, native Outlook or Windows validation.",results=results)
json_write("validation/d1_tests.json",summary);write_text("validation/d1_tests_sessionInfo.txt",capture.output(sessionInfo()))
unlink(tmp,recursive=TRUE)
cat(sprintf("\n%d D1 engineering tests; %d failures.\n",summary$tests,summary$failed))
if(!summary$passed)quit(status=1)
