#!/usr/bin/env Rscript
# D1-I2 numerical, provenance, failure-path and publication-contract tests.
# All constructed prose is synthetic. A temporary mock of observed metadata tests
# the positive publication contract; it is NEVER ingested into production history.
self<-sub("^--file=","",commandArgs()[grepl("^--file=",commandArgs())][1])
root<-normalizePath(file.path(dirname(self),".."),winslash="/",mustWork=TRUE);setwd(root)
options(unbrief.minimal="--minimal=true"%in%commandArgs(trailingOnly=TRUE),unbrief.root=root)
for(f in list.files("R",pattern="^[0-9].*\\.R$",full.names=TRUE)){parse(f,encoding="UTF-8");source(f)}
results<-list();test<-function(name,expr){e<-tryCatch({force(expr);NULL},error=function(e)conditionMessage(e));results[[length(results)+1L]]<<-list(test=name,passed=is.null(e),error=e);cat(if(is.null(e))"PASS" else "FAIL",name,if(!is.null(e))paste0(": ",e) else "","\n");flush.console()}
throws<-function(expr){stopifnot(isTRUE(tryCatch({force(expr);FALSE},error=function(e)TRUE)))}
near<-function(a,b,tol=1e-9)stopifnot(isTRUE(all.equal(unname(a),unname(b),tolerance=tol,check.attributes=FALSE)))
fp<-i2_policy(root,"feature");pp<-i2_policy(root,"projection")
unit<-function(text,iso="AND",i=1L,cls="engineering_fixture",language="en",genre="synthetic_test")list(observation_id=paste0("unit-",iso,"-",i),observation_version_id=sha_text(paste(iso,i,text)),iso3=iso,country=iso,region="Europe & Eurasia",date="2026-09-20",genre=genre,language=language,translation_version="source_english",eligibility_class=cls,source_type="engineering_fixture",source_sha256=sha_text(text),text_sha256=sha_text(text),acquired_at="2026-09-21T00:00:00Z",flags=list(),source_url="",text=text)
make_feature<-function(us) {
  vocab<-i2_fit_vocabulary(us,fp);ft<-i2_transform(us,vocab,fp)
  ref<-list(schema=I2_FEATURE_SCHEMA,policy=fp,policy_hash=sha_object(fp),scope=i2_scope_key(us),environment=i2_env_signature(),units=us,source_snapshot_id=sha_text("synthetic snapshot"),source_as_of_cutoff="2026-09-21T01:00:00Z",event_cutoff="2026-09-20",frozen_at="2026-09-21T02:00:00Z",vocabulary=vocab,features=ft,reference_is_human_gold=FALSE,exact_same_day_bootstrap_is_not_a_historical_validation=TRUE)
  ref$reference_id<-sha_object(ref)
  list(schema=I2_FEATURE_SCHEMA,method_id="M02",reference=ref,reference_operation="fitted_frozen_reference",input_identity=i2_units_key(us),current_units=us,current=ft,source_snapshot_id=ref$source_snapshot_id,source_as_of_cutoff=ref$source_as_of_cutoff,event_cutoff=ref$event_cutoff,fitted_reference_id=ref$reference_id,created_at="2026-09-21T03:00:00Z",definition="Synthetic numerical test")
}
small<-list(unit("apple apple pear shared",i=1),unit("apple banana shared",iso="ARG",i=2),unit("pear banana shared",iso="BWA",i=3))
v<-i2_fit_vocabulary(small,fp);f<-make_feature(small)
test("Changing a release threshold without its frozen design revision is rejected",{home<-tempfile("i2_policy_contract_");dir.create(file.path(home,"config"),recursive=TRUE);dir.create(file.path(home,"design/D1-I2"),recursive=TRUE);file.copy(file.path(root,"config/projection_policy.json"),file.path(home,"config/projection_policy.json"));file.copy(file.path(root,"design/D1-I2/projection_policy.json"),file.path(home,"design/D1-I2/projection_policy.json"));stopifnot(identical(i2_policy(home,"projection"),pp));bad<-pp;bad$min_reference_variance_retained<-0.001;json_write(file.path(home,"config/projection_policy.json"),bad);throws(i2_policy(home,"projection"));unlink(home,recursive=TRUE)})
test("R Matrix package used for sparse features",stopifnot(inherits(f$current$statement$x,"sparseMatrix")))
test("Frozen vocabulary excludes universal boilerplate",stopifnot(identical(v$vocabulary,c("apple","banana","pear"))))
test("Document frequency is unique-document presence",stopifnot(identical(v$document_frequency,rep(2L,3))))
test("Smoothed natural-log IDF matches declared formula",near(v$idf,rep(1+log(4/3),3)))
test("Positive TF uses one plus natural-log count",{z<-as.numeric(f$current$statement$x[1,]);expected<-c(1+log(2),0,1)*v$idf;near(z,expected/sqrt(sum(expected^2)))})
test("Every nonzero statement vector has unit L2 norm",near(Matrix::rowSums(f$current$statement$x^2),rep(1,3)))
test("Every nonzero country vector has unit L2 norm",near(Matrix::rowSums(f$current$country$x^2),rep(1,3)))
test("Cosine matches independently computed dot products",near(f$current$cosine,tcrossprod(as.matrix(f$current$country$x))))
test("Cosine is symmetric and self-similarity one",{near(f$current$cosine,t(f$current$cosine));near(diag(f$current$cosine),rep(1,3))})
test("Negation is not discarded",stopifnot(all(c("no","not","nor")%in%i2_tokenize("No not nor agreement",fp))))
test("Unicode letter runs retained without transliteration",stopifnot("café"%in%i2_tokenize("CAFÉ 100 abc-def",fp),!"100"%in%i2_tokenize("CAFÉ 100 abc-def",fp)))
test("Tokenization does not mutate source text",{x<-"NO café ABC 42";i2_tokenize(x,fp);stopifnot(identical(x,"NO café ABC 42"))})
test("Exact duplicate text does not change reference IDF",near(i2_fit_vocabulary(c(small,small[1]),fp)$idf,v$idf))
test("Exact duplicate within country does not change pooled vector",{z<-i2_transform(c(small,small[1]),v,fp);near(z$country$x,f$current$country$x)})
test("Additional intervention pooling is equal-weight then L2",{u<-small;u[[2]]$iso3<-u[[1]]$iso3;z<-i2_transform(u,v,fp);want<-colMeans(as.matrix(z$statement$x[1:2,]));want<-want/sqrt(sum(want^2));near(z$country$x["AND",],want)})
test("New terms cannot grow the frozen vocabulary",{u<-unit("apple pear neverseen",i=4);z<-i2_transform(list(u),v,fp);stopifnot(identical(colnames(z$statement$x),v$vocabulary),z$statement$rows$oov_tokens==1)})
test("Daily transformation leaves frozen IDF byte-identical",{before<-sha_object(v);i2_transform(list(unit("newword newword apple")),v,fp);stopifnot(identical(before,sha_object(v)))})
test("Transform is batch invariant",{u<-unit("apple pear neverseen",i=4);a<-i2_transform(list(u),v,fp);b<-i2_transform(c(list(u),small),v,fp);near(a$statement$x[1,],b$statement$x[1,])})
test("All-OOV text remains an undefined similarity",{z<-i2_transform(list(unit("quartz quartz zephyr")),v,fp);stopifnot(!z$statement$rows$nonzero,all(is.na(z$cosine)),z$statement$rows$oov_fraction==1)})
test("Stopword-only text remains an empty vector",{z<-i2_transform(list(unit("the and of")),v,fp);stopifnot(!z$statement$rows$nonzero,is.na(z$statement$rows$oov_fraction))})
test("Single unique reference text explicitly blocked",throws(i2_fit_vocabulary(small[1],fp)))
test("Empty vocabulary explicitly blocked",throws(i2_fit_vocabulary(list(unit("the and"),unit("of then",iso="ARG")),fp)))
test("Source-character resource cap is enforced",{p<-fp;p$max_source_chars<-1;throws(i2_fit_vocabulary(small,p))})
test("Statement resource cap is enforced",{p<-fp;p$max_statements<-1;throws(i2_weight_units(small,v,p))})
test("Sparse-nonzero cap is enforced",{p<-fp;p$max_sparse_nonzero<-1;throws(i2_weight_units(small,v,p))})
test("Dense-cell cap checked before materialization",{p<-fp;p$max_dense_cells<-1;throws(i2_dense(f$current$country$x,p))})
test("Valid frozen source reference revalidates",i2_validate_reference(f$reference,fp))
test("Changed IDF rejected even with recomputed object identity",{r<-f$reference;r$vocabulary$idf[1]<-99;r$reference_id<-sha_object(r[setdiff(names(r),"reference_id")]);throws(i2_validate_reference(r,fp))})
test("Future current input rejected even though availability is excluded from lexical cache identity",{g<-f;g$current_units[[1]]$acquired_at<-"2099-01-01T00:00:00Z";throws(i2_validate_features(g))})
test("Future feature creation ordering rejected",{g<-f;g$created_at<-"2020-01-01T00:00:00Z";throws(i2_validate_features(g))})
test("Changed source text rejected",{r<-f$reference;r$units[[1]]$text<-"changed";r$reference_id<-sha_object(r[setdiff(names(r),"reference_id")]);throws(i2_validate_reference(r,fp))})
test("Future reference input rejected",{r<-f$reference;r$units[[1]]$acquired_at<-"2099-01-01T00:00:00Z";r$reference_id<-sha_object(r[setdiff(names(r),"reference_id")]);throws(i2_validate_reference(r,fp))})
test("Runtime or tokenizer drift rejected",{r<-f$reference;r$environment$PCRE<-"changed";r$reference_id<-sha_object(r[setdiff(names(r),"reference_id")]);throws(i2_validate_reference(r,fp))})
test("Reference/current provenance classes use separate namespaces",{u<-small;u[[1]]$eligibility_class<-"observed_input";stopifnot(i2_scope_key(u)$key!=i2_scope_key(small)$key)})
test("Reference/current language changes use separate namespaces",{u<-small;u[[1]]$language<-"fr";stopifnot(i2_scope_key(u)$key!=i2_scope_key(small)$key)})
test("Acquisition replay does not alter feature input identity",{u<-small;u[[1]]$acquired_at<-"2026-09-22T00:00:00Z";stopifnot(i2_units_key(u)==i2_units_key(small))})
set.seed(71);x<-matrix(rnorm(80),10,8);x<-x/sqrt(rowSums(x^2));rownames(x)<-sprintf("U%02d",1:10);colnames(x)<-paste0("term",1:8)
pca<-i2_pca_fit(x,pp,fp);d<-sqrt(i2_squared_distances(x));pcoa<-i2_pcoa_fit(d,pp)
test("Chord distance equals square root two minus two cosine",{want<-2-2*tcrossprod(x);want[]<-sqrt(pmax(0,want));diag(want)<-0;near(d,want)})
test("PCA scores match fixed-center loading multiplication",near(pca$coordinates,sweep(x,2,pca$center,"-")%*%pca$rotation))
test("PCA matches stats prcomp retained variance",near(pca$values,stats::prcomp(x,center=TRUE,scale.=FALSE)$sdev^2*9))
test("PCA loading vectors are orthonormal",near(crossprod(pca$rotation),diag(2)))
test("PCA loading signs are deterministic",stopifnot(all(i2_sign_columns(pca$rotation)==1)))
test("PCoA eigenvalues match stats cmdscale",near(pcoa$values,stats::cmdscale(as.dist(d),k=2,eig=TRUE)$eig))
test("PCoA and PCA preserve same two-dimensional distances",near(as.matrix(dist(pca$coordinates)),as.matrix(dist(pcoa$coordinates)),1e-8))
test("PCoA reference transform reconstructs fitted coordinates",near(i2_pcoa_project_distances(pcoa,d),pcoa$coordinates,1e-8))
set.seed(72);y<-matrix(rnorm(24),3,8);y<-y/sqrt(rowSums(y^2));colnames(y)<-colnames(x);rownames(y)<-paste0("new",1:3)
zp<-i2_project(pca,y,x,fp);zc<-i2_project(pcoa,y,x,fp)
test("Out-of-sample PCA equals predict(prcomp) up to signs",{m<-stats::prcomp(x,rank.=2);a<-predict(m,y);near(abs(zp),abs(a),1e-8)})
test("Out-of-sample PCoA agrees with frozen PCA via reference rotation",{q<-qr.solve(pca$coordinates,pcoa$coordinates);near(zp%*%q,zc,1e-8)})
test("PCoA new points do not recenter the reference",near(i2_project(pcoa,y[1,,drop=FALSE],x,fp),zc[1,,drop=FALSE],1e-8))
test("PCA new points do not recenter the reference",near(i2_project(pca,y[1,,drop=FALSE],x,fp),zp[1,,drop=FALSE],1e-8))
test("Projection leaves trained objects unchanged",{b<-sha_object(pca);i2_project(pca,y,x,fp);stopifnot(sha_object(pca)==b)})
test("Wrong feature order is rejected",throws(i2_project(pca,y[,8:1],x,fp)))
test("Wrong PCoA anchor order is rejected",throws(i2_pcoa_project_distances(pcoa,d[,10:1])))
test("Asymmetric distances are rejected",{bad<-d;bad[1,2]<-0;throws(i2_pcoa_fit(bad,pp))})
test("Negative distances are rejected",{bad<-d;bad[1,2]<-bad[2,1]<--1;throws(i2_pcoa_fit(bad,pp))})
test("Nonzero diagonal is rejected",{bad<-d;bad[1,1]<-1;throws(i2_pcoa_fit(bad,pp))})
test("Nonfinite distances are rejected",{bad<-d;bad[1,2]<-NA;throws(i2_pcoa_fit(bad,pp))})
test("Material non-Euclidean spectrum is withheld, not corrected",{bad<-matrix(c(0,1,1,1,0,5,1,5,0),3);throws(i2_pcoa_fit(bad,pp))})
test("Rank-one PCA is not made into artificial 2D coordinates",throws(i2_pca_fit(cbind(a=1:8,b=2*(1:8)),pp,fp)))
test("Identical-point PCoA is rejected",throws(i2_pcoa_fit(matrix(0,8,8),pp)))
test("Tiny references are explicitly blocked",throws(i2_pca_fit(x[1:2,],pp,fp)))
test("PCA metrics use all high-dimensional pair distances",{m<-i2_geometry_metrics(x,pca$coordinates,pca,pp);stopifnot(m$n_pairs==45);near(m$raw_distance_stress,sqrt(sum((as.numeric(dist(x))-as.numeric(dist(pca$coordinates)))^2)/sum(as.numeric(dist(x))^2)))})
test("Two-dimensional energy cannot exceed source energy",{m<-i2_geometry_metrics(x,pca$coordinates,pca,pp);stopifnot(m$current_pairwise_energy_retained<=1+1e-10)})
test("All missing projection coordinates yield unavailable diagnostics",{m<-i2_geometry_metrics(x,matrix(NA_real_,nrow(x),2),pca,pp);stopifnot(m$n_current==0,is.na(m$raw_distance_stress))})
test("Only one observed coordinate cannot establish fidelity",{z<-matrix(NA_real_,nrow(x),2);z[1,]<-0;m<-i2_geometry_metrics(x,z,pca,pp);stopifnot(m$n_current==1,is.na(m$raw_distance_stress))})
# Nine distinct texts with a deliberately low-rank lexical geometry.
# These simple botanical/geological/music strings are NOT national statements.
words<-list(c("orchard","apple","pear","plum","fruit","tree"),c("basalt","granite","quartz","marble","rock","mineral"),c("violin","piano","flute","cello","music","rhythm"))
isos<-c("AND","ARG","BWA","BGR","BDI","CAF","CYP","CZE","ECU")
texts<-vapply(1:9,function(i){g<-ceiling(i/3);shift<-(i-1)%%3;w<-words[[g]][c((shift+1):6,if(shift)1:shift else integer())];paste(rep(w,10),collapse=" ")},character(1))
mock<-lapply(1:9,function(i)unit(texts[i],isos[i],i,cls="observed_input",genre="mock_comparable_english"))
ff<-make_feature(mock);mm<-i2_projection_model(ff,"M05",root,clock=function()"2026-09-21T04:00:00Z");zz<-i2_project(mm,ff$current$country$x,ff$reference$features$country$x,fp);qq<-i2_projection_checks(ff,mm,zz,list(errors=list()),pp)
test("Low-rank numerical conformance fixture passes display gates",stopifnot(qq$passed))
test("All seventeen independent display checks recorded",stopifnot(nrow(qq$checks)==17,!anyDuplicated(qq$checks$check)))
test("No inference or alignment guarantee is inferred from gate pass",stopifnot(qq$display_release_only,qq$no_claim_of_political_alignment_or_inferential_validity))
test("Engineering source provenance blocks publication",{g<-ff;g$current_units[[1]]$eligibility_class<-"engineering_fixture";q<-i2_projection_checks(g,mm,zz,list(errors=list()),pp);stopifnot(!q$passed,q$checks$state[q$checks$check=="observed_source_scope"]=="fail")})
test("Replay provenance in reference also blocks publication",{g<-ff;g$reference$units[[1]]$eligibility_class<-"replay_fixture";stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("Unknown language blocks publication",{g<-ff;g$current_units[[1]]$language<-"unspecified";stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("Mixed genre blocks publication",{g<-ff;g$current_units[[1]]$genre<-"different";stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("Source flags block automatic display",{g<-ff;g$current_units[[1]]$flags<-list("uncertain source");stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("Collection failures block automatic display",stopifnot(!i2_projection_checks(ff,mm,zz,list(errors=list("failure")),pp)$passed))
test("Excessive OOV blocks automatic display",{g<-ff;g$current$statement$rows$oov_fraction[1]<-.99;stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("Too-short statement blocks automatic display",{g<-ff;g$current$statement$rows$eligible_tokens[1]<-1;stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("A missing contributing statement cannot disappear in country pooling",{g<-ff;g$current$statement$rows$nonzero[1]<-FALSE;stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("Cross-country exact duplicate blocks automatic display",{g<-ff;g$current_units[[2]]$text_sha256<-g$current_units[[1]]$text_sha256;stopifnot(!i2_projection_checks(g,mm,zz,list(errors=list()),pp)$passed)})
test("Changing retained-variance gate values cannot pass revalidation",{g<-mm;g$values[1]<-g$values[1]*2;g$model_id<-sha_object(g[setdiff(names(g),"model_id")]);throws(i2_validate_projection_model(g,ff,pp))})
test("Changed PCA loadings fail eigen-equation validation",{g<-mm;g$rotation[1,1]<-2;g$model_id<-sha_object(g[setdiff(names(g),"model_id")]);throws(i2_validate_projection_model(g,ff,pp))})
test("Changed frozen center is rejected",{g<-mm;g$center[1]<-2;g$model_id<-sha_object(g[setdiff(names(g),"model_id")]);throws(i2_validate_projection_model(g,ff,pp))})
# End-to-end positive contract mock. All data live below a temporary validation path.
rel<-paste0("validation/i2_fixture_",Sys.getpid());tmp<-file.path(root,rel);dir.create(tmp,recursive=TRUE)
cfg<-load_config("config/config.example.json");cfg$analysis_mode<-"extractive";cfg$analytics$history_dir<-paste0(rel,"/history");cfg$analytics$method_cache_dir<-paste0(rel,"/cache");cfg$analytics$feature_reference_dir<-paste0(rel,"/features");cfg$analytics$projection_reference_dir<-paste0(rel,"/projections")
registry<-load_registry("config/countries.csv")
obs<-lapply(1:9,function(i){co<-resolve_country(registry,isos[i]);list(iso3=isos[i],country=co$country,speaker="SYNTHETIC CONTRACT TEST",title="Not a real delegate",date="2026-09-20",text=texts[i],source_type="supplied_full_text",source_file="",language="en",genre="mock_comparable_english",translation_version="source_english",flags=list(),engineering_contract_test=TRUE)})
input<-file.path(tmp,"MOCK_OBSERVED_INPUT.json");json_write(input,obs);run<-file.path(tmp,"positive_contract");dir.create(run)
prepare_run(root,run,cfg,"local","2026-09-20",input);prepare_analytics(root,run,cfg);cp<-readRDS(file.path(run,"checkpoint.rds"))
test("Positive mock records six real adapters, not 42 fits",{l<-read.csv(file.path(run,"audit/analytics/method_ledger.csv"));stopifnot(sum(l$implementation_status=="implemented")==6,sum(l$terminal_status=="not_implemented")==36,all(l$terminal_status[l$method_id%in%c("M02","M05","M06")]%in%c("executed","withheld_quality")))})
test("Positive mock releases O3 only through evidence factory",stopifnot(cp$analytics$report_packets$O3$state=="ready",sum(vapply(cp$analytics$report_packets,function(p)p$state=="ready",logical(1)))==1))
test("PCoA remains audit-only even after passing checks",stopifnot(length(cp$analytics$inline_images)==1,cp$analytics$inline_images[[1]]$slot_id=="O3",!grepl("PCoA",cp$analytics$inline_images[[1]]$name)))
test("Ready O3 independently revalidates",d1_validate_packets(cp$analytics$report_packets,run,cp,cp$analytics$as_of_cutoff))
test("Changed published metrics are rejected",{bad<-cp$analytics$report_packets;bad$O3$payload$metrics$reference_variance_retained<-0.01;throws(d1_validate_packets(bad,run,cp,cp$analytics$as_of_cutoff))})
test("Challenger cannot replace primary in the ready slot",{bad<-cp$analytics$report_packets;bad$O3$payload$method_id<-"M06";throws(d1_validate_packets(bad,run,cp,cp$analytics$as_of_cutoff))})
test("Readiness config still cannot override publication checks",{bad<-cfg;bad$analytics$allow_ready_packets<-TRUE;throws(validate_analytics_config(bad))})
test("Sixth packet still rejected with valid O3 present",throws(d1_validate_packets(c(cp$analytics$report_packets,cp$analytics$report_packets[1]),run,cp,cp$analytics$as_of_cutoff)))
test("Ready map has exactly one allowlisted numerical image",{r<-d1_render_packets(cp,run,cfg);stopifnot(count_pattern('class="analytics-slot"',paste(r$html,collapse="\n"))==5,length(r$images)==1)})
run_audit_figures(root,run,runner=function(...)1L);build_email(root,run,cfg);qa<-validate_output(root,run,cfg)
test("Positive mock MIME includes seal plus PCA and no other chart",stopifnot(qa$passed,qa$inline_images==2,qa$country_sections==9))
test("Ready map caption retained in plaintext",stopifnot(grepl("reference variation",read_text(file.path(run,"daily_briefing.txt")),fixed=TRUE)))
features<-readRDS(file.path(run,"audit/analytics/artifacts/M02.rds"));snap<-readRDS(file.path(run,"audit/history/snapshot.rds"));again<-i2_feature_execute(cp,root,run,snap)
test("Second feature call reuses the exact frozen reference",stopifnot(again$reference_operation=="reused_frozen_reference",again$fitted_reference_id==features$fitted_reference_id))
test("Repeated transform matches the prior sparse feature matrix",stopifnot(identical(again$current,features$current)))
project<-i2_projection_execute(again,cp,root,run,"M05")
test("Projection transform reuses its trained reference model",stopifnot(project$reference_operation=="reused_reference_fit"))
test("Reused projection has unchanged coordinates",near(project$coordinates,readRDS(file.path(run,"audit/analytics/artifacts/M05.rds"))$coordinates))
test("Future report cutoff cannot admit later reference",{b<-cp;b$brief$date<-"2026-09-19";throws(i2_feature_execute(b,root,run,snap))})
# Execute the read-only CLI itself, not merely its internal functions.
model_files<-list.files(file.path(root,cfg$analytics$feature_reference_dir),recursive=TRUE,full.names=TRUE);model_before<-vapply(model_files,sha_file,character(1))
cli<-function(command)system2(file.path(R.home("bin"),"Rscript"),vapply(c("--vanilla",file.path(root,"reference_tool.R"),paste0("--command=",command),paste0("--store=",cfg$analytics$feature_reference_dir),if(isTRUE(getOption("unbrief.minimal")))"--minimal=true"),shQuote,character(1)),stdout=file.path(tmp,paste0("cli_",command,".log")),stderr=file.path(tmp,paste0("cli_",command,".log")))
test("Read-only reference list CLI executes successfully",stopifnot(cli("list")==0L))
test("Reference verification CLI executes source recomputation",stopifnot(cli("verify")==0L))
test("Both CLI commands leave every reference byte unchanged",stopifnot(identical(model_before,vapply(model_files,sha_file,character(1)))))
test("Corrupt pointer fails rather than rebootstrap",{a<-list.files(file.path(root,cfg$analytics$feature_reference_dir),pattern="^ACTIVE.rds$",recursive=TRUE,full.names=TRUE)[1];bytes<-read_bytes(a);writeBin(c(bytes,as.raw(1)),a);err<-tryCatch({i2_feature_execute(cp,root,run,snap);FALSE},error=function(e)TRUE);writeBin(bytes,a);stopifnot(err)})
test("Corrupt projection cache fails rather than refit",{a<-list.files(file.path(root,cfg$analytics$projection_reference_dir),pattern="^M05.*\\.rds$",full.names=TRUE)[1];bytes<-read_bytes(a);writeBin(c(bytes,as.raw(1)),a);err<-tryCatch({i2_projection_execute(again,cp,root,run,"M05");FALSE},error=function(e)TRUE);writeBin(bytes,a);stopifnot(err)})
summary<-list(passed=all(vapply(results,function(r)r$passed,logical(1))),tests=length(results),failed=sum(!vapply(results,function(r)r$passed,logical(1))),R_version=R.version.string,Matrix_version=as.character(packageVersion("Matrix")),fixture_scope="Synthetic numerical tests plus isolated mock observed metadata for positive publication conformance. Not real speeches, independent holdout validation, political findings, or production history.",results=results)
json_write("validation/i2_tests.json",summary);write_text("validation/i2_tests_sessionInfo.txt",capture.output(sessionInfo()))
# Preserve bounded conformance screenshots/HTML separately only when explicitly requested;
# never ship this mock as a real daily briefing or merge its history with production.
unlink(tmp,recursive=TRUE)
cat(sprintf("\n%d I2 engineering tests; %d failures.\n",summary$tests,summary$failed));if(!summary$passed)quit(status=1)
