#!/usr/bin/env Rscript
# Synthetic engineering tests. No national positions or inferential calibration.
self <- sub("^--file=", "", commandArgs()[grepl("^--file=", commandArgs())][1])
root <- normalizePath(file.path(dirname(self), ".."), winslash = "/", mustWork = TRUE)
setwd(root); options(unbrief.minimal = "--minimal=true" %in% commandArgs(trailingOnly = TRUE), unbrief.root = root)
for (f in list.files("R", pattern = "^[0-9].*\\.R$", full.names = TRUE)) { parse(f); source(f) }
results <- list()
test <- function(name, expr) {
  e <- tryCatch({ force(expr); NULL }, error = function(e) conditionMessage(e))
  results[[length(results) + 1L]] <<- list(test = name, passed = is.null(e), error = e)
  cat(if (is.null(e)) "PASS" else "FAIL", name, if (!is.null(e)) paste0(": ", e), "\n"); flush.console()
}
throws <- function(x) stopifnot(isTRUE(tryCatch({force(x); FALSE}, error = function(e) TRUE)))
near <- function(x, y, tol = 1e-9) stopifnot(isTRUE(all.equal(unname(x), unname(y), tolerance = tol, check.attributes = FALSE)))
p <- hc_policy(root); quick <- p; quick$replicates <- 10L
# Reduced repeats are ONLY for synthetic unit tests, not a changed production gate.
x <- hc_with_seed(199, function() {
  a <- matrix(runif(30 * 8, 0, .025), 30, 8)
  for (i in 1:30) a[i, ceiling(i / 10)] <- a[i, ceiling(i / 10)] + 1
  a / sqrt(rowSums(a * a))
})
rownames(x) <- sprintf("S%02d", 1:30); colnames(x) <- paste0("term", 1:8)
n <- hc_compute(x, quick)
test("Twelve implemented adapters; original hierarchy and PAM retained", stopifnot(identical(names(d1_adapters()), c("M01","M02","M05","M06","M07","M09","M08","M31","M32","M33","M34","M36"))))
test("Original 42-method registry is unchanged", stopifnot(nrow(read_d1_registry(root)) == 42L))
test("Frozen policy explicitly prohibits publication", stopifnot(p$publication_mode == "audit_only", p$replicates == 100))
test("Full feature distances match independent stats dist", near(n$distance, as.matrix(dist(x))))
test("Distance computed from normalized vectors matches cosine chord", {w <- sqrt(pmax(2 - 2 * tcrossprod(x), 0)); diag(w) <- 0; near(n$distance, w)})
test("Sparse and dense feature paths agree", stopifnot(identical(hc_compute(Matrix::Matrix(x, sparse = TRUE), quick), n)))
test("Permuting row order is resolved by country identity", stopifnot(identical(hc_compute(x[30:1,], quick), n)))
test("Deterministic repeat produces the same complete artifact", stopifnot(identical(hc_compute(x, quick), n)))
test("Caller RNG state and kind are unchanged", {set.seed(110); seed <- .Random.seed; kind <- RNGkind(); hc_compute(x, quick); stopifnot(identical(seed,.Random.seed),identical(kind,RNGkind()))})
test("All 15 predeclared linkage/k candidates retained", stopifnot(nrow(n$candidates) == 15L))
test("Average linkage remains primary even when challengers differ", stopifnot(grepl("^average__", n$selected_id)))
test("Separated synthetic features recover three average-linkage groups", stopifnot(n$selected_k == 3L, hc_ari(n$selected_groups, rep(1:3, each=10)) == 1))
test("No smaller than minimum-size cut is silently accepted", stopifnot(n$selection_size_admissible))
test("Average tree matches stats hclust", near(n$trees$average$height, hclust(as.dist(n$distance), method="average")$height))
test("Complete tree matches stats hclust", near(n$trees$complete$height, hclust(as.dist(n$distance), method="complete")$height))
test("Ward uses Ward.D2 on unsquared Euclidean distances", near(n$trees$ward.D2$height, hclust(as.dist(n$distance), method="ward.D2")$height))
test("Silhouette matches cluster package", {g <- n$selected_groups; a<-cluster::silhouette(as.integer(g),as.dist(n$distance)); z<-n$partitions[n$partitions$candidate_id==n$selected_id,];near(z$silhouette,a[,"sil_width"])})
test("One replicate row per planned candidate and sample", stopifnot(nrow(n$resample_ledger)==150L,!anyDuplicated(paste(n$resample_ledger$candidate_id,n$resample_ledger$replicate))))
test("Subsamples have 80 percent unique countries", {tab<-table(n$resample_plan$replicate);stopifnot(all(tab==24),!anyDuplicated(paste(n$resample_plan$replicate,n$resample_plan$iso3)))})
test("Fixed k is used inside every successful replicate", {tab<-split(n$resample_memberships,paste(n$resample_memberships$candidate_id,n$resample_memberships$replicate));stopifnot(all(vapply(tab,function(d)length(unique(d$cluster))==as.integer(sub('.*__','',d$candidate_id[1])),logical(1))))})
test("Every stability candidate accounts for all repeats", stopifnot(all(n$cluster_stability$planned == 10L), all(n$candidates$planned_replicates==10L)))
test("ARI is invariant to numeric labels", near(hc_ari(c(1,1,2,2),c(8,8,5,5)),1))
test("ARI negative value is retained", near(hc_ari(c(1,1,2,2),c(1,2,1,2)),-.5))
test("Identical trivial partitions have ARI one", near(hc_ari(rep(1,4),rep(9,4)),1))
test("ARI requires at least two comparable observations", stopifnot(is.na(hc_ari(1,2))))
test("Cluster singleton has zero silhouette, not missing", {d<-as.matrix(dist(matrix(c(0,1,2,20),ncol=1)));rownames(d)<-colnames(d)<-LETTERS[1:4];f<-hc_cut(hclust(as.dist(d),'average'),2L,d);stopifnot(f$silhouette[4]==0)})
g <- setNames(c(1,1,1,2,2,2),LETTERS[1:6]); sg <- setNames(c(3,3,4,4),c("A","B","D","E"))
test("Restricted exact clusters have Jaccard one", stopifnot(all(hc_best_jaccard(g,sg)$jaccard==1)))
test("Unsampled small clusters are not assigned artificial stability", {z<-hc_best_jaccard(g,sg[c(1,2,3)]);stopifnot(z$sampled_members[2]==1,!z$evaluable[2],is.na(z$jaccard[2]))})
test("Primary pair exposure denominators are symmetric", near(n$pair_opportunities,t(n$pair_opportunities)))
test("Coassignment ratios equal archived counts", {z<-n$pair_together/n$pair_opportunities;z[n$pair_opportunities==0]<-NA_real_;near(z,n$coassignment)})
test("All conditional consensus values are valid fractions", stopifnot(all(n$coassignment[is.finite(n$coassignment)]>=0 & n$coassignment[is.finite(n$coassignment)]<=1)))
test("Both same-k linkage comparisons retained", stopifnot(nrow(n$linkage_sensitivity)==2L,all(n$linkage_sensitivity$k==n$selected_k)))
test("Zero vectors are excluded and identified", {z<-x;z[1,]<-0;q<-hc_compute(z,quick);stopifnot(identical(q$excluded_iso3,'S01'),!"S01"%in%names(q$selected_groups))})
test("All zero vectors fail, not a one-cluster success", throws(hc_compute(x*0,quick)))
test("All identical nonzero vectors fail", {z<-x;z[,]<-rep(x[1,],each=nrow(x));throws(hc_compute(z,quick))})
test("Nonfinite features fail", {z<-x;z[1,1]<-NA;throws(hc_compute(z,quick))})
test("Unnormalized input fails", throws(hc_compute(x*2,quick)))
test("Duplicate country IDs fail", {z<-x;rownames(z)[1]<-rownames(z)[2];throws(hc_compute(z,quick))})
test("Missing country IDs fail", {z<-x;rownames(z)<-NULL;throws(hc_compute(z,quick))})
test("Country resource cap enforced", {q<-quick;q$max_countries<-5;throws(hc_compute(x,q))})
test("Pairwise allocation cap enforced", {q<-quick;q$max_pairwise_cells<-50;throws(hc_compute(x,q))})
failure <- hc_compute(x,quick,refitter=function(...)stop('injected engineering failure'))
test("Refit failures are fully counted", stopifnot(nrow(failure$resample_ledger)==150L,all(failure$resample_ledger$status=='failed'),all(failure$candidates$successful_replicates==0L)))
test("Failed replicates do not become stability zeros", stopifnot(all(is.na(failure$cluster_resample_jaccard$jaccard)),all(failure$cluster_stability$evaluable_fraction==0)))
test("Never observed pairs remain NA", stopifnot(all(is.na(failure$coassignment)),all(failure$pair_opportunities==0)))
tiny <- hc_compute(x[c(1,11,21,22),],quick)
test("Oversized k in a subset is blocked and retained", stopifnot(any(tiny$resample_ledger$status=='blocked_support')))
# Source-bound validation on an intentionally synthetic text fixture.
fp <- i2_policy(root,'feature')
words<-list(c('orchard','apple','pear','plum','fruit','tree'),c('basalt','granite','quartz','marble','rock','mineral'),c('violin','piano','flute','cello','music','rhythm'))
us<-lapply(1:15,function(i){w<-words[[ceiling(i/5)]];text<-paste(c(rep(w,8),rep(w[1],i),rep(w[2],i%%4)),collapse=' ');list(observation_id=paste0('synthetic-',i),observation_version_id=sha_text(paste(i,text)),iso3=sprintf('S%02d',i),country=paste('Synthetic',i),region='Unmapped',date='2026-09-20',genre='synthetic_test',language='en',translation_version='source_english',eligibility_class='engineering_fixture',source_type='engineering_fixture',source_sha256=sha_text(text),text_sha256=sha_text(text),acquired_at='2026-09-21T00:00:00Z',flags=list(),source_url='',text=text)})
vocab<-i2_fit_vocabulary(us,fp);ft<-i2_transform(us,vocab,fp)
ref<-list(schema=I2_FEATURE_SCHEMA,policy=fp,policy_hash=sha_object(fp),scope=i2_scope_key(us),environment=i2_env_signature(),units=us,source_snapshot_id=sha_text('HC engineering'),source_as_of_cutoff='2026-09-21T01:00:00Z',event_cutoff='2026-09-20',frozen_at='2026-09-21T02:00:00Z',vocabulary=vocab,features=ft,reference_is_human_gold=FALSE,exact_same_day_bootstrap_is_not_a_historical_validation=TRUE)
ref$reference_id<-sha_object(ref)
f<-list(schema=I2_FEATURE_SCHEMA,method_id='M02',reference=ref,reference_operation='fitted_frozen_reference',input_identity=i2_units_key(us),current_units=us,current=ft,source_snapshot_id=ref$source_snapshot_id,source_as_of_cutoff=ref$source_as_of_cutoff,event_cutoff=ref$event_cutoff,fitted_reference_id=ref$reference_id,created_at='2026-09-21T03:00:00Z',definition='Synthetic test')
original<-sha_object(f);v<-hc_execute(f,NULL,root)
test("Full production repeat policy executed on synthetic text", stopifnot(nrow(v$numerical$resample_ledger)==1500L))
test("Feature artifact is never mutated", stopifnot(sha_object(f)==original))
test("All 13 source and numeric screens retained", stopifnot(nrow(v$quality$checks)==13L,!anyDuplicated(v$quality$checks$check)))
test("Synthetic data never becomes published evidence", stopifnot(!v$quality$passed,!v$publication_eligible,v$quality$release_status=='audit_only'))
test("Source-bound result independently recomputes", hc_validate(v,f,root))
test("A forged ready flag is rejected", {z<-v;z$publication_eligible<-TRUE;z$result_id<-sha_object(z[setdiff(names(z),'result_id')]);throws(hc_validate(z,f,root))})
test("Modified distance is rejected even after rehash", {z<-v;z$numerical$distance[1,2]<-.99;z$result_id<-sha_object(z[setdiff(names(z),'result_id')]);throws(hc_validate(z,f,root))})
test("Modified reference binding rejected", {z<-v;z$fitted_reference_id<-'forged';z$result_id<-sha_object(z[setdiff(names(z),'result_id')]);throws(hc_validate(z,f,root))})
test("Modified quality flags rejected", {z<-v;z$quality$passed<-TRUE;z$result_id<-sha_object(z[setdiff(names(z),'result_id')]);throws(hc_validate(z,f,root,recompute=FALSE))})
test("No M07 ready producer exists", stopifnot(!any(grepl('M07',D1_READY_PRODUCERS))))
test("M07 cannot be substituted in O3", throws(i2_validate_ready_packet(list(slot_id='O3',model_id='M07',model_role='primary',release_status='released_descriptive_display'),NULL,'','2026-09-30T00:00:00Z')))
test("Unversioned policy edits rejected", {home<-tempfile();dir.create(file.path(home,'config'),recursive=TRUE);dir.create(file.path(home,'design/D1-HC'),recursive=TRUE);file.copy('config/hierarchical_policy.json',file.path(home,'config/hierarchical_policy.json'));file.copy('design/D1-HC/hierarchical_policy.json',file.path(home,'design/D1-HC/hierarchical_policy.json'));q<-p;q$min_mean_silhouette<-0;json_write(file.path(home,'config/hierarchical_policy.json'),q);throws(hc_policy(home));unlink(home,recursive=TRUE)})
test("Audit renders undefined stability as Not evaluable without changing data", {
  home<-tempfile();dir.create(file.path(home,'audit/analytics/artifacts'),recursive=TRUE)
  z<-v;z$quality$checks$observed[1]<-NA_character_
  saveRDS(z,file.path(home,'audit/analytics/artifacts/M07.rds'))
  block<-paste(hc_audit_block(home),collapse='\n')
  stopifnot(grepl('Not evaluable',block,fixed=TRUE),is.na(readRDS(file.path(home,'audit/analytics/artifacts/M07.rds'))$quality$checks$observed[1]))
  unlink(home,recursive=TRUE)
})
summary<-list(tests=length(results),failed=sum(!vapply(results,`[[`,logical(1),'passed')),results=results,R=R.version.string,cluster=as.character(packageVersion('cluster')),Matrix=as.character(packageVersion('Matrix')),scope='Synthetic engineering tests; no empirical release validation',full_source_run_is_separate=TRUE)
json_write('validation/hierarchical_tests.json',summary)
write_text('validation/hierarchical_sessionInfo.txt',capture.output(sessionInfo()))
cat(sprintf('%d hierarchical tests, %d failures.\n',summary$tests,summary$failed))
if(summary$failed)quit(status=1L)
