#!/usr/bin/env Rscript
self<-sub("^--file=","",commandArgs()[grepl("^--file=",commandArgs())][1]);root<-normalizePath(file.path(dirname(self),".."),winslash="/",mustWork=TRUE);setwd(root);options(unbrief.minimal=TRUE,unbrief.root=root)
for(f in list.files("R",pattern="^[0-9].*\\.R$",full.names=TRUE)){parse(f);source(f)}
results<-list();test<-function(name,expr){e<-tryCatch({force(expr);NULL},error=function(e)conditionMessage(e));results[[length(results)+1L]]<<-list(test=name,passed=is.null(e),error=e);cat(if(is.null(e))"PASS" else "FAIL",name,if(!is.null(e))paste0(": ",e),"\n")};throws<-function(x)stopifnot(isTRUE(tryCatch({force(x);FALSE},error=function(e)TRUE)))
near<-function(x,y,tol=1e-9)stopifnot(isTRUE(all.equal(unname(x),unname(y),tolerance=tol,check.attributes=FALSE)))
p<-pam_policy(root);q<-p;q$replicates<-10L
x<-hc_with_seed(991,function(){a<-matrix(runif(30*8,0,.025),30,8);for(i in 1:30)a[i,ceiling(i/10)]<-a[i,ceiling(i/10)]+1;a/sqrt(rowSums(a*a))});rownames(x)<-sprintf("S%02d",1:30);colnames(x)<-paste0("term",1:8)
n<-pam_compute(x,q)
test("M09 is registered",stopifnot("M09"%in%names(d1_adapters()),identical(d1_adapters()$M09$version,"d1-pam-1")))
test("PAM policy frozen and audit only",stopifnot(p$publication_mode=="audit_only",p$replicates==100L))
test("PAM uses same full-feature distance as hierarchical",near(n$distance,as.matrix(dist(x))))
test("Five k candidates retained",stopifnot(nrow(n$candidates)==5L,identical(n$candidates$k,2:6)))
test("Separated features recover k=3",stopifnot(n$selected_k==3L,hc_ari(n$selected_groups,rep(1:3,each=10))==1))
test("Selected medoids are observed countries",stopifnot(length(n$selected_medoids)==n$selected_k,all(n$selected_medoids%in%rownames(x))))
test("Silhouette independently matches cluster",{g<-n$selected_groups;a<-cluster::silhouette(as.integer(g),as.dist(n$distance));z<-n$partitions[n$partitions$candidate_id==n$selected_id,];near(z$silhouette,a[,"sil_width"])})
test("Every candidate accounts for repeats",stopifnot(nrow(n$resample_ledger)==50L,all(n$candidates$planned_replicates==10L)))
test("Roster subsamples deterministic",stopifnot(identical(pam_compute(x,q),n)))
test("Caller RNG unchanged",{set.seed(8);seed<-.Random.seed;kind<-RNGkind();pam_compute(x,q);stopifnot(identical(seed,.Random.seed),identical(kind,RNGkind()))})
test("Sparse and dense agree",stopifnot(identical(pam_compute(Matrix::Matrix(x,sparse=TRUE),q),n)))
test("Row order canonicalized",stopifnot(identical(pam_compute(x[30:1,],q),n)))
test("Coassignment fractions valid",stopifnot(all(n$coassignment[is.finite(n$coassignment)]>=0&n$coassignment[is.finite(n$coassignment)]<=1)))
test("Medoid stability is bounded",stopifnot(all(n$medoid_stability$retention_fraction>=0&n$medoid_stability$retention_fraction<=1)))
test("Zero vectors excluded",{z<-x;z[1,]<-0;r<-pam_compute(z,q);stopifnot(identical(r$excluded_iso3,"S01"),!"S01"%in%names(r$selected_groups))})
test("All zero vectors fail",throws(pam_compute(x*0,q)))
test("Nonfinite input fails",{z<-x;z[1,1]<-NA;throws(pam_compute(z,q))})
test("Unnormalized input fails",throws(pam_compute(x*2,q)))
test("Duplicate IDs fail",{z<-x;rownames(z)[1]<-rownames(z)[2];throws(pam_compute(z,q))})
test("Resource cap enforced",{z<-q;z$max_countries<-5;throws(pam_compute(x,z))})
failure<-pam_compute(x,q,refitter=function(...)stop("injected PAM failure"))
test("Failed PAM resamples are fully counted",stopifnot(nrow(failure$resample_ledger)==50L,all(failure$resample_ledger$status=="failed"),all(failure$candidates$successful_replicates==0L)))
test("Failed PAM resamples remain unevaluable, not zero stability",stopifnot(all(is.na(failure$cluster_resample_jaccard$jaccard)),all(failure$cluster_stability$evaluable_fraction==0)))
test("Never observed PAM pairs remain NA",stopifnot(all(is.na(failure$coassignment)),all(failure$pair_opportunities==0)))
# Source-bound synthetic fixture
fp<-i2_policy(root,'feature');words<-list(c('orchard','apple','pear','plum','fruit','tree'),c('basalt','granite','quartz','marble','rock','mineral'),c('violin','piano','flute','cello','music','rhythm'))
us<-lapply(1:15,function(i){w<-words[[ceiling(i/5)]];text<-paste(c(rep(w,8),rep(w[1],i),rep(w[2],i%%4)),collapse=' ');list(observation_id=paste0('synthetic-',i),observation_version_id=sha_text(paste(i,text)),iso3=sprintf('S%02d',i),country=paste('Synthetic',i),region='Unmapped',date='2026-09-20',genre='synthetic_test',language='en',translation_version='source_english',eligibility_class='engineering_fixture',source_type='engineering_fixture',source_sha256=sha_text(text),text_sha256=sha_text(text),acquired_at='2026-09-21T00:00:00Z',flags=list(),source_url='',text=text)})
vocab<-i2_fit_vocabulary(us,fp);ft<-i2_transform(us,vocab,fp);ref<-list(schema=I2_FEATURE_SCHEMA,policy=fp,policy_hash=sha_object(fp),scope=i2_scope_key(us),environment=i2_env_signature(),units=us,source_snapshot_id=sha_text('PAM engineering'),source_as_of_cutoff='2026-09-21T01:00:00Z',event_cutoff='2026-09-20',frozen_at='2026-09-21T02:00:00Z',vocabulary=vocab,features=ft,reference_is_human_gold=FALSE,exact_same_day_bootstrap_is_not_a_historical_validation=TRUE);ref$reference_id<-sha_object(ref)
f<-list(schema=I2_FEATURE_SCHEMA,method_id='M02',reference=ref,reference_operation='fitted_frozen_reference',input_identity=i2_units_key(us),current_units=us,current=ft,source_snapshot_id=ref$source_snapshot_id,source_as_of_cutoff=ref$source_as_of_cutoff,event_cutoff=ref$event_cutoff,fitted_reference_id=ref$reference_id,created_at='2026-09-21T03:00:00Z',definition='Synthetic test')
orig<-sha_object(f);v<-pam_execute(f,NULL,root)
test("Full production PAM repeats executed",stopifnot(nrow(v$numerical$resample_ledger)==500L))
test("Frozen feature artifact not mutated",stopifnot(sha_object(f)==orig))
test("All PAM quality checks retained",stopifnot(nrow(v$quality$checks)==14L,!anyDuplicated(v$quality$checks$check)))
test("Synthetic provenance remains audit only",stopifnot(!v$quality$passed,!v$publication_eligible,v$quality$release_status=='audit_only'))
test("Source-bound result recomputes",pam_validate(v,f,root))
test("Forged publication flag rejected",{z<-v;z$publication_eligible<-TRUE;z$result_id<-sha_object(z[setdiff(names(z),'result_id')]);throws(pam_validate(z,f,root))})
test("Modified distance rejected",{z<-v;z$numerical$distance[1,2]<-.9;z$result_id<-sha_object(z[setdiff(names(z),'result_id')]);throws(pam_validate(z,f,root))})
test("No M09 ready producer exists",stopifnot(!any(grepl('M09',D1_READY_PRODUCERS))))
test("M09 cannot populate O3",throws(i2_validate_ready_packet(list(slot_id='O3',model_id='M09',model_role='challenger',release_status='audit_only'),NULL,'','2026-09-30T00:00:00Z')))
test("Unversioned PAM policy edit rejected",{home<-tempfile();dir.create(file.path(home,'config'),recursive=TRUE);dir.create(file.path(home,'design/D1-PAM'),recursive=TRUE);file.copy('config/pam_policy.json',file.path(home,'config/pam_policy.json'));file.copy('design/D1-PAM/pam_policy.json',file.path(home,'design/D1-PAM/pam_policy.json'));z<-p;z$min_mean_silhouette<-0;json_write(file.path(home,'config/pam_policy.json'),z);throws(pam_policy(home));unlink(home,recursive=TRUE)})
summary<-list(tests=length(results),failed=sum(!vapply(results,`[[`,logical(1),'passed')),results=results,R=R.version.string,cluster=as.character(packageVersion('cluster')),Matrix=as.character(packageVersion('Matrix')),scope='Synthetic engineering tests; no empirical release validation')
json_write('validation/pam_tests.json',summary);write_text('validation/pam_sessionInfo.txt',capture.output(sessionInfo()));cat(sprintf('%d PAM tests, %d failures.\n',summary$tests,summary$failed));if(summary$failed)quit(status=1L)
