args<-commandArgs(FALSE);self<-sub("^--file=","",args[grep("^--file=",args)][1])
root<-normalizePath(file.path(dirname(self),".."),winslash="/",mustWork=TRUE);setwd(root)
options(unbrief.root=root,unbrief.minimal=FALSE)
for(f in list.files("R",pattern="^[0-9].*\\.R$",full.names=TRUE))source(f)
records<-list()
test<-function(name,expr){e<-tryCatch({force(expr);NULL},error=function(e)conditionMessage(e));records[[length(records)+1L]]<<-list(test=name,passed=is.null(e),error=e);cat(if(is.null(e))"PASS" else "FAIL",name,if(!is.null(e))e,"\n")}
throws<-function(expr)stopifnot(isTRUE(tryCatch({force(expr);FALSE},error=function(e)TRUE)))
p<-i5_policy()
x<-hc_with_seed(42L,function(){a<-matrix(runif(30*9,0,.01),30,9);for(i in 1:30)a[i,((ceiling(i/10)-1)*3+1):(ceiling(i/10)*3)]<-a[i,((ceiling(i/10)-1)*3+1):(ceiling(i/10)*3)]+1;a/sqrt(rowSums(a*a))})
rownames(x)<-sprintf("S%02d",1:30);colnames(x)<-paste0("term",1:9)
truth<-rep(1:3,each=10)
test("Six new adapters registered",stopifnot(all(I5_IDS%in%names(d1_adapters())),length(d1_adapters())==12L))
test("Publication allowlist unchanged",stopifnot(identical(D1_READY_PRODUCERS,"M05:tfidf-pca-display-v1")))
test("Invalid/zero feature rows rejected",{z<-x;z[1,]<-0;throws(i5_compute("M08",z))})
test("Unknown country names rejected",{z<-x;rownames(z)[1]<-"";throws(i5_compute("M08",z))})
test("Resource cap enforced",{q<-p;q$max_cells<-10;throws(i5_compute("M08",x,q))})
test("Missing country feature is not imputed",{z<-x;z[1,1]<-NA_real_;throws(i5_compute("M31",z))})
test("Signed stance cannot enter lexical geometry",{z<-x;z[1,1]<--z[1,1];throws(i5_compute("M31",z))})
set.seed(99);seed<-.Random.seed
km<-i5_compute("M08",x)
test("Kmeans preserves global RNG",stopifnot(identical(seed,.Random.seed)))
test("Kmeans recovers three separated synthetic groups",stopifnot(hc_ari(km$groups,truth)>.99))
test("All multistart candidate and resampling rows retained",stopifnot(nrow(km$candidates)==15L,nrow(km$resamples)==30L))
test("Kmeans deterministic",stopifnot(identical(km,i5_compute("M08",x))))
net<-i5_compute("M31",x)
test("Lexical graph symmetric, diagonal zero, full roster",stopifnot(identical(net$adjacency,t(net$adjacency)),all(diag(net$adjacency)==0),nrow(net$adjacency)==30L))
test("Missing stance is explicitly unavailable",stopifnot(net$stance_layer$status=="blocked_labels",net$diplomatic_interaction_layer$status=="blocked_data"))
for(id in c("M32","M33","M34")) {
 value<-i5_compute(id,x)
 test(paste(id,"recovers synthetic components"),stopifnot(hc_ari(value$groups,truth)>.99))
 test(paste(id,"retains stability evidence"),stopifnot(nrow(value$resamples)==30L,value$successful_fraction>=.9,value$mean_ari>.9))
 test(paste(id,"repeats deterministically"),stopifnot(identical(value,i5_compute(id,x))))
}
metrics<-i5_compute("M36",x)
test("Metrics preserve all nodes and components",stopifnot(nrow(metrics$nodes)==30L,metrics$components==3L,metrics$temporal_change$status=="blocked_history"))
test("Strength agrees with independent row sums",stopifnot(max(abs(metrics$nodes$strength-rowSums(net$adjacency)))<1e-12))
test("Disconnected graph betweenness finite",stopifnot(all(is.finite(metrics$nodes$betweenness))))
test("Spectral isolated node rejected",{a<-net$adjacency;a[1,]<-a[,1]<-0;throws(i5_partition("M34",x,a,3,42,p))})
test("Empty graph community is unavailable",throws(i5_partition("M32",x,net$adjacency*0,1,42,p)))
test("Signed graph rejected",{a<-net$adjacency;a[1,2]<-a[2,1]<--1;throws(i5_graph(a))})
test("Single-snapshot metrics preserve isolated nodes",{z<-diag(6);rownames(z)<-paste0("S",1:6);v<-i5_compute("M36",z);stopifnot(nrow(v$nodes)==6,all(v$nodes$degree==0),v$components==6)})
# Source-bound M02 fixture: explicitly synthetic, never eligible for publication.
fp<-i2_policy(root,"feature")
words<-list(c("orchard","apple","pear","fruit"),c("granite","basalt","quartz","rock"),c("violin","piano","flute","music"))
us<-lapply(1:30,function(i){w<-words[[ceiling(i/10)]];text<-paste(c(rep(w,10),rep(w[1],i)),collapse=" ");list(observation_id=paste0("synthetic-",i),observation_version_id=sha_text(paste(i,text)),iso3=sprintf("S%02d",i),country=paste("Synthetic",i),region="Unmapped",date="2026-09-20",genre="synthetic_test",language="en",translation_version="source_english",eligibility_class="engineering_fixture",source_type="engineering_fixture",source_sha256=sha_text(text),text_sha256=sha_text(text),acquired_at="2026-09-21T00:00:00Z",flags=list(),source_url="",text=text)})
voc<-i2_fit_vocabulary(us,fp);ft<-i2_transform(us,voc,fp)
ref<-list(schema=I2_FEATURE_SCHEMA,policy=fp,policy_hash=sha_object(fp),scope=i2_scope_key(us),environment=i2_env_signature(),units=us,source_snapshot_id=sha_text("I5 synthetic"),source_as_of_cutoff="2026-09-21T01:00:00Z",event_cutoff="2026-09-20",frozen_at="2026-09-21T02:00:00Z",vocabulary=voc,features=ft,reference_is_human_gold=FALSE,exact_same_day_bootstrap_is_not_a_historical_validation=TRUE)
ref$reference_id<-sha_object(ref)
f<-list(schema=I2_FEATURE_SCHEMA,method_id="M02",reference=ref,reference_operation="fitted_frozen_reference",input_identity=i2_units_key(us),current_units=us,current=ft,source_snapshot_id=ref$source_snapshot_id,source_as_of_cutoff=ref$source_as_of_cutoff,event_cutoff=ref$event_cutoff,fitted_reference_id=ref$reference_id,created_at="2026-09-21T03:00:00Z",definition="Synthetic engineering fixture")
for(id in I5_IDS) {
 v<-i5_execute(id,f,root)
 test(paste(id,"source-bound result recomputes"),i5_validate(v,f,root))
 test(paste(id,"round-trip and table inspection preserve identity"),{z<-unserialize(serialize(v,NULL,version=3));if(!is.null(z$numerical$candidates))capture.output(print(z$numerical$candidates));i5_validate(z,f,root)})
 test(paste(id,"synthetic sources never pass source quality"),stopifnot(!v$source_quality_pass,!v$publication_eligible))
 test(paste(id,"rehashing cannot promote release"),{z<-v;z$publication_eligible<-TRUE;z$result_id<-i5_hash(z[setdiff(names(z),"result_id")]);throws(i5_validate(z,f,root))})
 test(paste(id,"rehashing cannot alter numerical data"),{z<-v;z$numerical$kind<-"forged";z$result_id<-i5_hash(z[setdiff(names(z),"result_id")]);throws(i5_validate(z,f,root))})
}
home<-tempfile("i5-proof-");dir.create(file.path(home,"audit/analytics/artifacts"),recursive=TRUE)
immutable_write(file.path(home,"audit/analytics/artifacts/M02.rds"),serialize(f,NULL,version=3))
context<-list(snapshot_id=f$source_snapshot_id)
# Use a bare cp only when validating an existing feature fixture without rebuilding observations.
for(id in I5_IDS) {
 v<-i5_execute(id,f,root);path<-paste0("audit/analytics/artifacts/",id,".rds");immutable_write(file.path(home,path),serialize(v,NULL,version=3))
 proof<-list(method_id=id,context=context,artifact_ref=path,artifact_sha256=sha_file(file.path(home,path)),feature_artifact_ref="audit/analytics/artifacts/M02.rds",feature_artifact_sha256=sha_object(f),error="",gates=i5_gates(id,v,f))
 test(paste(id,"proof independently validates"),i5_validate_proof(proof,home,root))
 test(paste(id,"forged gate rejected"),{z<-proof;z$gates[[1]]$state<-"unestablished";throws(i5_validate_proof(z,home,root))})
}
result<-rows_frame(records,c("test","passed","error"))
dest<-Sys.getenv("I5_TEST_REPORT",file.path(tempdir(),"i5-tests.csv"));csv_write(dest,result)
failed<-sum(!vapply(records,`[[`,logical(1),"passed"));cat(length(records),"checks;",failed,"failures. Report:",dest,"\n")
if(failed)quit(status=1)
