# Fast structural tests for the additive Shiny/D1 adapter. Full replay acceptance is
# recorded separately because it exercises the complete D1 analytical pipeline.
args <- commandArgs(FALSE)
self <- sub("^--file=", "", args[grep("^--file=", args)][1])
root <- normalizePath(file.path(dirname(self), ".."), winslash="/", mustWork=TRUE)
ui <- file.path(root, "ui")
setwd(ui)
source(file.path(ui, "R", "load.R")); load_readout(ui, globalenv())
sys.source(file.path(root, "interfaces", "shiny_v1.R"), envir=globalenv())
results <- list(); test <- function(name, expr) { ok <- tryCatch({force(expr); TRUE}, error=function(e) FALSE); results[[length(results)+1L]] <<- data.frame(test=name, passed=ok); if(!ok) stop(name); invisible(ok) }
test("Capability schema", stopifnot(identical(un_readout_capabilities()$request_schema, "un.readout.request.v1")))
test("Dynamic topics enabled", stopifnot(isTRUE(un_readout_capabilities()$dynamic_topics)))
test("Five-output gate retained", stopifnot(isTRUE(un_readout_capabilities()$exactly_five_outputs), isTRUE(un_readout_capabilities()$publication_gates)))
test("No-send retained", stopifnot(isTRUE(un_readout_capabilities()$no_send)))
test("Legacy codebook declared unchanged", stopifnot(isTRUE(un_readout_capabilities()$legacy_codebook_unchanged)))
pin <- trimws(readLines(file.path(root,"config","shiny_adapter.sha256"), warn=FALSE)[1])
test("Pinned adapter hash", stopifnot(identical(pin, sha256_file(file.path(root,"interfaces","shiny_v1.R")))))
cfg <- new_config("2026-09-23","2026-09-23",c("Food Security","Artificial Intelligence"),list(),"d1")
test("Arbitrary topic preserved", stopifnot(identical(vapply(cfg$fixed_topics, `[[`, character(1), "label"), c("Food Security","Artificial Intelligence"))))
test("Discovery independent of watchlist", stopifnot(identical(cfg$discovery_scope,"all_eligible_source_texts_independent_of_fixed_topics")))
d1core <- new.env(parent=globalenv()); sys.source(file.path(root,"R","00_core.R"), envir=d1core); legacy <- d1core$json_read(file.path(root,"config","issue_codebook.json"))
test("Legacy four-topic prefix unchanged", stopifnot(identical(vapply(legacy[1:4], `[[`, character(1), "issue_id"), c("iran","cuba","ukraine","ai"))))
out <- do.call(rbind, results); dir.create(file.path(root,"validation"),showWarnings=FALSE); utils::write.csv(out,file.path(root,"validation","shiny_adapter_tests.csv"),row.names=FALSE)
cat(sprintf("%d Shiny adapter tests; %d failures.\n", nrow(out), sum(!out$passed)))
