#!/usr/bin/env Rscript
if(!l10n_info()[["UTF-8"]])invisible(try(Sys.setlocale("LC_CTYPE",if(.Platform$OS.type=="windows")"English_United States.utf8" else "C.UTF-8"),silent=TRUE))
self<-sub("^--file=","",commandArgs()[grepl("^--file=",commandArgs())][1]);root<-normalizePath(file.path(dirname(self),".."),winslash="/",mustWork=TRUE);setwd(root)
if(file.exists("config/library_path.txt")){lib<-readLines("config/library_path.txt",warn=FALSE)[1];if(dir.exists(lib)).libPaths(c(lib,.libPaths()))}
options(unbrief.minimal="--minimal=true"%in%commandArgs(trailingOnly=TRUE))
for(f in list.files("R",pattern="^[0-9].*\\.R$",full.names=TRUE))source(f)
results<-list();test<-function(name,expr){err<-tryCatch({force(expr);NULL},error=function(e)conditionMessage(e));results[[length(results)+1]]<<-list(test=name,passed=is.null(err),error=err);cat(if(is.null(err))"PASS" else "FAIL",name,if(!is.null(err))paste0(": ",err) else "","\n")}
throws<-function(expr){x<-tryCatch({force(expr);FALSE},error=function(e)TRUE);stopifnot(x)}
tmp<-tempfile();dir.create(tmp)
book<-validate_issue_book(json_read("config/issue_codebook.json"));legacy<-json_read("examples/2026-09-23/legacy_codebook.json");registry<-load_registry("config/countries.csv");cfg<-load_config("config/config.example.json")
test("JSON UTF-8, quotes, arrays and null round-trip",{x<-list(a=1,b=list(TRUE,FALSE,NULL),text="É — UN 🇺🇳 \" \\ \n",empty=list());stopifnot(identical(json_parse_minimal(json_minimal(x)),x))})
test("JSON escaped surrogate pair",stopifnot(identical(json_parse_minimal('"\\uD83C\\uDDFA"'),intToUtf8(0x1F1FA))))
test("JSON duplicate keys rejected",throws(json_parse_minimal('{"a":1,"a":2}')))
test("JSON trailing tokens rejected",throws(json_parse_minimal('[]true')))
test("JSON invalid escape rejected",throws(json_parse_minimal('"\\q"')))
test("JSON unpaired surrogate rejected",throws(json_parse_minimal('"\\uD800"')))
test("JSON leading-zero number rejected",throws(json_parse_minimal('01')))
test("JSON trailing comma rejected",throws(json_parse_minimal('[1,]')))
test("JSON raw newline in string rejected",throws(json_parse_minimal('"abc\nxyz"')))
test("Base64 round-trips 0-512 bytes",for(n in 0:512){x<-as.raw((seq_len(n)-1)%%256);stopifnot(identical(unb64(b64(x)),x))})
test("Base64 known RFC encoding",stopifnot(b64(charToRaw("foobar"))=="Zm9vYmFy"))
test("Base64 corrupt padding rejected",throws(unb64("====")))
test("SHA-256 known abc digest",stopifnot(sha_text("abc")=="ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"))
test("Source URL host allowlist",stopifnot(source_url("/en/ga/81/1")=="https://transcripts.un.org/en/ga/81/1"))
test("Off-host source URL rejected",throws(source_url("https://example.com/transcript")))
test("Misleading suffix host rejected",throws(source_url("https://transcripts.un.org.evil.example/en/ga")))
test("Header CRLF injection rejected",throws(header_text("Daily\r\nBcc: unknown@example.com")))
test("Invalid email placeholder rejected",throws(validate_address("[your.email]@state.gov")))
test("Email address accepted",stopifnot(validate_address("reviewer@example.com")=="reviewer@example.com"))
test("HTML special characters escaped",stopifnot(html_escape('<x a="b">&')=="&lt;x a=&quot;b&quot;&gt;&amp;"))
test("Broken table balance rejected",throws(check_tables("<table><tr><td>x</tr></td></table>")))
test("Valid table balance accepted",check_tables("<table><tr><td>x</td></tr></table>"))
test("Source date parsed",stopifnot(parse_source_date("September 23, 2026")=="2026-09-23"))
test("Invalid calendar date rejected",throws(parse_source_date("2026-02-30")))
test("Structured country resolves",stopifnot(resolve_country(registry,"AND")$country=="Andorra"))
test("Unresolved speaker name not mapped to country",stopifnot(is.null(resolve_country(registry,"An invented person"))))
speeches<-json_read("examples/2026-09-23/speeches.json");analyses<-json_read("examples/2026-09-23/analyses.json")
test("Legacy and fresh codebooks retain distinct versions",{stopifnot(all(vapply(legacy,function(i)i$version=="1.0-inherited-reviewed-and-lexicon",logical(1))),all(vapply(book,function(i)i$version=="2.1-semantic-presence",logical(1))),length(legacy)==10,length(book)==13)})
test("All 39 original DOCX hashes match",stopifnot(verify_replay_sources("examples/2026-09-23",speeches)==39))
test("All 39 normalized texts and hashes validate",for(s in speeches)normalized_speech(s,registry))
test("All 155 inherited summary points retain exact evidence",{for(s in speeches)validate_analysis(analyses[[s$iso3]],s,legacy,inherited=TRUE);stopifnot(sum(vapply(analyses,function(a)length(a$bullets),integer(1)))==155)})
test("Text hash corruption rejected",{s<-speeches[[1]];s$text_sha256<-paste(rep("0",64),collapse="");throws(normalized_speech(s,registry))})
test("Country/ISO3 mismatch rejected",{s<-speeches[[1]];s$country<-"Argentina";throws(normalized_speech(s,registry))})
test("Sentence reconstruction mismatch rejected",{s<-speeches[[1]];s$sentences[[1]]$text<-"Tampered sentence";throws(normalized_speech(s,registry))})
test("Unsupported evidence quote rejected",throws(validate_evidence(list(list(sentence_id=speeches[[1]]$sentences[[1]]$id,quote="not in this source")),speeches[[1]]$sentences)))
test("Unknown evidence sentence rejected",throws(validate_evidence(list(list(sentence_id="UNKNOWN",quote="arbitrary")),speeches[[1]]$sentences)))
test("Missing issue decision rejected",{a<-analyses[[speeches[[1]]$iso3]];a$issues<-a$issues[-1];throws(validate_analysis(a,speeches[[1]],legacy,inherited=TRUE))})
test("Duplicate issue decision rejected",{a<-analyses[[speeches[[1]]$iso3]];a$issues[[2]]<-a$issues[[1]];throws(validate_analysis(a,speeches[[1]],legacy,inherited=TRUE))})
test("Prose artifacts rejected",{a<-analyses[[speeches[[1]]$iso3]];a$bullets[[1]]$text<-"[AND.1] An internal marker";throws(validate_analysis(a,speeches[[1]],legacy,inherited=TRUE))})
fixture<-list(iso3="AND",country="Andorra",speaker="Fixture Speaker",title="Delegate",date="2026-09-23",source_type="engineering_fixture",text="We call for Security Council reform and permanent representation. We request accessible climate finance to support adaptation and protect coastal communities. We urge international cooperation on artificial intelligence standards and equitable digital access.")
s<-normalized_speech(fixture,registry);a<-extractive_analysis(s,book)
test("Extractive bullets are exact source excerpts",validate_analysis(a,s,book))
test("No keyword hit is uncertain, not absent",stopifnot(all(vapply(Filter(function(i)!length(i$evidence),a$issues),function(i)i$status=="uncertain",logical(1)))))
test("Identical country texts deduplicate",{g<-group_countries(list(s,s));stopifnot(length(g$speeches)==1&&length(g$duplicates)==1)})
test("Distinct interventions preserve sentence provenance",{s2<-s;s2$text<-paste(s2$text,"A second distinct intervention.");s2$sentences<-sentence_units(s2$text);s2$text_sha256<-sha_text(s2$text);g<-group_countries(list(s,s2));stopifnot(length(g$speeches)==1,length(g$speeches[[1]]$source_parts)==2,any(grepl("^P2_",vapply(g$speeches[[1]]$sentences,function(z)z$id,character(1)))))})
item<-list(slug="ga/81/fixture",date="2026-09-23",title="General Assembly general debate",body="GA",category="ga",hasTranscript=TRUE,pageUrl="https://transcripts.un.org/en/ga/81/fixture",jsonUrl="https://transcripts.un.org/en/ga/81/fixture.json")
doc<-list(video=list(date=item$date,slug=item$slug),disclaimer="Engineering fixture, not a live UN transcript.",transcript=list(language="en",data=list(list(statement_number=1,speaker=list(name="Fixture Speaker",affiliation="AND",`function`="Delegate"),pageUrl=item$pageUrl,paragraphs=list(list(sentences=list(list(text=s$text,start=0,end=30))))))))
st<-cfg;st$live$min_statement_words<-20
source<-list(sha256=sha_text(json_text(doc)))
test("UN JSON detail parser accepts fixture",stopifnot(length(parse_api_detail(doc,item,item$date,registry,st,source)$speeches)==1))
test("UN date mismatch rejected",{d<-doc;d$video$date<-"2026-09-22";throws(parse_api_detail(d,item,item$date,registry,st,source))})
test("UN language mismatch rejected",{d<-doc;d$transcript$language<-"fr";throws(parse_api_detail(d,item,item$date,registry,st,source))})
test("UN invalid timing rejected",{d<-doc;d$transcript$data[[1]]$paragraphs[[1]]$sentences[[1]]$end<- -1;throws(parse_api_detail(d,item,item$date,registry,st,source))})
test("UN institutional speaker excluded",{d<-doc;d$transcript$data[[1]]$speaker[["function"]]<-"President of the General Assembly";r<-parse_api_detail(d,item,item$date,registry,st,source);stopifnot(length(r$speeches)==0&&length(r$excluded)==1)})
test("Long unresolved-country statement requires review",{old<-doc;doc$transcript$data[[1]]$speaker$affiliation<-"Unmapped delegation";ar<-new_archive(file.path(tmp,"unknown"));iv<-list(total=1,totalIncludingOther=1,page=1,hasMore=FALSE,meetings=list(item));ff<-function(url,settings,body=NULL,headers=list())charToRaw(json_text(if(grepl("meetings.json",url,fixed=TRUE))iv else doc));z<-collect_live(item$date,registry,ar,st,ff);stopifnot(length(z$speeches)==0&&length(z$collection$errors)==1);doc<-old})
inv<-list(total=1,totalIncludingOther=1,page=1,hasMore=FALSE,meetings=list(item))
fetch<-function(url,settings,body=NULL,headers=list())charToRaw(json_text(if(grepl("meetings.json",url,fixed=TRUE))inv else doc))
test("Inventory and detail collection with mocked transport",{ar<-new_archive(file.path(tmp,"collect"));z<-collect_live(item$date,registry,ar,st,fetch);stopifnot(length(z$speeches)==1&&length(z$collection$errors)==0)})
test("Missing transcript remains a collection error",{old<-inv;inv$meetings[[1]]$hasTranscript<-FALSE;ar<-new_archive(file.path(tmp,"missing"));z<-collect_live(item$date,registry,ar,st,fetch);stopifnot(length(z$speeches)==0&&length(z$collection$errors)==1);inv<-old})
test("Pagination inventory drift rejected",{old<-inv;inv$total<-2;ar<-new_archive(file.path(tmp,"drift"));throws(collect_live(item$date,registry,ar,st,fetch));inv<-old})
# Test model control flow without calling a remote service or using real credentials.
cfg_test<-cfg;cfg_test$allow_external_ai<-TRUE;cfg_test$storage$cache_dir<-paste0("test_cache_",Sys.getpid())
oldkey<-Sys.getenv("OPENAI_API_KEY");Sys.setenv(OPENAI_API_KEY="offline-test-fixture-no-network")
responses<-list(a,list(decision="accept",notes="Engineering fixture only.",analysis=a));calls<-0L
model_fetch<-function(url,settings,body=NULL,headers=list()){calls<<-calls+1L;charToRaw(json_text(list(status="completed",model="offline-fixture",id=paste0("fixture-",calls),usage=list(input_tokens=1,output_tokens=1),output=list(list(content=list(list(type="output_text",text=json_text(responses[[calls]]))))))))}
client<-new_model_client(root,cfg_test,file.path(tmp,"model"),model_fetch)
test("Two-pass model control flow with mocked responses",{out<-model_analyze(client,s,book);stopifnot(calls==2&&out$verification$status=="model_reviewed")})
test("Source-bound cache avoids new model calls",{out<-model_analyze(client,s,book);stopifnot(calls==2&&isTRUE(out$verification$cache_reused))})
test("External model processing disabled by default",{c<-new_model_client(root,cfg,file.path(tmp,"blocked"),model_fetch);throws(model_call(c,"x",list(),list(),"x","fixture"))})
test("Invocation-wide request budget enforced",{c<-new_model_client(root,cfg_test,file.path(tmp,"budget"),model_fetch);c$budget$used<-cfg_test$model$max_calls_per_run;throws(model_call(c,"x",list(),list(),"x","fixture"))})
test("Incomplete model response rejected",{badfetch<-function(...)charToRaw('{"status":"incomplete","output":[]}');c<-new_model_client(root,cfg_test,file.path(tmp,"incomplete"),badfetch);throws(model_call(c,"x",list(),list(),"x","fixture"))})
if(nzchar(oldkey))Sys.setenv(OPENAI_API_KEY=oldkey) else Sys.unsetenv("OPENAI_API_KEY")
unlink(file.path(root,cfg_test$storage$cache_dir),recursive=TRUE)
seal<-read_bytes("assets/USUN_Seal.png")
test("MIME round-trip with UTF-8 and inline image",{raw<-assemble_mime("É plain",'<html><body><img src="cid:test@local"></body></html>',list(list(name="seal.png",cid="test@local",bytes=seal)),"UN | É", "2026-09-24T20:00:00Z","TEST");p<-flatten_mime(parse_mime(raw));stopifnot(length(p)==5,identical(Filter(function(z)z$type=="image/png",p)[[1]]$bytes,seal),identical(rawToChar(Filter(function(z)z$type=="text/plain",p)[[1]]$bytes),"É plain"))})
test("MIME bare LF rejected",throws(parse_mime(charToRaw("Subject: test\n\ntext"))))
latest<-file.path(root,"output/latest.json")
if(file.exists(latest))test("Generated replay MIME and chart totals validate",{run<-file.path(root,json_read(latest)$run);stopifnot(validate_output(root,run,json_read(file.path(run,"config_used.json")))$passed)})
if(file.exists(latest))test("Replay carries distinct inherited and provisional versions",{run<-file.path(root,json_read(latest)$run);if(json_read(file.path(run,"brief.json"))$source=="replay"){cb<-json_read(file.path(run,"audit/codebook.json"));stopifnot(sum(vapply(cb,function(i)i$version=="1.0-inherited-reviewed-and-lexicon",logical(1)))==10,sum(vapply(cb,function(i)i$version=="2.1-provisional-replay-scan",logical(1)))==3)}})
if(requireNamespace("jsonlite",quietly=TRUE))test("Package JSON backend matches offline adapter",{j<-json_minimal(list(a=list(1,TRUE,NULL),b="É \\ quote \""));stopifnot(identical(jsonlite::fromJSON(j,simplifyVector=FALSE),json_parse_minimal(j)))})
if(requireNamespace("digest",quietly=TRUE))test("Package digest known SHA-256",stopifnot(digest::digest(charToRaw("abc"),algo="sha256",serialize=FALSE)=="ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"))
if(requireNamespace("base64enc",quietly=TRUE))test("Package Base64 matches offline adapter",{old<-getOption("unbrief.minimal");options(unbrief.minimal=TRUE);x<-b64(seal);options(unbrief.minimal=old);stopifnot(x==base64enc::base64encode(seal))})
if(requireNamespace("xml2",quietly=TRUE))test("Package DOCX parser reads all replay originals",{dest<-file.path(tmp,"docx");dir.create(dest);utils::unzip("examples/2026-09-23/original_sources.zip",exdir=dest);for(p in list.files(dest,full.names=TRUE))stopifnot(length(docx_paragraphs(p))>5)})
# Release 2.1 regression tests: fixed-topic contracts and regional display.
test("Permanent topics have exact labels and order",stopifnot(identical(vapply(book[1:4],function(i)i$label,character(1)),FIXED_ISSUE_LABELS)))
test("Missing permanent topic rejected",throws(validate_issue_book(book[-2])))
test("Reordered permanent topics rejected",throws(validate_issue_book(book[c(2,1,3:length(book))])))
test("Duplicate issue ID rejected",throws(validate_issue_book(c(book,book[1]))))
test("Fixed order config cannot silently change",{z<-cfg;z$display$fixed_issue_order<-list("cuba","iran","ukraine","ai");f<-file.path(tmp,"bad_config.json");json_write(f,z);throws(load_config(f))})
test("Old configuration receives region-first defaults",{z<-cfg;z$display<-NULL;f<-file.path(tmp,"old_config.json");json_write(f,z);stopifnot(load_config(f)$display$group_by=="region")})
test("Schema is bound to all configured topics",{schema<-bind_issue_schema(json_read("schemas/country_analysis.json"),book);stopifnot(setequal(unlist(schema$properties$issues$items$properties$issue_id$enum),vapply(book,function(x)x$issue_id,character(1))))})
test("Optional topic extension reaches schema",{extra<-book[[5]];extra$issue_id<-"new_fixture_topic";schema<-bind_issue_schema(json_read("schemas/country_analysis.json"),c(book,list(extra)));stopifnot("new_fixture_topic"%in%unlist(schema$properties$issues$items$properties$issue_id$enum))})
match_fixed<-function(id,text)grepl(Filter(function(i)i$issue_id==id,book)[[1]]$extractive_regex,text,ignore.case=TRUE,perl=TRUE)
test("AI separate from generic digital policy",stopifnot(!match_fixed("ai","We call for digital connectivity and cyber security."),match_fixed("ai","We call for responsible artificial intelligence and AI safeguards.")))
test("AI pattern excludes aid and paid",stopifnot(!match_fixed("ai","We paid for humanitarian aid and chaired the meeting.")))
test("Iran separate from generic Middle East",stopifnot(!match_fixed("iran","Gaza and Hormuz require peace."),match_fixed("iran","Iran must return to dialogue.")))
test("Cuba separate from generic sanctions",stopifnot(!match_fixed("cuba","We oppose unilateral sanctions."),match_fixed("cuba","We request an end to the embargo on Cuba.")))
test("Ukraine separate from generic Russia and Black Sea",stopifnot(!match_fixed("ukraine","We discussed trade with Russia and Black Sea tourism."),match_fixed("ukraine","We support reconstruction in Ukraine.")))
test("Incidental Franco-Iranian nationality excluded",stopifnot(!match_fixed("iran","A Franco-Iranian artist commented on education.")))
ordered<-order_country_readouts(rev(speeches),cfg)
test("Countries grouped in configured regional order",{regions<-vapply(ordered,function(x)x$region,character(1));stopifnot(identical(unique(regions),region_sequence(regions,cfg)))})
test("Country names alphabetized inside each region",{for(reg in unique(vapply(ordered,function(x)x$region,character(1)))){z<-Filter(function(x)x$region==reg,ordered);names<-vapply(z,function(x)country_sort_key(x$country),character(1));stopifnot(identical(names,sort(names,method="radix")))}})
test("Unmapped region displayed last",stopifnot(tail(region_sequence(c("Unmapped","Custom Region","Africa"),cfg),1)=="Unmapped"))
test("All 39 source regions are preserved",{for(z in ordered)stopifnot(identical(z$region,Filter(function(x)x$iso3==z$iso3,speeches)[[1]]$region))})
up<-upgrade_replay_topics(analyses,speeches,legacy,book)
test("Replay keeps all inherited summary bytes",{for(id in names(analyses))stopifnot(identical(analyses[[id]]$bullets,up$analyses[[id]]$bullets))})
test("Replay keeps all original ten issue decisions",{for(id in names(analyses))for(i in analyses[[id]]$issues)stopifnot(identical(i,Filter(function(x)x$issue_id==i$issue_id,up$analyses[[id]]$issues)[[1]]))})
test("Replay expands to 507 explicitly versioned cells",stopifnot(sum(vapply(up$analyses,function(x)length(x$issues),integer(1)))==507,length(up$codebook)==13))
test("New topic no-hit is unresolved, never absent",{for(z in up$analyses)for(i in Filter(function(x)x$issue_id%in%c("iran","cuba","ai"),z$issues))if(!length(i$evidence))stopifnot(i$status=="uncertain")})
test("Every provisional positive retains exact evidence",{for(z in speeches)for(i in Filter(function(x)x$issue_id%in%c("iran","cuba","ai"),up$analyses[[z$iso3]]$issues))if(i$status=="present"){stopifnot(length(i$evidence)>0);validate_evidence(i$evidence,z$sentences)}})
zero<-data.frame(issue_id=FIXED_ISSUE_IDS,issue=FIXED_ISSUE_LABELS,n_present=0L,n_unknown=0L)
test("All four topics appear with zero confirmed mentions",{h<-fixed_watchlist_html(zero,5,list(analysis_mode="openai"));for(label in FIXED_ISSUE_LABELS)stopifnot(grepl(paste0(">",label,"</td>"),h,fixed=TRUE));stopifnot(count_pattern("0 / 5",h)==4)})
test("No-source day is not displayed as zero prevalence",{h<-fixed_watchlist_html(zero,0,list(analysis_mode="openai"));stopifnot(count_pattern("No country texts",h)==4,!grepl("0 / 0",h,fixed=TRUE))})
test("Unresolved counts cannot disappear from watchlist",{z<-zero;z$n_unknown<-5L;h<-fixed_watchlist_html(z,5,list(analysis_mode="openai"));stopifnot(count_pattern(">5</td>",h)==4)})
test("Regional heading escapes HTML",{h<-region_heading_html("Custom <Region>",2);check_tables(h);stopifnot(grepl("&lt;Region&gt;",h,fixed=TRUE))})
summary<-list(passed=all(vapply(results,function(x)x$passed,logical(1))),tests=length(results),failed=sum(!vapply(results,function(x)x$passed,logical(1))),R_version=as.character(getRversion()),minimal_mode=isTRUE(getOption("unbrief.minimal")),network="Mocked only; no live API request",package_backends_tested=as.list(c("jsonlite","digest","base64enc","xml2")[vapply(c("jsonlite","digest","base64enc","xml2"),requireNamespace,logical(1),quietly=TRUE)]),results=results)
json_write("validation/r_tests.json",summary);write_text("validation/r_tests_sessionInfo.txt",capture.output(sessionInfo()));unlink(tmp,recursive=TRUE)
cat(sprintf("\n%d tests; %d failures.\n",summary$tests,summary$failed))
if(!summary$passed)quit(status=1)
