"""Create a source-backed notebook companion from completed comparison outputs."""
from __future__ import annotations
import argparse,json
from pathlib import Path
import nbformat as nbf


def build(root: Path) -> Path:
    result=root/'results'
    s=json.loads((result/'summary.json').read_text())
    pairs=json.loads((result/'comparisons.json').read_text())
    ari=next(p['ari'] for p in pairs if p['right']=='strict_semantic_pca64_k10' and p['left']=='strict_lsa64_k10')
    n=json.loads((result/'neighborhoods.json').read_text())
    cross=next(p['mean_overlap'] for p in n if p['left']=='lexical_lsa64' and p['right']=='semantic_raw384' and p['exclusion']=='meeting' and p['k']==15)
    d=json.loads((result/'display-diagnostics.json').read_text())
    fidelity=next(p['neighbor_recall15'] for p in d if p['setting']=='strict_semantic_pca64_k10')
    probes=json.loads((result/'probe-results.json').read_text())
    reversed_count=sum(p['semantic_opposite']>p['semantic_paraphrase'] for p in probes)
    md=nbf.v4.new_markdown_cell;code=nbf.v4.new_code_cell
    cells=[md('# Lexical and semantic structure\n\n**UN Transcript Project · Provisional development analysis · October 1–4, 2026**\n\n## Bottom line\n\n'
        f'The pinned local encoder adds a different view of the same language, not a validated map of political agreement. On the **1,641 strict passages**, the matched 64-dimensional k-means partitions agree at **ARI {ari:.3f}**. Across different meetings, the two representations share **{cross:.1%} of their 15 nearest neighbors** on average.\n\n'
        f'All **{s["cache_audit"]["passages"]:,} baseline-eligible passages** were embedded without truncation or sampling. All six configurations and 16 meeting-omission refits completed. **All 37 temporal-holdout transcripts remain unopened.** Machine-review status is unchanged; no human approvals were recorded.\n\n'
        f'Two limitations govern interpretation: the encoder places opposite positions closer than paraphrases in **{reversed_count}/{len(probes)} authored probes**, and the primary 2-D display retains only **{fidelity:.1%} of its 15 nearest neighbors**. Use source-linked high-dimensional relationships for exploration; do not read stance or coalitions from the picture.'),
      md('## Context and methods\n\nMiniLM is the official English `sentence-transformers/all-MiniLM-L6-v2` ONNX float32 export, pinned to revision `1110a243fdf4706b3f48f1d95db1a4f5529b4d41`. Model and tokenizer bytes are verified against the checked-in manifest. Inference uses CPU-only ONNX Runtime 1.23.0 and tokenizers 0.22.1, without remote inference. See `runtime/research/semantic_review/RUN_CONTRACT.md`.\n\n**Key assumptions.** Source segments are observed turns, not verified complete speeches. All labels remain machine-only. Equal-passage fitting is retained; observed-parent and meeting weights affect summaries only. The pretrained encoder is fixed, not trained on these records. Its pretraining exposure has not been audited as a globally unseen-data guarantee.\n\nThe tokenizer\'s embedded 128-token defaults are disabled. Every WordPiece is retained in nonoverlapping windows of at most 254 content tokens plus CLS/SEP. Mask-aware mean pooling is followed by normalized, content-token-weighted chunk aggregation. Original code-point intervals and text hashes remain in `results/embedding-cache/chunks.json`. Tokenizer normalization is recorded, not represented as original-text editing.\n\nThe saved TF-IDF/LSA results are reused unchanged. Matched comparisons retain identical passage IDs, order, and source hashes. PCA32/PCA64 and Ward comparisons match the saved lexical dimension and algorithm; raw384 versus LSA64 explicitly differs in dimension. The chosen cluster count is a sensitivity setting, not an estimate of the true number of diplomatic groups.'),
      code("from pathlib import Path\nimport json, html\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom IPython.display import display, HTML\nROOT=Path.cwd()\nRESULTS=ROOT/'results'\nFIG=ROOT/'figures'; FIG.mkdir(exist_ok=True)\nread=lambda name: json.loads((RESULTS/name).read_text())\nsummary=read('summary.json'); fits=pd.DataFrame(read('fits.json'))\npairs=pd.DataFrame(read('comparisons.json')); neighborhoods=pd.DataFrame(read('neighborhoods.json'))\nrefits=pd.DataFrame(read('refits.json')); probes=pd.DataFrame(read('probe-results.json'))\ndisplays=pd.DataFrame(read('display-diagnostics.json'))\ndef finish(fig, name):\n    fig.tight_layout()\n    fig.savefig(FIG/name, dpi=160, bbox_inches='tight')\n    plt.show()\ndisplay(pd.DataFrame({'Population':['Strict','Inclusive','Original baseline'],'Passages':[summary['population_counts'][k] for k in ['strict','inclusive','baseline']]}))"),
      md('## Results\n\n### 1. Partition agreement depends on representation\n\nARI compares co-membership, not cluster numbers or policy alignment. These paired partitions share their full passage population. Comparing silhouettes across different feature geometries does not select a defensible winner.'),
      code("selected=pairs[pairs['left'].str.startswith('strict_lsa')].copy()\nlabels=['LSA64 / raw semantic384 · k-means','LSA32 / semantic PCA32 · k-means','LSA64 / semantic PCA64 · k-means','LSA64 / semantic PCA64 · Ward']\nfig,ax=plt.subplots(figsize=(10,4.5))\ny=np.arange(len(selected)); ax.barh(y,selected['ari']);ax.set_yticks(y,labels);ax.invert_yaxis();ax.set_xlim(0,1)\nfor i,v in enumerate(selected['ari']):ax.text(v+0.015,i,f'{v:.3f}',va='center')\nax.set_xlabel('Adjusted Rand index (1 = identical partition)');ax.set_title('Same 1,641 passages · matched settings except raw384 contrast')\nfinish(fig,'figure-1.png')"),
      md('### 2. Neighbors differ beyond source boundaries\n\nEach bar is the mean intersection of two 15-neighbor sets divided by 15. Excluding the same source segment or meeting prevents within-source proximity from dominating this diagnostic. The percentages are not probabilities of shared policy positions.'),
      code("fig,ax=plt.subplots(figsize=(9,4.5))\nx=np.arange(3); scopes=['self','parent','meeting']\nfor j,(right,label) in enumerate([('semantic_raw384','Lexical / semantic384'),('semantic_pca64','Lexical / semantic PCA64')]):\n    vals=[neighborhoods.loc[(neighborhoods['left']=='lexical_lsa64') & (neighborhoods['right']==right) & (neighborhoods['exclusion']==scope) & (neighborhoods['k']==15),'mean_overlap'].iloc[0] for scope in scopes]\n    ax.bar(x+(j-.5)*.34,np.array(vals)*100,width=.34,label=label)\nax.set_xticks(x,['All other passages','Other source segments','Other meetings']);ax.set_ylim(0,100);ax.set_ylabel('Shared neighbors (%)');ax.legend(frameon=False);ax.set_title('Average agreement among 15 nearest neighbors')\nfinish(fig,'figure-2.png')\ndisplay(pd.DataFrame(read('nuisance-diagnostics.json')).round(3))"),
      md('### 3. Omitting a development meeting changes both partitions\n\nThe lexical values below are **inherited from the saved prior run**; the semantic refits were newly executed. For each omitted meeting, each result compares refitted labels against its own full-development reference on the remaining training observations. This is not prediction on omitted meetings and not use of the reserved temporal holdout.'),
      code("fig,ax=plt.subplots(figsize=(6.5,5.5))\nax.scatter(refits['saved_lexical_overlap_ari'],refits['semantic_overlap_ari'])\nax.plot([0,1],[0,1],linestyle='--',linewidth=1,label='Equal sensitivity score')\nax.set_xlim(.3,1);ax.set_ylim(.3,1);ax.set_aspect('equal',adjustable='box')\nax.set_xlabel('Saved lexical refit ARI');ax.set_ylabel('New semantic refit ARI');ax.set_title('16 paired development-meeting omissions');ax.legend(frameon=False)\nfinish(fig,'figure-3.png')\ndisplay(refits[['saved_lexical_overlap_ari','semantic_overlap_ari']].agg(['median','min','max']).round(3).rename(columns={'saved_lexical_overlap_ari':'Saved lexical ARI','semantic_overlap_ari':'Semantic ARI'},index={'median':'Median','min':'Min','max':'Max'}))"),
      md('### 4. Shared subject matter is not shared stance\n\nEach authored probe compares an anchor with a paraphrase, an opposite position on the same issue, and a different-issue statement containing diplomatic boilerplate. These eight sets are transparent stress cases, not independently sampled test data or calibrated accuracy estimates. Their text is in `results/probes-plan.json`.'),
      code("fig,ax=plt.subplots(figsize=(10,5))\ny=np.arange(len(probes))\nax.hlines(y,probes['semantic_paraphrase'],probes['semantic_opposite'],linewidth=1)\nax.scatter(probes['semantic_paraphrase'],y,marker='o',label='Same-position paraphrase')\nax.scatter(probes['semantic_opposite'],y,marker='x',label='Opposite-position statement')\nax.set_yticks(y,probes['probe'].str.title());ax.invert_yaxis();ax.set_xlim(0,1);ax.set_xlabel('Cosine similarity to anchor (not a probability)');ax.set_title('Semantic similarity remains high for opposing positions');ax.legend(frameon=False,loc='lower left')\nfinish(fig,'figure-4.png')\ndisplay(probes.drop(columns=['scope']).round(3))"),
      md('### 5. The 2-D display loses most local relationships\n\n**This is a diagnostic visualization, not a coalition map.** Its axes are the first two principal components of the normalized semantic PCA64 fitting geometry. The displayed dots did not determine the ten clusters. The low neighbor-preservation result means apparent proximity, separation and boundaries in this picture are unreliable guides to high-dimensional neighborhoods.'),
      code("with np.load(RESULTS/'strict_semantic_pca64_k10.npz',allow_pickle=False) as a:\n    xy=a['display']; labs=a['labels']\nfig,ax=plt.subplots(figsize=(9,6))\nfor label in sorted(np.unique(labs)):\n    keep=labs==label;ax.scatter(xy[keep,0],xy[keep,1],s=9,alpha=.55,label=f'S{label+1}')\nax.set_xlabel('Display PC1');ax.set_ylabel('Display PC2');ax.set_title('Diagnostic only · low nearest-neighbor retention')\nax.legend(frameon=False,bbox_to_anchor=(1.02,1),loc='upper left',title='Arbitrary fit labels')\nfinish(fig,'figure-5.png')\ndisplay(displays[['setting','neighbor_recall15','distance_spearman']].round(3))"),
      md('### 6. Inspect source-linked cross-meeting neighbors\n\nThe export provides every strict passage\'s nearest semantic neighbor from a **different meeting**, with both source IDs, text hashes, and its lexical rank. The examples below are the six largest lexical-rank discrepancies among those pairs, after removing duplicate unordered pairs. This deterministic selection highlights disagreement; it does **not** demonstrate that the semantic relationship is better. Exact texts and all pairs are retained in the CSV.'),
      code("all_examples=pd.read_csv(RESULTS/'crossmeeting-neighbors.csv')\nall_examples['pair_key']=[tuple(sorted([a,b])) for a,b in zip(all_examples.id,all_examples.neighbor_id)]\nexamples=all_examples.sort_values(['lexical_rank_of_semantic_neighbor','id'],ascending=[False,True]).drop_duplicates('pair_key').head(6)\nparts=[]\nfor _,r in examples.iterrows():\n    left=html.escape(r['text'][:450]);right=html.escape(r['neighbor_text'][:450])\n    parts.append(f\"<section class='example'><h4>Lexical rank {int(r.lexical_rank_of_semantic_neighbor):,} · semantic cosine {r.semantic_cosine:.3f}</h4><p><a href='{html.escape(r.source_url,quote=True)}' rel='noopener noreferrer'>{html.escape(r.id)}</a>: {left}…</p><p><a href='{html.escape(r.neighbor_source_url,quote=True)}' rel='noopener noreferrer'>{html.escape(r.neighbor_id)}</a>: {right}…</p></section>\")\ndisplay(HTML(''.join(parts)))"),
      md('## Takeaways and remaining work\n\nThe encoder is operational for provisional topic-related exploration. Lexical and semantic representations overlap only partly; neither is established as superior. Meeting and source composition remain important, and the authored negation probes show why semantic proximity must not become a stance label.\n\nBefore any claim of nonrandom diplomatic structure, define and calibrate nuisance-preserving reference tests, account for the settings examined, and freeze a model-specific evaluation protocol. The 37-meeting temporal holdout remains inaccessible in this phase. Human source adjudication remains deferred and can later revise the provisional population without rewriting this checkpoint.\n\n**Reproduction.** `README.md` gives model acquisition, offline fitting and notebook commands. The model lock, original checkpoint, cache, fit transforms, labels, raw numerical arrays and source-linked exports are retained. Model weights are not included in the results ZIP; download the exact pinned bytes before disconnected execution.\n\n**Primary model references:** [model card](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/tree/1110a243fdf4706b3f48f1d95db1a4f5529b4d41), [ONNX artifact](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/onnx/model.onnx). Source passages are automatic transcripts and are not independently verified official quotations.')]
    nb=nbf.v4.new_notebook(cells=cells,metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'}})
    path=root/'UN_semantic_comparison.ipynb';nbf.write(nb,path);return path

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('root',type=Path)
    print(build(parser.parse_args().root))
