#!/usr/bin/env python3
"""Real-Chromium end-to-end QA for the *draft* W3/W5/W6 browser wiring.

The published build is assembled in a disposable directory. Fixtures are
generated by W3's real Python methods and contain no UN transcript content.
"""
from __future__ import annotations

import argparse
from contextlib import contextmanager
import functools
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
import json
from pathlib import Path
import tempfile
import threading

from playwright.sync_api import sync_playwright


class Quiet(SimpleHTTPRequestHandler):
    def log_message(self, fmt, *args):
        pass


@contextmanager
def serve(directory: Path):
    server = ThreadingHTTPServer(("127.0.0.1", 0),
        functools.partial(Quiet, directory=str(directory)))
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"http://127.0.0.1:{server.server_address[1]}"
    finally:
        server.shutdown()
        thread.join(timeout=10)
        server.server_close()


FILES = ("SHA256.json","interchange-v1.json","receipt.json",
         "source-linked-edges.json","fit-geometry.json")


def choose(page, fixture_dir: Path):
    paths=[str(fixture_dir / f) for f in FILES]
    assert all(Path(p).is_file() for p in paths)
    page.locator("#research-files").set_input_files(paths)
    page.locator("#research-import").click()


def verify(browser, base: str, fixtures: Path, folder: Path,
           name: str, width: int, height: int):
    context=browser.new_context(viewport={"width":width,"height":height},
                                device_scale_factor=1,reduced_motion="reduce")
    page=context.new_page()
    errors=[]
    outside=[]
    page.on("pageerror", lambda x: errors.append(str(x)))
    page.on("request", lambda x: outside.append(x.url) if not
            x.url.startswith(base + "/") and not
            x.url.startswith("about:") and not x.url.startswith("data:") else None)
    try:
        page.goto(base+"/research.html",wait_until="load")
        assert page.locator("h1").inner_text()=="Source-bound research methods"
        assert page.get_by_text("EXPERIMENTAL · SYNTHETIC ONLY").count()==1
        assert page.locator("iframe").count()==2
        # Ensure the actual reviewed W5 and W6 assets, not just links, are
        # present in the allowlisted disposable build.
        page.locator("#w5 details").evaluate("(el)=>el.open=true")
        page.locator("#w6 details").evaluate("(el)=>el.open=true")
        assert "Research Method Lab" in page.frame_locator(
            '#w5 iframe').locator("h1").inner_text(timeout=15000)
        assert "Evidence visualization suite" in page.frame_locator(
            '#w6 iframe').locator("h1").inner_text(timeout=15000)
        for scenario,expected,assertions in [
            ("small", "Validated W3 source-bound graph",
             ["Frame 24", "eligible 24", "excluded 0"]),
            ("missing", "Validated W3 source-bound graph",
             ["Frame 25","eligible 24","excluded 1","missing 1"]),
            ("large", "display withheld above 50 nodes",
             ["WITHHELD","96 source-bound observations","No sampling performed"])
        ]:
            choose(page, fixtures/scenario)
            page.locator("#research-status").get_by_text(expected,
                exact=False).wait_for(timeout=15000)
            text=page.locator("#research-status").inner_text()+" "+page.locator(
                "#research-graph").inner_text()
            for term in assertions:
                assert term.lower() in text.lower(), (scenario,name,term,text[:300])
            if scenario=="large":
                assert page.locator("#research-graph [data-ev-inspect]").count()==0
            else:
                assert page.locator("#research-graph .ev-panel").count()==1
                assert page.locator("#research-graph [data-ev-inspect]").count()>=1
                first=page.locator("#research-graph [data-ev-inspect]").first
                first.focus()
                page.keyboard.press("Enter")
                assert "source" in page.locator("#research-graph .ev-inspector").inner_text().lower()
            if scenario=="missing":
                page.screenshot(path=str(folder/("research-"+name+"-source-complete.png")),
                                full_page=True)
        # Corrupted source-bound edge file must never produce a retained chart.
        with tempfile.TemporaryDirectory() as tmp:
            paths=[]
            for fn in FILES:
                src=fixtures/"small"/fn
                target=Path(tmp)/fn
                target.write_bytes(src.read_bytes())
                paths.append(str(target))
            with (Path(tmp)/"source-linked-edges.json").open("ab") as out:
                out.write(b" ")
            page.locator("#research-files").set_input_files(paths)
            page.locator("#research-import").click()
            page.locator("#research-status").get_by_text("Checksum mismatch",
                exact=False).wait_for(timeout=15000)
            assert page.locator("#research-graph .ev-panel").count()==0
        viewport_width=page.evaluate("document.documentElement.scrollWidth")
        assert viewport_width<=width+2, \
            f"{name} horizontal page overflow {viewport_width}>{width}"
        assert not errors, f"Uncaught script errors in {name}: {errors}"
        assert not outside, f"Unexpected external request in {name}: {outside}"
        return {
            "viewport":name,"width":width,"height":height,
            "verified_scenarios":["small","missing","large","tampered_checksum"],
            "W5_and_W6_iframes_loaded":True,"source_keyboard_inspected":True,
            "external_requests":0,"uncaught_errors":0,
            "whole_page_horizontal_overflow":False
        }
    finally:
        context.close()


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site",type=Path,required=True)
    parser.add_argument("--fixtures",type=Path,required=True)
    parser.add_argument("--browser",type=Path,required=True)
    parser.add_argument("--output",type=Path,required=True)
    args=parser.parse_args()
    assert args.site.is_dir() and args.fixtures.is_dir() and args.browser.is_file()
    output=args.output.resolve()
    output.mkdir(parents=True,exist_ok=True)
    with serve(args.site) as base,sync_playwright() as pw:
        browser=pw.chromium.launch(headless=True,executable_path=str(
            args.browser.resolve()),args=["--no-sandbox","--disable-dev-shm-usage"])
        try:
            viewports=[verify(browser,base,args.fixtures,output,n,w,h)
                       for n,w,h in [("desktop",1440,900),("mobile",390,844)]]
        finally:
            browser.close()
    result={"schema":"un.coordinator.synthetic-research-browser-qa.v1",
            "publication_eligible":False,"heldout_transcripts_opened":0,
            "viewports":viewports,
            "limitations":"Synthetic only; no private UN corpus or real source inference; no deployment."}
    (output/"browser-qa.json").write_text(json.dumps(result,indent=2)+"\n",
                                          encoding="utf8")
    print("PASS: native W3 source-bound synthetic graph import and W5/W6 browser integration, "
          "desktop and mobile, no external requests.")


if __name__=="__main__":
    main()
