"""Create an offline visual review pack from an existing, validated public replay."""
from pathlib import Path
import argparse, csv, hashlib, html, json, shutil

def build(run, out):
    qa=json.loads((run/'validation.json').read_text(encoding='utf-8'))
    if not qa.get('passed'): raise ValueError('Use a validated run')
    out.mkdir(parents=True,exist_ok=True)
    for source,target in [('daily_briefing_preview.html','readout.html'),('daily_briefing.eml','readout.eml'),('figures/USUN_Seal.png','seal.png')]:
        shutil.copyfile(run/source,out/target)
    figures=[('Figure_1_Issue_Frequency.png','Issue evidence','Counts use the inherited and provisional replay codebook; they are not human-validated relevance estimates.'),
        ('Figure_4_Country_Discourse_Map.png','Country language map','PCA failed release checks on this replay. Audit-only lexical geometry; proximity is not political alignment.'),
        ('Figure_6_Hierarchical_Clustering_Audit.png','Grouping diagnostics','Quality-withheld. Group labels have no geopolitical meaning.'),
        ('Figure_7_PAM_Clustering_Audit.png','Exemplar diagnostics','Quality-withheld. Medoids are textual exemplars, not representative political positions.')]
    cards=[]
    for i,(source,title,note) in enumerate(figures,1):
        name=f'chart{i}.png';shutil.copyfile(run/'audit/figures'/source,out/name)
        cards.append(f'<article><div class="eyebrow">RESEARCH VIEW {i:02d} · AUDIT ONLY</div><h2>{title}</h2><p>{note}</p><a href="{name}"><img src="{name}" alt="{html.escape(title+": "+note)}"></a></article>')
    ledger=list(csv.DictReader((run/'audit/analytics/method_ledger.csv').open(encoding='utf-8-sig')))
    labels={'withheld_quality':'Withheld: quality checks','executed':'Computed · audit only','blocked_data':'Blocked: data requirements'}
    states=''.join(f'<tr><td>{r["method_id"]}</td><td>{html.escape("Lexical network (stance layer unavailable)" if r["method_id"]=="M31" else r["method"])}</td><td>{html.escape(labels.get(r["terminal_status"],r["terminal_status"]))}</td></tr>' for r in ledger if r['method_id'] in ['M08','M31','M32','M33','M34','M36'])
    page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>UN Transcript Agent — visual review</title>
<style>:root{--navy:#062135;--blue:#002d74;--red:#d01319;--ink:#202b38;--rule:#d6dee7;--space:32px;--font:16px}*{box-sizing:border-box}body{margin:0;background:white;color:var(--ink);font:var(--font)/1.5 Arial,Helvetica,sans-serif}header{background:var(--navy);color:white;border-bottom:4px solid var(--red);padding:25px 4vw;display:flex;align-items:center;gap:20px}header img{width:68px;height:68px;object-fit:contain}header strong{font:24px Georgia,serif}header small{display:block;letter-spacing:.09em;margin-top:4px}header .status{margin-left:auto;font-size:12px;text-align:right}main{max-width:1440px;margin:auto;padding:var(--space) 4vw}h1{font:36px/1.2 Georgia,serif;color:var(--navy);margin:8px 0 15px}h2{font:24px Georgia,serif;color:var(--blue);margin:7px 0}p{margin:8px 0 18px}.eyebrow{font-size:11px;letter-spacing:.12em;font-weight:bold;color:var(--blue)}.meta{color:#526171;font-size:14px}.takeaway{background:#e7f1f8;border-left:4px solid var(--blue);padding:16px 20px;margin:22px 0}.actions{display:flex;flex-wrap:wrap;gap:12px;margin:18px 0}.actions a,button{border:1px solid var(--blue);color:var(--blue);background:white;padding:10px 16px;text-decoration:none;border-radius:3px;font:inherit;cursor:pointer}.actions a:first-child{background:var(--blue);color:white}.toolbar{display:flex;flex-wrap:wrap;gap:20px;align-items:end;background:#f6f8fa;padding:20px;border:1px solid var(--rule);margin:25px 0}label{display:flex;flex-direction:column;font-size:13px;gap:7px}select,input{font:inherit;min-height:36px}.charts{display:grid;grid-template-columns:1fr 1fr;gap:var(--space)}article{min-width:0;border-top:2px solid var(--blue);padding-top:18px}article p{font-size:14px;min-height:44px}article img{display:block;width:100%;height:auto;border:1px solid var(--rule)}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--rule)}th{background:#eef4f9}footer{background:#f6f8fa;padding:24px 4vw;border-top:1px solid #c1a783;font-size:13px}a{color:var(--blue)}:focus-visible{outline:3px solid #d01319;outline-offset:3px}#feedback{width:100%;min-height:95px;font:inherit;padding:12px}#notice{min-height:24px;font-size:13px}@media(max-width:720px){header{padding:20px;gap:12px}header strong{font-size:20px}header img{width:50px;height:50px}header .status{display:none}main{padding:24px 20px}h1{font-size:30px}.charts{grid-template-columns:1fr}article p{min-height:0}.toolbar{gap:14px}.toolbar>*{max-width:100%}}@media print{.toolbar,.actions,.feedback{display:none}.charts{display:block}article{break-inside:avoid;margin-bottom:24px}}</style>
<header><img src="seal.png" alt="Approved USUN seal"><div><strong>UN Transcript Agent</strong><small>VISUAL REVIEW · WORKING EXAMPLE</small></div><div class="status">INTERNAL | NON-FINAL<br>Archived replay · not today's briefing</div></header>
<main><div class="eyebrow">DESIGN REVIEW / 01</div><h1>A briefing you can refine</h1><p class="meta">23 September 2026 source replay · 39 country statements · 42 method records · five analytical slots</p>
<div class="takeaway"><strong>Review the design, with the evidence boundary visible.</strong><br>The actual draft is linked below. This separate gallery exposes withheld research charts for visual review. It does not add them to the released email or turn them into validated findings.</div>
<div class="actions"><a href="readout.html">Open actual readout ↗</a><a href="readout.eml" download>Download unsent email</a><a href="#review">Record visual refinements ↓</a></div>
<div class="toolbar" aria-label="Preview appearance"><label>Spacing<select id="spacing"><option value="32px">Comfortable</option><option value="20px">Compact</option><option value="44px">Airy</option></select></label><label>Body size<select id="size"><option value="16px">Standard · 16 px</option><option value="18px">Larger · 18 px</option></select></label><label>Section blue<input id="blue" type="color" value="#002d74"></label><button id="reset">Reset preview</button><span class="meta">Controls affect this gallery; saved email and chart pixels stay unchanged.</span></div>
<div class="charts">CARDS</div><section style="margin-top:36px"><h2>What the new methods actually returned</h2><p class="meta">All six additions remain audit-only. The table distinguishes computed outputs from blocked and quality-withheld results.</p><div class="table"><table><thead><tr><th>ID</th><th>Method</th><th>Replay state</th></tr></thead><tbody>STATES</tbody></table></div></section>
<section class="feedback" id="review" style="margin-top:36px"><h2>Your visual refinements</h2><p>Describe changes to the masthead, colours, icons, typography, chart labels, layout or amount of detail. This page does not submit anything.</p><label for="feedback">Review notes</label><textarea id="feedback" placeholder="For example: larger country labels; smaller seal; put the country map first…"></textarea><div class="actions"><button id="export">Save review notes</button></div><p id="notice" role="status"></p></section></main><footer>Source: included 23 September replay. Rendered from the validated I5 run; chart conclusions remain withheld. No email has been sent. Source hashes are recorded in <a href="provenance.json">provenance.json</a>.</footer>
<script>const root=document.documentElement;function update(){root.style.setProperty('--space',spacing.value);root.style.setProperty('--font',size.value);root.style.setProperty('--blue',blue.value)}const spacing=document.querySelector('#spacing'),size=document.querySelector('#size'),blue=document.querySelector('#blue');[spacing,size,blue].forEach(x=>x.addEventListener('input',update));document.querySelector('#reset').onclick=()=>{spacing.value='32px';size.value='16px';blue.value='#002d74';update()};document.querySelector('#export').onclick=()=>{const data={spacing:spacing.value,bodySize:size.value,sectionBlue:blue.value,notes:document.querySelector('#feedback').value};const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='visual-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#notice').textContent='Review notes downloaded. Share the file or paste your notes in the chat.'};</script></html>'''
    (out/'index.html').write_bytes(page.replace('CARDS',''.join(cards)).replace('STATES',states).encode())
    hashes={f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in out.iterdir() if f.is_file() and f.name!='provenance.json'}
    (out/'provenance.json').write_bytes((json.dumps({'source':'Included 2026-09-23 public replay; I5 validated run','countries':39,'audit_only_charts':True,'files':hashes},indent=2)+'\n').encode())

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('run',type=Path);p.add_argument('out',type=Path);a=p.parse_args();build(a.run,a.out)
