const fs=require('node:fs'),V=require('../site/nmf-view.js');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const names={full:'Complete corpus',substantive:'Reviewed substantive subset',inclusive:'Including mixed remarks and fragment'};
const shortNames={full:'Complete corpus',substantive:'Substantive subset',inclusive:'Mixed / fragment added'};
const [input,output]=process.argv.slice(2);if(!output)throw Error('Supply comparison JSON and HTML destination.');
if(require('node:path').resolve(input).toLowerCase()===require('node:path').resolve(output).toLowerCase())throw Error('Keep comparison data and rendered report separate.');
const d=JSON.parse(fs.readFileSync(input)),six=Object.entries(d.policies).map(([key,p])=>({key,fit:p.fits.find(f=>f.parameters.components===6)}));
const rows=Object.entries(d.policies).flatMap(([key,p])=>p.fits.map(f=>[names[key],f.parameters.components,f.usable_count,f.diagnostics.relative_residual.toFixed(3),(100*f.diagnostics.squared_reconstruction_fraction).toFixed(1)+'%',f.diagnostics.converged?'Yes':'No']));
const settings=`<p class="hint">${esc(d.protocol)}</p>`;
const diagnostic=table(['Inclusion','Components','Usable','Relative residual','Squared magnitude captured','Stopping rule met'],rows);
const stability=table(['Inclusion','Fitted / attempted','Converged','Distinct samples','Mean aligned cosine','Converged-only cosine','Mixture L1'],six.map(({key,fit})=>{const s=fit.stability;return [names[key],s.successful+'/'+s.attempted,s.converged,s.unique_group_samples,s.cosine.mean.toFixed(3),s.converged_cosine.mean?.toFixed(3)??'Not assessed',s.mixture_l1.mean.toFixed(3)];}));
const comparison=table(['Refitted subset','Shared passages','Aligned cosine to full fit','Mixture L1 difference'],d.comparisons.map(c=>[names[c.policy],c.shared_passages,c.mean_cosine.toFixed(3),c.mean_mixture_l1.toFixed(3)]));
const body=`<header><p>UN Transcript Agent · September 22–28, 2026</p><h1>Which patterns persist when procedure is removed?</h1><p>Reviewed passage types and overlapping NMF components.</p><a href="./#analyze">Open analysis workspace</a> · <a href="passage-audit.html">Clustering comparison</a></header>
<p class="warning">${d.human_confirmed} explicit passage-type decisions by one reviewer. Component interpretations have not been reviewed. Source audio and transcript accuracy remain unverified.</p>
<section><h2>Read the comparison</h2><p>Each fit starts from its own nonnegative TF-IDF matrix. Components can overlap within a passage. Procedure-related terms can account for prominent components in the complete collection, while the substantive subset changes the fitted vocabulary and mixture structure.</p><p>Component numbers are local to each fit. Compare source passages before assigning names. Neither term similarity nor reconstruction establishes policy agreement.</p>${settings}</section>
<section><h2>Component-count sensitivity</h2>${diagnostic}<p class="hint">Lower in-sample residual often follows a larger component count. These three settings do not identify an optimal count, and comparisons across inclusion policies change the input matrix. No component count was selected from these results.</p></section>
<section><h2>Whole-meeting sensitivity at six components</h2>${stability}<p class="hint">Six source meetings produce only six distinct omissions at this sampling fraction. Thirty seeded refits also vary initialization; they are not thirty independent meetings. Cosine ranges from 0 to 1, mixture L1 from 0 to 2. Summary means include all fitted samples; convergence coverage is shown separately.</p>${V.bars('Mean component cosine after whole-meeting refitting',six,c=>shortNames[c.key],c=>c.fit.stability.cosine.mean)}</section>
<section><h2>Full fit versus independently refitted subsets</h2>${comparison}<p class="hint">One-to-one component alignment uses full-vocabulary term weights, with absent terms set to zero. Different numbers of passages, vocabulary, IDF and optimization can all change the fit; this does not isolate the causal effect of removing procedure.</p></section>
${six.map(({key,fit})=>`<section><h2>${esc(names[key])}</h2>${V.render(fit,d.sources,table)}${d.policies[key].fits.filter(f=>f.parameters.components!==6).map(f=>`<details><summary>Compare ${f.parameters.components} components and their sources</summary>${V.render(f,d.sources,table)}</details>`).join('')}</section>`).join('')}
<section><h2>Evidence and next steps</h2><p>Review the highest-loading sources, inspect competing starting points and compare four, six and eight components before naming any pattern. Keep replies separate for questions about exchanges between delegations.</p><p><a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/NMF.md">Method and validation</a> · <a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/nmf-comparison.json">Comparison data and source IDs</a> · <a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/passage-type-reviewed-mask.json">Reviewed passage mask</a></p><p class="hint">Original collection SHA-256: <code>${d.corpus_sha256}</code><br>Reviewed mask SHA-256: <code>${d.mask_sha256}</code><br>${esc(d.engine)}. Original text and the earlier provisional comparison are preserved.</p></section>`;
fs.writeFileSync(output,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NMF comparison · UN Transcript Agent</title><link rel="stylesheet" href="analysis.css"><style>body{margin:0;background:#f2f5f7;color:#152c43;font:16px/1.65 Arial,sans-serif}main{max-width:1160px;margin:auto;padding:28px}header{border-bottom:3px solid #b1242e;padding-bottom:16px}h1,h2,h3{font-family:Georgia,serif;line-height:1.2}h1{font-size:36px}h2{font-size:26px}section{background:white;border:1px solid #d6dfe6;padding:24px;margin:24px 0}section section{border:0;margin:0;padding:0}a{color:#002d74}.warning{padding:16px;border-left:3px solid #b1242e;background:#fff2ed}.hint,small{font-size:14px;color:#536577}summary{cursor:pointer;font-weight:bold}details{padding:12px 0;border-bottom:1px solid #d6dfe6}li,code{overflow-wrap:anywhere}.chart-wrap,.table-wrap{overflow-x:auto}svg{min-width:850px;width:100%;height:auto}svg text{fill:#152c43;font:14px Arial,sans-serif}td,th{padding:9px;text-align:left;border-bottom:1px solid #d4dee5}table{border-collapse:collapse;width:100%;font-size:14px}blockquote{margin:10px 0;padding:8px 14px;border-left:2px solid #ccd6df}@media(max-width:600px){main{padding:16px}section{padding:16px}h1{font-size:29px}}@media print{body{background:white}main{max-width:none;padding:0}svg{min-width:0}section{break-inside:avoid}}</style></head><body><main>${body}</main></body></html>`);
console.log('Rendered NMF comparison with source links and no embedded transcript text.');
