const fs=require('node:fs'),path=require('node:path'),V=require('../site/gmm-view.js');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v===null||v===undefined?'Not assessed':v.toFixed(3);
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const names={full:'Complete corpus',substantive:'Reviewed substantive subset',inclusive:'Including mixed remarks and fragment'};
const short={full:'Complete',substantive:'Substantive',inclusive:'Broader subset'};
const [input,output]=process.argv.slice(2);if(!output||path.resolve(input).toLowerCase()===path.resolve(output).toLowerCase())throw Error('Use separate comparison JSON and output HTML paths.');
const d=JSON.parse(fs.readFileSync(input)),sources=new Map(d.sources.map(r=>[r.id,r]));
const all=Object.entries(d.policies).flatMap(([policy,p])=>p.fits.map(f=>({policy,...f})));
function chart(){
 const valid=all.filter(f=>!f.skipped&&f.stability.soft_membership.mean_total_variation.mean!==null),height=45+valid.length*34;
 return `<div class="chart-wrap"><svg viewBox="0 0 930 ${height}" role="img" aria-label="Mean aligned membership change after whole-meeting refits"><title>Mean total variation; zero to one, lower is more consistent</title>${valid.map((f,i)=>{const y=12+i*34,v=f.stability.soft_membership.mean_total_variation.mean;return `<text x="0" y="${y+17}">${esc(short[f.policy]+' · '+f.representation.toUpperCase()+' · '+f.gmm.covariance_type)}</text><rect x="325" y="${y}" width="${v*460}" height="22" fill="${f.gmm.covariance_type==='diag'?'#002d74':'#82704c'}"/><text x="805" y="${y+17}">${num(v)}</text>`;}).join('')}<text x="325" y="${height-2}">0</text><text x="785" y="${height-2}" text-anchor="end">1</text></svg></div>`;
}
const comparisonRows=all.map(f=>f.skipped?[names[f.policy],f.representation.toUpperCase(),f.skipped]:[names[f.policy],f.representation.toUpperCase(),f.gmm.covariance_type,f.analyzed_count,f.gmm.hard_counts.join(', '),f.gmm.ambiguous_count,num(f.gmm.mean_entropy),num(f.stability.ari?.mean),num(f.stability.soft_membership.mean_total_variation.mean),f.stability.successful+'/'+f.stability.attempted]);
const grid=Object.entries(d.policies).map(([policy,p])=>`<details><summary>${esc(names[policy])} · component count and regularization</summary>${['pca','lsa'].map(rep=>`<h3>${rep.toUpperCase()} · one fixed input matrix</h3>${table(['Covariance','Regularization','Components','Dimensions','Parameters','AIC','BIC','Hard sizes','Ambiguous','Converged starts'],p.grid.filter(r=>r.representation===rep).map(r=>r.skipped?[r.covariance,r.regularization,r.k,r.dimensions,r.skipped]:[r.covariance,r.regularization,r.k,r.dimensions,r.parameter_count,num(r.aic),num(r.bic),r.sizes.join(', '),r.ambiguous,r.converged_starts+'/5']))}`).join('')}</details>`).join('');
const details=all.map(f=>f.skipped?`<p>${esc(f.skipped)}</p>`:`<details class="mixture-fit"><summary>${esc(names[f.policy])} · ${f.representation.toUpperCase()} · ${f.gmm.covariance_type}</summary>${V.render(f,d.sources,table)}<h3>Component terms and high-membership sources</h3><p class="hint">Terms are weighted by memberships. Examples rank by membership, with original source order breaking ties; they do not establish a common stance.</p>${f.clusters.map(c=>`<details><summary>Component ${c.cluster} · ${esc(c.terms.map(t=>t.term).join(', '))}</summary><ul>${c.sources.map(p=>{const r=sources.get(p.id);return `<li><a href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer">${esc(r.country+' · '+r.date)}</a> · ${num(p.membership)} · ${esc(r.id)}</li>`;}).join('')}</ul></details>`).join('')}</details>`).join('');
const body=`<header><p>UN Transcript Agent · September 22–28, 2026</p><h1>How stable are overlapping passage memberships?</h1><p>Regularized Gaussian mixtures on the same PCA and LSA representations.</p><a href="./#analyze">Open analysis workspace</a> · <a href="passage-audit.html">Reviewed passage comparison</a> · <a href="nmf-audit.html">NMF comparison</a></header>
<p class="warning">${d.human_confirmed} passage types were confirmed by one reviewer. Mixture memberships and component meanings are not reviewed categories. A high membership can change substantially after source groups are omitted.</p>
<section><h2>Fixed comparison</h2><p>${esc(d.protocol)}</p><p>The 194-passage substantive subset and 198-passage broader subset retain their original text. Two zero-term passages are excluded separately from the complete corpus, leaving 458 usable passages.</p></section>
<section><h2>Membership sensitivity</h2>${chart()}<p class="hint">Mean total variation compares aligned membership vectors on shared passage IDs. Zero means unchanged; one means disjoint memberships. All six source meetings are resampled as whole groups. Thirty repeats use only six distinct omissions and also vary initialization.</p></section>
<section><h2>Within-fit certainty and refit stability</h2>${table(['Inclusion','Representation','Covariance','Usable','Hard sizes','Max membership <0.6','Mean entropy','Hard ARI','Mean soft TV','Fitted refits'],comparisonRows)}<p class="hint">Four components, regularization 0.0001. Hard counts use the largest membership. Entropy measures spread within the fitted model, while refit ARI and total variation measure sensitivity. Low entropy does not establish a stable or accurate thematic interpretation.</p></section>
<section><h2>Component-count and regularization checks</h2><p class="warning">Compare information criteria only within a single inclusion policy and representation at fixed dimensions. Regularization, local optima and dependent passages limit formal AIC/BIC claims. These tables do not select a winning model or justify comparisons across PCA/LSA or subsets.</p>${grid}</section>
<section><h2>Full fit versus separately refitted subsets</h2>${table(['Subset','Representation','Covariance','Shared','Hard ARI','Mean soft TV'],d.full_subset_comparisons.map(c=>[names[c.policy],c.representation.toUpperCase(),c.covariance,c.shared_passages,num(c.hard_ari),num(c.soft_agreement.mean_total_variation)]))}<p class="hint">Refitting changes the population, vocabulary, IDF and retained representation together. ARI is withheld where fewer than two highest-membership groups occur in either shared set. Component alignment uses memberships on shared IDs, not means in different coordinate systems.</p></section>
<section><h2>Inspect memberships and sources</h2>${details}</section>
<section><h2>Evidence and next steps</h2><p>Inspect passages with large membership changes, compare covariance and variance-floor settings, and check full source context before naming components. Additional independent meetings are needed before stronger stability claims.</p><p><a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/GMM.md">Method and validation</a> · <a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/gmm-comparison.json">Comparison data</a> · <a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/passage-type-reviewed-mask.json">Reviewed inclusion mask</a></p><p class="hint">Original collection: <code>${d.corpus_sha256}</code><br>Reviewed mask: <code>${d.mask_sha256}</code><br>${esc(d.engine)}. Source audio and factual content are not authenticated. No new transcript text is embedded in this public report.</p></section>`;
fs.writeFileSync(output,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gaussian mixture comparison · UN Transcript Agent</title><link rel="stylesheet" href="analysis.css"><style>body{margin:0;background:#f2f5f7;color:#152c43;font:16px/1.65 Arial,sans-serif}main{max-width:1160px;margin:auto;padding:28px}header{border-bottom:3px solid #b1242e;padding-bottom:16px}h1,h2,h3{font-family:Georgia,serif;line-height:1.2}h1{font-size:36px}h2{font-size:26px}section{background:white;border:1px solid #d6dfe6;padding:24px;margin:24px 0}section section{border:0;margin:0;padding:0}a{color:#002d74}.warning{padding:16px;border-left:3px solid #b1242e;background:#fff2ed}.hint,.method-note,small{font-size:14px;color:#536577}summary{cursor:pointer;font-weight:bold}details{padding:12px 0;border-bottom:1px solid #d6dfe6}li,code{overflow-wrap:anywhere}.chart-wrap,.table-wrap{overflow-x:auto}svg{min-width:850px;width:100%;height:auto}svg text{fill:#152c43;font:14px Arial,sans-serif}.cluster-legend svg{min-width:0;width:14px}td,th{padding:9px;text-align:left;border-bottom:1px solid #d4dee5}table{border-collapse:collapse;width:100%;font-size:14px}@media(max-width:600px){main{padding:16px}section{padding:16px}h1{font-size:29px}}@media print{body{background:white}main{max-width:none;padding:0}svg{min-width:0}section{break-inside:avoid}}</style></head><body><main>${body.replace(/[ \t]+$/gm, '')}</main></body></html>`);
console.log('Rendered source-linked GMM comparison.');
