const fs=require('node:fs'),path=require('node:path'),V=require('../site/mds-view.js');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>v===null||v===undefined?'Not assessed':v.toFixed(3),range=values=>n(Math.min(...values))+'–'+n(Math.max(...values));
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const names={full:'Complete corpus',substantive:'Substantive subset',inclusive:'Broader subset'};
const [directory,output]=process.argv.slice(2),read=name=>JSON.parse(fs.readFileSync(path.join(directory,name)));
const u=read('umap.json'),m=read('mds.json'),old=read('mds-300.json'),inspection=read('inspection.json'),records=inspection.rankings.full;
function sensitivity(f){
 const colors=['#002d74','#82704c','#b13d34'],x=v=>70+430*(v-5)/45,y=v=>320-260*v;
 return `<div class="chart-wrap"><svg viewBox="0 0 580 405" role="img" aria-label="${f.representation.toUpperCase()} substantive UMAP ten-neighbor preservation by setting"><title>UMAP: overlap with ten nearest retained-score neighbors, by neighborhood setting and seed</title>
 ${[0,.25,.5,.75,1].map(v=>`<path d="M 70 ${y(v)} H 500" stroke="#d8dfe6"/><text x="55" y="${y(v)+5}" text-anchor="end">${v}</text>`).join('')}
 ${u.protocol.seeds.map((seed,i)=>{const runs=f.runs.filter(r=>r.seed===seed);return `<polyline points="${runs.map(r=>x(r.neighbors)+','+y(r.fidelity.neighbor_overlap)).join(' ')}" fill="none" stroke="${colors[i]}" stroke-width="2" stroke-dasharray="${i===1?'6 4':i===2?'2 4':'none'}"/>${runs.map(r=>`<circle cx="${x(r.neighbors)}" cy="${y(r.fidelity.neighbor_overlap)}" r="4" fill="${colors[i]}"><title>Seed ${seed}, ${r.neighbors} neighbors: ${n(r.fidelity.neighbor_overlap)}</title></circle>`).join('')}<line x1="${70+i*160}" x2="${100+i*160}" y1="391" y2="391" stroke="${colors[i]}" stroke-width="2" stroke-dasharray="${i===1?'6 4':i===2?'2 4':'none'}"/><text x="${108+i*160}" y="397">Seed ${seed}</text>`;}).join('')}
 ${u.protocol.neighbors.map(v=>`<text x="${x(v)}" y="343" text-anchor="middle">${v}</text>`).join('')}<text x="285" y="370" text-anchor="middle">UMAP neighborhood setting</text><text x="18" y="190" transform="rotate(-90 18 190)" text-anchor="middle">Ten-neighbor overlap (0–1)</text></svg></div>`;
}
const summary=table(['Inclusion','Representation','UMAP neighbor overlap','MDS neighbor overlap','UMAP distance error','MDS distance error'],u.fits.map(f=>{const d=m.fits.find(d=>d.policy===f.policy&&d.representation===f.representation);return [names[f.policy],f.representation.toUpperCase(),range(f.runs.map(r=>r.fidelity.neighbor_overlap)),n(d.fidelity.neighbor_overlap),range(f.runs.map(r=>r.relative_distance_error)),n(d.scale_adjusted.relative_distance_error)];}));
const sourceSections=Object.entries(inspection.rankings).map(([policy,rows])=>`<h3>${names[policy]}</h3>${rows.slice(0,5).map(r=>{const note=inspection.inspected.find(p=>p.id===r.id);return `<details class="inspection-source"><summary>${esc(r.country)} · mean membership change ${n(r.mean_tv_across_four_models)}</summary><p>${esc(note.inspection_note)}</p><p class="hint">${esc(r.reviewed_type)} · ${r.words} whitespace-delimited words · ${esc(r.id)}</p>${table(['Representation','Covariance','Times sampled','Mean TV','Original max membership'],r.models.map(p=>[p.representation.toUpperCase(),p.covariance,p.sampled_refits,n(p.mean_tv),n(p.reference_max_membership)]))}<a href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer">Open original source · ${esc(r.date)}</a></details>`;}).join('')}`).join('');
const details=u.fits.map(f=>`<details><summary>${names[f.policy]} · ${f.representation.toUpperCase()} · ${f.passages} passages</summary>${table(['Neighbors','Seed','Overlap','Trustworthiness','Continuity','Distance error','Overlap with default display'],f.runs.map(r=>[r.neighbors,r.seed,n(r.fidelity.neighbor_overlap),n(r.fidelity.trustworthiness),n(r.fidelity.continuity),n(r.relative_distance_error),n(r.reference_layout_overlap)]))}${table(['Neighbors','Seed-pair overlap range'],u.protocol.neighbors.map(k=>[k,range(f.seed_comparisons.filter(r=>r.neighbors===k).map(r=>r.overlap))]))}<p class="hint">Fixed score/membership state: <code>${f.frozen_state_sha256}</code>. No clustering was rerun.</p></details>`).join('');
const maps=u.fits.filter(f=>f.policy==='substantive').map(f=>{const d=m.fits.find(d=>d.policy===f.policy&&d.representation===f.representation);return `<details class="map-comparison"><summary>Inspect substantive ${f.representation.toUpperCase()} maps</summary><p>All panels use the same saved diagonal-mixture highest-membership colors. Source identities are fixed. Component numbers are local to each representation and do not match across PCA and LSA. Bounds and orientation differ between panels; UMAP units are arbitrary. Compare neighbors and the diagnostics rather than apparent gaps.</p><div class="maps">${f.runs.filter(r=>r.neighbors===15).map(r=>`<div><h4>UMAP · 15 neighbors · seed ${r.seed}</h4>${V.scatter(f.ids.map((id,i)=>({id,cluster:f.labels[i],umap:r.coordinates[i]})),records,'umap','UMAP seed '+r.seed)}</div>`).join('')}<div><h4>Metric MDS · selected seed ${d.seed}</h4>${V.scatter(f.ids.map((id,i)=>({id,cluster:f.labels[i],mds:d.coordinates[i]})),records)}</div></div></details>`;}).join('');
const convergence=table(['Inclusion','Representation','300-step selection converged','Final selected iterations','Final raw stress','Relative error','Converged starts'],m.fits.map((d,i)=>[names[d.policy],d.representation.toUpperCase(),old.fits[i].converged?'Yes':'No',d.iterations,n(d.stress),n(d.relative_distance_error),d.runs.filter(r=>r.converged).length+'/'+d.runs.length]));
const body=`<header><p>UN Transcript Agent · September 22–28, 2026</p><h1>Membership changes and display sensitivity</h1><p>Source inspection, 72 UMAP layouts and metric MDS on frozen representations.</p><a href="./#analyze">Open analysis workspace</a> · <a href="gmm-audit.html">Mixture comparison</a></header>
<section><h2>What the checks show</h2><p>The full-corpus inspection leads are short chair introductions, including one already reviewed as a suspected transcription issue. The substantive examples cover several issues within individual addresses. Adding four mixed or fragment records changes the leading inspection list. None of these observations establishes a changed diplomatic position.</p><p>UMAP preserved more local neighbors in this grid. Metric MDS preserved overall pairwise distances better after allowing one uniform scale adjustment for each layout. Neither display validates a theme or political relationship.</p><p class="warning">The 460 saved passage-type decisions remain unchanged. These are analyst observations about cached text and numerical sensitivity, not additional human labels or audio authentication. The corpus still contains only six meeting assets.</p></section>
<section id="sources"><h2>Passages with the largest membership changes</h2><p>Five passages per inclusion policy, ranked by the equal-weight average of mean total variation across the four PCA/LSA and diagonal/spherical mixture fits. Each per-passage mean uses its successful sampled refits. This is an inspection ranking, not a significance test. The 15 selected source segments were inspected; all originals and reviewed types remain intact.</p>${sourceSections}</section>
<section id="umap"><h2>UMAP neighborhood sensitivity</h2><p>For each of six frozen score matrices: seeds 7, 42 and 2026; neighborhood settings 5, 15, 30 and 50; minimum distance 0.1; 300 epochs. Evaluation always uses ten nearest neighbors. The reference setting reproduced the prior coordinates exactly, and every fitted membership remained unchanged.</p><div class="maps">${u.fits.filter(f=>f.policy==='substantive').map(f=>`<div><h3>Substantive ${f.representation.toUpperCase()}</h3>${sensitivity(f)}</div>`).join('')}</div><p class="hint">Higher overlap preserves more local geometry. The lines connect tested settings; three seeds do not define an uncertainty interval. Seed-pair overlap compares displayed neighbors with each other, separately from preservation of retained-score neighbors.</p><p class="hint">A separate browser-versus-Node check reproduced assignments and nearly identical scores, but different UMAP layouts at the same seed. Preserve exported coordinates for exact reproduction. Within the same browser, enabling MDS left scores, memberships, UMAP and grouped-refit results unchanged.</p>${details}</section>
<section id="comparison"><h2>Local neighbors and overall distances</h2>${summary}<p class="hint">UMAP entries span all twelve tested layouts per input; MDS entries use the lowest-stress start. Distance error is the root squared distance residual divided by target-distance norm, after a best uniform scale adjustment. All unordered pairs count equally, including zero target distances. Lower error fits distances better; higher neighbor overlap preserves more local structure. Compare methods within a row; different inclusion policies change the population.</p>${maps}</section>
<section id="mds"><h2>Metric MDS stopping checks</h2><p>Metric SMACOF uses three seeded starts and equal weight for every pairwise Euclidean distance in the retained 20-dimensional scores. Four of the six 300-iteration selections were unfinished. The 1,000-iteration limit allowed all selected layouts to meet the stopping rule; initialization still affects the local solution. The workspace discloses iteration-limited displays if other inputs or settings do not converge.</p>${convergence}<details><summary>Substantive PCA distance plot</summary>${V.shepard(m.fits.find(f=>f.policy==='substantive'&&f.representation==='pca'))}<p class="hint">All 18,721 unordered pairs enter twenty equal-width target-distance bins. Dots show means; lines show observed ranges, not confidence intervals.</p></details></section>
<section><h2>Use and next steps</h2><p>Use the maps to locate sources for inspection. Check the recorded transcription concerns against audio before correcting text. For issue-specific grouping, the next useful experiment is a separately recorded within-speech segmentation pilot with parent IDs and offsets; it should preserve these full-segment results as the baseline. Additional independent meetings remain necessary before stronger stability claims.</p><p><a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/DISPLAY_AUDIT.md">Method, source notes and validation</a> · <a href="https://github.com/LystadJS/UNGA81-Transcript-Agent/blob/main/docs/display-comparison.json">Layout comparison data</a></p><p class="hint">Original corpus SHA-256: <code>${inspection.corpus_sha256}</code>. No new transcript text is embedded in this public page.</p></section>`;
fs.writeFileSync(output,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Membership and display sensitivity · UN Transcript Agent</title><link rel="stylesheet" href="analysis.css"><style>body{margin:0;background:#f2f5f7;color:#152c43;font:16px/1.65 Arial,sans-serif}main{max-width:1160px;margin:auto;padding:28px}header{border-bottom:3px solid #b1242e;padding-bottom:16px}h1,h2,h3{font-family:Georgia,serif;line-height:1.2}h1{font-size:36px}section{background:white;border:1px solid #d6dfe6;padding:24px;margin:24px 0}a{color:#002d74}.warning{padding:16px;border-left:3px solid #b1242e;background:#fff2ed}.hint{font-size:14px;color:#536577}summary{cursor:pointer;font-weight:bold}details{padding:12px 0;border-bottom:1px solid #d6dfe6}code{overflow-wrap:anywhere}.table-wrap{overflow:auto}td,th{padding:9px;text-align:left;border-bottom:1px solid #d4dee5}table{border-collapse:collapse;width:100%;font-size:14px}.maps{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:20px}.maps>div{min-width:0}.chart-wrap svg{min-width:460px;width:100%;height:auto}.chart-wrap{max-width:100%;overflow:auto}svg text{font:15px Arial;fill:#152c43}.cluster-map svg{width:100%;height:auto}@media(max-width:700px){main{padding:16px}section{padding:16px}h1{font-size:29px}.maps{grid-template-columns:1fr}}@media print{main{max-width:none;padding:0}section{break-inside:avoid}.chart-wrap svg{min-width:0}}</style></head><body><main>${body.replace(/[ \t]+$/gm,'')}</main></body></html>`);
console.log('Rendered membership, UMAP and MDS audit.');
