'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const C = require('../research/corpus/contract.cjs'), B = require('../research/corpus/boundary-review.js');
const G = require('./boundary_packet.cjs'), fixture = require('./boundary_fixture.cjs');
const tests = [], test = (name,run) => tests.push({name,run}), copy = B.clone;
const corpus = fixture(), packet = G.model(corpus).packet, seed = B.seed(packet);
const confirmed = (index=0) => ({...seed.choices[index], confirmed:true, type:'substantive_speech', extent:'complete',
  speech_id:'SYNTHETIC-speech-'+index, reviewer:'SYNTHETIC TEST — NOT OWNER REVIEW', reviewed_at:'2020-01-04T00:00:00Z'});
const withChoice = c => ({...copy(seed),choices:[c]});
const temp = fs.mkdtempSync(path.join(os.tmpdir(),'un-boundary-test-'));
let built;
test('all development meetings, unavailable meeting included',()=>{assert.equal(packet.meetings.length,3);assert.equal(packet.counts.unavailable_meetings,1);});
test('all original source segments and partitions included',()=>{assert.equal(packet.records.length,corpus.parents.length);assert.equal(packet.records.reduce((n,r)=>n+r.partitions.length,0),corpus.passages.length);});
test('no heldout identity, title, URL or transcript in review model',()=>{assert(!JSON.stringify(packet).includes('fixture/meeting2'));assert.equal(packet.holdout.transcripts_opened,0);});
test('every pending seed is explicitly unconfirmed',()=>assert(seed.choices.every(c=>c.confirmed===false&&c.reviewer===''&&c.reviewed_at==='')));
test('packet integrity verifies original and Unicode partition hashes',async()=>assert.equal((await B.validatePacket(packet)).sha256,packet.sha256));
test('tampered packet digest rejected',async()=>{const p=copy(packet);p.records[0].text+='change';await assert.rejects(B.validatePacket(p),/digest/);});
test('rehashed packet with wrong original text hash rejected',async()=>{const p=copy(packet);p.records[0].text+='change';delete p.sha256;await assert.rejects(B.validatePacket(C.seal(p)),/text digest/);});
test('rehashed packet with wrong partition hash rejected',async()=>{const p=copy(packet);p.records[0].partitions[0].text_sha256='0'.repeat(64);delete p.sha256;await assert.rejects(B.validatePacket(C.seal(p)),/Partition text/);});
test('source pointer cannot be changed',async()=>{const p=copy(packet);p.records[0].json_pointer='/other';delete p.sha256;await assert.rejects(B.validatePacket(C.seal(p)),/pointer/);});
test('external source links rejected',async()=>{const p=copy(packet);p.meetings[0].source_url='https://example.com';delete p.sha256;await assert.rejects(B.validatePacket(C.seal(p)),/source link/);});
test('unsafe cached-source path rejected',async()=>{const p=copy(packet);p.meetings[0].raw_file='../outside.json';delete p.sha256;await assert.rejects(B.validatePacket(C.seal(p)),/source path/);});
test('pending choices remain pending on import',()=>assert.equal(B.validateReview(packet,seed).choices.filter(c=>c.confirmed).length,0));
test('partial matching import preserves remaining pending choices',()=>{const r=B.validateReview(packet,withChoice(confirmed()));assert.equal(r.choices.length,seed.choices.length);assert.equal(r.choices.filter(c=>c.confirmed).length,1);});
test('legacy contract import without packet digest is accepted',()=>{const r=withChoice(confirmed());delete r.packet_sha256;assert.equal(B.validateReview(packet,r).choices[0].confirmed,true);});
test('different source bundle rejected',()=>assert.throws(()=>B.validateReview(packet,{...seed,source_bundle_sha256:'a'.repeat(64)}),/different source/));
test('different packet version rejected',()=>assert.throws(()=>B.validateReview(packet,{...seed,packet_sha256:'a'.repeat(64)}),/different packet/));
test('heldout or unknown source ID rejected',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),id:'fixture/meeting2#0'})),/source ID/));
test('changed source text hash rejected',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),text_sha256:'0'.repeat(64)})),/hash/));
test('duplicate review IDs rejected',()=>assert.throws(()=>B.validateReview(packet,{...seed,choices:[confirmed(),confirmed()]}),/duplicate/));
test('unknown review field rejected',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),replacement_text:'changed'})),/Unknown review field/));
test('string confirmation is not coerced to true',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),confirmed:'true'})),/Confirmation/));
test('reviewer name required',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),reviewer:''})),/reviewer/));
test('source type required',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),type:null})),/type/));
test('complete speech requires ID',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),speech_id:null})),/speech ID/));
test('near-complete speech requires coverage note',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),extent:'near_complete'})),/missing part/));
test('valid near-complete note accepted',()=>assert.equal(B.validateReview(packet,withChoice({...confirmed(),extent:'near_complete',note:'SYNTHETIC opening absent'})).choices[0].confirmed,true));
test('future timestamp rejected',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),reviewed_at:'2999-01-01T00:00:00Z'})),/timestamp/));
test('timezone-free timestamp rejected',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),reviewed_at:'2020-01-01'})),/timestamp/));
test('oversized note rejected',()=>assert.throws(()=>B.validateReview(packet,withChoice({...confirmed(),note:'x'.repeat(10001)})),/Notes/));
test('shared speech cannot cross meetings',()=>{const a=confirmed(),b=confirmed(4);b.speech_id=a.speech_id;assert.throws(()=>B.validateReview(packet,{...seed,choices:[a,b]}),/Shared speech/);});
test('shared speech cannot conflict with recorded metadata',()=>{const a=confirmed(),b=confirmed(2);b.speech_id=a.speech_id;assert.throws(()=>B.validateReview(packet,{...seed,choices:[a,b]}),/Shared speech/);});
test('matching adjacent source segments may share explicit speech ID',()=>{const a=confirmed(),b=confirmed(1);b.speech_id=a.speech_id;assert.equal(B.validateReview(packet,{...seed,choices:[a,b]}).choices.filter(c=>c.confirmed).length,2);});
test('confirmed engineering choices pass current corpus rebuild',async()=>{const r=await G.validate(corpus,withChoice(confirmed()));assert.equal(r.confirmed,1);assert.equal(r.original_source_bundle_sha256,corpus.source_bundle.sha256);assert.equal(r.heldout_opened,false);});
test('already reviewed source decisions are preserved, not reset',()=>{const r=B.validateReview(packet,withChoice(confirmed()));const c=C.build(corpus.frame,corpus.source_bundle,r);assert.equal(B.seed(G.model(c).packet).choices[0].confirmed,true);});
test('empty original records remain reviewable',()=>assert(packet.records.some(r=>r.text===''&&r.partitions.length===0)));
test('builder refuses a changed and resealed derived corpus',()=>{const c=copy(corpus);c.parents[0].text+='x';delete c.sha256;assert.throws(()=>G.model(C.seal(c)),/re-derivation/);});
test('builder makes no network requests',async()=>{const old=globalThis.fetch;let calls=0;globalThis.fetch=()=>{calls++;throw Error('Network prohibited');};try{built=await G.build(corpus,path.join(temp,'packet'));assert.equal(calls,0);}finally{globalThis.fetch=old;}});
test('output cannot overwrite prior packet',async()=>assert.rejects(G.build(corpus,path.join(temp,'packet')),/NEW output/));
test('every cached source preserves exact original bytes',()=>{for(const m of packet.meetings.filter(m=>m.raw_file)){const raw=fs.readFileSync(path.join(temp,'packet',m.raw_file));assert.equal(C.sha(raw),m.raw_sha256);assert(raw.equals(Buffer.from(corpus.source_bundle.sources.find(s=>s.meeting_id===m.meeting_id).raw_base64,'base64')));}});
test('HTML data encoding prevents closing-script injection',()=>{const html=fs.readFileSync(path.join(temp,'packet/index.html'),'utf8');assert(!html.includes('</script><img'));assert(html.includes('connect-src \'none\''));assert(html.includes('\\u003cscript\\u003e'));});
test('source placeholder-like text is never interpreted as a template',()=>{const html=G.render(packet);const data=html.match(/<script type="application\/json" id="packet-data">([\s\S]*?)<\/script>/)[1];assert.equal(JSON.parse(data).records[0].text,packet.records[0].text);});
test('browser scripts and styles are hash-bound in CSP',()=>{const html=fs.readFileSync(path.join(temp,'packet/index.html'),'utf8');assert.equal((html.match(/sha256-/g)||[]).length,3);});
test('manifest declares zero generated decisions and source requests',()=>{assert.equal(built.decisions_generated,0);assert.equal(built.new_source_requests,0);});
test('saved pending review validates with unchanged original source coverage',async()=>assert.equal((await G.validate(corpus,JSON.parse(fs.readFileSync(path.join(temp,'packet/review-template.json'))))).pending,packet.records.length));
test('deterministic rebuild produces identical packet artifacts',async()=>{await G.build(corpus,path.join(temp,'again'));assert.equal(fs.readFileSync(path.join(temp,'packet/SHA256SUMS.txt'),'utf8'),fs.readFileSync(path.join(temp,'again/SHA256SUMS.txt'),'utf8'));});
(async()=>{const checks=[];for(const t of tests){try{await t.run();checks.push({name:t.name,status:'PASS'});}catch(e){checks.push({name:t.name,status:'FAIL',error:e.stack});}}
 const result={schema:'un.boundary-packet-tests.v1',synthetic:true,passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length,checks};
 if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2)+'\n');
 console.log(JSON.stringify(result,null,2));fs.rmSync(temp,{recursive:true});if(result.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
