'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const [site,out]=process.argv.slice(2);if(!site||!out)throw Error('Usage: node tools/test_meeting_picker_ui.cjs SITE_OR_URL OUTPUT');fs.mkdirSync(out,{recursive:true});let server,url=site;
 if(!/^https?:/.test(site)){const root=path.resolve(site);server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]).replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch(e){res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/';}
 if(!url.endsWith('/'))url+='/';
 const browser=await chromium.launch({headless:true,...(process.env.PW_CHANNEL?{channel:process.env.PW_CHANNEL}:{})});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[],downloads=[],requests=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
  const date='2026-09-24',meetings=[{slug:'asset/test/first',title:'First Committee — engineering fixture',date,pageUrl:'/en/asset/test/first',jsonUrl:'/en/asset/test/first.json',hasTranscript:true},{slug:'asset/test/second',title:'Second Committee — engineering fixture',date,pageUrl:'/en/asset/test/second',jsonUrl:'/en/asset/test/second.json',hasTranscript:true},{slug:'asset/test/pending',title:'Pending meeting — engineering fixture',date,pageUrl:'/en/asset/test/pending',hasTranscript:false}];
  let mode='ok';
  await page.route('https://transcripts.un.org/**',async route=>{const req=route.request(),u=new URL(req.url());requests.push(u.href);let data;
    if(u.pathname==='/en/meetings.json'){
      if(mode==='fail'){await route.fulfill({status:503,headers:{'access-control-allow-origin':'*'},body:'Unavailable'});return;}
      if(mode==='empty')data={page:1,total:0,hasMore:false,meetings:[]};
      else if(mode==='missing')data={page:1,total:1,hasMore:false,meetings:[meetings[0]]};
      else {const n=Number(u.searchParams.get('page'));data={page:n,total:3,hasMore:n===1,meetings:n===1?[meetings[0]]:meetings.slice(1)};}
    }else{
      downloads.push(u.pathname);const slug=u.pathname.includes('second')?'asset/test/second':'asset/test/first';
      data={video:{slug,date},transcript:{language:'en',data:Array.from({length:6},(_,i)=>({speaker:{affiliation:'TEST'},pageUrl:'/en/'+slug+'?t='+i,paragraphs:[{sentences:[{text:['Ocean climate finance resilience alpha','Security peace diplomacy ceasefire bravo','Trade debt investment development charlie','Ocean maritime fisheries conservation delta','Nuclear disarmament strategic security echo','Sustainable development infrastructure finance foxtrot'][i]}]}]}))}};
    }
    await route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(data)});
  });
  await page.goto(url+'index.html#analyze');await page.waitForFunction(()=>document.querySelector('#region').options.length>2);
  await page.locator('#meetingSelectionMode').selectOption('single');await page.locator('#singleMeetingDate').fill(date);await page.locator('#findMeetings').click();await page.waitForFunction(()=>document.querySelector('#individualMeeting').options.length===4);
  assert.equal(downloads.length,0);assert.equal(await page.locator('#individualMeeting option[value="asset/test/pending"]').evaluate(o=>o.disabled),true,await page.locator('#individualMeeting').evaluate(s=>JSON.stringify(Array.from(s.options,o=>({value:o.value,disabled:o.disabled,text:o.textContent})))));checks.push('date lists all paginated meetings before downloading any transcript; unavailable item disabled');
  await page.locator('#individualMeeting').selectOption('asset/test/second');assert.equal(await page.locator('#startDate').inputValue(),date);assert.equal(await page.locator('#meetingScope').inputValue(),'all');assert.equal(await page.locator('#startDate').isDisabled(),true);await page.locator('#topic').fill('');
  await page.locator('#clusterMethod').check();await page.locator('details').filter({has:page.locator('#clusterCount')}).locator('summary').first().click();await page.locator('#clusterCount').fill('2');await page.locator('#umapNeighbors').fill('3');await page.locator('#stabilityEnabled').check();
  const run=async()=>{await page.locator('#runAnalysis').click();await page.waitForFunction(()=>!document.querySelector('#analysisOutput').hidden||document.querySelector('#analysisStatus').textContent.startsWith('Could not complete'),{},{timeout:90000});};
  await run();assert.equal(await page.locator('#analysisOutput').isVisible(),true,await page.locator('#analysisStatus').textContent());assert.deepEqual(downloads,['/en/asset/test/second.json']);
  const save=async(id,name)=>{const [d]=await Promise.all([page.waitForEvent('download'),page.locator('#'+id).click()]);await d.saveAs(path.join(out,name));return fs.readFileSync(path.join(out,name));};
  const result=JSON.parse(await save('exportResult','meeting-analysis.json'));assert.equal(result.counts.matched,6);assert.equal(result.collection.selected_meeting_slug,'asset/test/second');assert.equal(result.parameters.meeting_slug,'asset/test/second');assert.ok(result.matched.every(r=>r.meeting_slug==='asset/test/second'));assert.ok(result.methods.clusters.stability.skipped);checks.push('selected meeting alone drives clustering, denominators and source identity; one-meeting refit assessment withheld');
  const html=(await save('exportHTML','meeting-report.html')).toString();assert.ok(html.includes('Individual meeting:'));assert.ok(html.includes('Second Committee'));assert.ok(!/<script\b/i.test(html));const corpus=JSON.parse(await save('exportCorpus','meeting-transcripts.json'));assert.equal(corpus.collection.selected_meetings,1);await save('exportCSV','meeting-passages.csv');checks.push('source-linked report HTML, corpus, analysis JSON and CSV export retain the selected meeting');
  await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});checks.push('desktop/mobile date picker and report have no page overflow');
  await page.locator('#singleMeetingDate').fill('2026-09-25');assert.equal(await page.locator('#individualMeeting').isDisabled(),true);assert.equal(await page.locator('#exportResult').isDisabled(),true);checks.push('date change clears the selection and disables stale report exports');
  mode='empty';await page.locator('#findMeetings').click();await page.waitForFunction(()=>document.querySelector('#meetingListStatus').textContent.startsWith('No meetings'));checks.push('empty inventory explicitly qualified as a listing, not proof of no proceedings');
  mode='fail';await page.locator('#findMeetings').click();await page.waitForFunction(()=>document.querySelector('#meetingListStatus').textContent.startsWith('Could not list'));assert.equal(await page.locator('#individualMeeting').isDisabled(),true);checks.push('inventory failure is not a silent empty list');
  mode='ok';await page.locator('#singleMeetingDate').fill(date);await page.locator('#findMeetings').click();await page.waitForFunction(()=>document.querySelector('#individualMeeting').options.length===4);await page.locator('#individualMeeting').selectOption('asset/test/second');mode='missing';downloads.length=0;await run();assert.equal(await page.locator('#analysisOutput').isVisible(),false);assert.equal(downloads.length,0);assert.match(await page.locator('#analysisStatus').textContent(),/no other meeting was substituted/);checks.push('inventory changed after selection: no replacement transcript or partial report');
  assert.deepEqual(errors,[]);const validation={status:'PASS',source:url,synthetic_inventory:true,live_UN_inventory_tested:false,checks,check_count:checks.length,browser:browser.version(),errors,transcript_posts:0};fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(validation,null,2));console.log(JSON.stringify(validation));
 }finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
