/* Engineering choices are written only to the test output directory. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const [location,packetFile,out]=process.argv.slice(2);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
 try{const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[],uploads=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')uploads.push(r.url());});page.on('dialog',d=>d.accept());
 await page.goto(location.startsWith('http')?location:pathToFileURL(path.resolve(location)).href);
 if(location.startsWith('http'))await page.locator('#packet').setInputFiles(packetFile);
 await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('#audioDecision').inputValue(),'');assert.equal(await page.locator('#derive').isDisabled(),true);await page.waitForFunction(()=>document.querySelector('#player').readyState>=1);assert.ok(await page.locator('#player').evaluate(e=>e.duration>1));
 await page.locator('#reviewer').fill('ENGINEERING TEST ONLY');await page.locator('#audioDecision').selectOption('supported');await page.locator('#record').click();assert.match(await page.locator('#status').textContent(),/Listen/);
 await page.locator('#audioDecision').selectOption('mismatch');await page.locator('#listened').check();await page.locator('#record').click();assert.match(await page.locator('#status').textContent(),/Describe/);await page.locator('#listened').uncheck();await page.locator('#audioDecision').selectOption('unclear');await page.locator('#record').click();assert.match(await page.locator('#progress').textContent(),/1 of 24/);
 for(let i=1;i<12;i++){await page.locator('#audioDecision').selectOption('unclear');await page.locator('#record').click();}
 await page.screenshot({path:path.join(out,'audio-desktop.png')});await page.locator('#kind').selectOption('passage');
 assert.equal(await page.locator('#passageDecision').inputValue(),'');const originalEnd=await page.locator('#end').inputValue();await page.locator('#end').fill('999999');await page.locator('#passageDecision').selectOption('include');await page.locator('#record').click();assert.match(await page.locator('#status').textContent(),/offset/);await page.locator('#end').fill(originalEnd);
 await page.locator('details').filter({has:page.locator('#parentText')}).locator('summary').click();await page.evaluate(()=>{const t=document.querySelector('#parentText').firstChild,r=document.createRange();r.setStart(t,20);r.setEnd(t,100);getSelection().removeAllRanges();getSelection().addRange(r);});await page.locator('#selection').click();assert.equal(await page.locator('#start').inputValue(),'20');assert.equal(await page.locator('#end').inputValue(),'100');await page.locator('#start').fill('0');await page.locator('#end').fill(originalEnd);
 for(let i=0;i<12;i++){if(i===8){const packet=JSON.parse(fs.readFileSync(packetFile));await page.locator('#end').fill(String(packet.audio.find(a=>a.id==='A02').end));}await page.locator('#passageDecision').selectOption('include');await page.locator('#record').click();}
 assert.equal(await page.locator('#derive').isEnabled(),true);await page.locator('#note').fill('Unrecorded edit');assert.equal(await page.locator('#derive').isDisabled(),true);await page.locator('#save').click();assert.match(await page.locator('#status').textContent(),/Record your current/);await page.locator('#record').click();
 const [saved]=await Promise.all([page.waitForEvent('download'),page.locator('#save').click()]);const savedFile=path.join(out,'engineering-review.json');await saved.saveAs(savedFile);const review=JSON.parse(fs.readFileSync(savedFile));assert.equal(review.choices.length,24);assert.ok(review.choices.every(c=>c.reviewer==='ENGINEERING TEST ONLY'));
 const [derived]=await Promise.all([page.waitForEvent('download'),page.locator('#derive').click()]);await derived.saveAs(path.join(out,'engineering-units.json'));const units=JSON.parse(fs.readFileSync(path.join(out,'engineering-units.json')));assert.ok(units.records.length>0);assert.ok(units.withheld.length>0);assert.equal(units.originals_changed,false);
 await page.screenshot({path:path.join(out,'passages-desktop.png')});await page.setViewportSize({width:390,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#heading').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'passages-mobile.png')});
 await page.reload();if(location.startsWith('http'))await page.locator('#packet').setInputFiles(packetFile);await page.locator('#workspace').waitFor({state:'visible'});await page.locator('#resume').setInputFiles(savedFile);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Saved choices restored.'));assert.match(await page.locator('#progress').textContent(),/24 of 24/);
 const wrong={...review,packet_sha256:'0'.repeat(64)};fs.writeFileSync(path.join(out,'wrong.json'),JSON.stringify(wrong));await page.locator('#resume').setInputFiles(path.join(out,'wrong.json'));await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('different packet'));assert.match(await page.locator('#status').textContent(),/different packet/);assert.deepEqual(errors,[]);assert.deepEqual(uploads,[]);
 const result={status:'PASS',location,packet_import:true,audio_decodes:true,no_preselected_decisions:true,listening_attestation_required:true,offset_validation:true,selection_sets_offsets:true,unrecorded_edits_block_exports:true,save_resume:true,wrong_packet_rejected:true,unresolved_audio_excluded:true,derived_units_in_engineering_fixture:units.records.length,withheld_in_engineering_fixture:units.withheld.length,mobile_overflow:false,browser_errors:errors,uploads,human_decisions_created:false};fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
